import type { PlaylistItem } from "./eventConfig";

export const PLAYLIST_1: PlaylistItem[] = [
  { id: 1, title: "I Get Around", artist: "2Pac" },
  { id: 2, title: "Thunderstruck", artist: "AC DC" },
  { id: 3, title: "Because I Got High", artist: "Afroman" },
  { id: 4, title: "Eternity", artist: "Alex Warren" },
  { id: 5, title: "Cups", artist: "Anna Kendrick" },
  { id: 6, title: "positions", artist: "Ariana Grande" },
  { id: 7, title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys" },
  { id: 8, title: "Cruel Summer", artist: "Bananarama" },
  { id: 9, title: "You Gotta FIght for Your Right", artist: "Beastie Boys" },
  { id: 10, title: "I Got You", artist: "Bebe Rexha" },
  { id: 11, title: "Came Here To Forget", artist: "Blake Shelton" },
  { id: 12, title: "More Than A Feeling", artist: "Boston" },
  { id: 13, title: "One Hell Of An Amen", artist: "Brantley Gilbert" },
  { id: 14, title: "Just The Way You Are", artist: "Bruno Mars" },
  { id: 15, title: "Word Up", artist: "Cameo" },
  { id: 16, title: "Before He Cheats", artist: "Carrie Underwood" },
  { id: 17, title: "Gypsies Tramps and Thieves", artist: "Cher" },
  { id: 18, title: "Break Up In The End", artist: "Cole Swindell" },
  { id: 19, title: "True Colors", artist: "Cyndi Lauper" },
  { id: 20, title: "Dura", artist: "Daddy Yankee" },
  { id: 21, title: "Life After You", artist: "Daughtry" },
  { id: 22, title: "Play Hard", artist: "David Guetta" },
  { id: 23, title: "Bootylicious", artist: "Destiny's Child" },
  { id: 24, title: "Runaround Sue", artist: "Dion & The Belmonts" },
  { id: 25, title: "Danza Kuduro", artist: "Don Omar" },
  { id: 26, title: "Suspicious Minds", artist: "Dwight Yoakam" },
  { id: 27, title: "Sapphire", artist: "Ed Sheeran" },
  { id: 28, title: "Evil Woman", artist: "Electric Light Orchestra" },
  { id: 29, title: "Hold Me Closer", artist: "Elton John & Britney Spears" },
  { id: 30, title: "Sweet Dreams", artist: "Eurythmics" },
  { id: 31, title: "Praise You", artist: "Fatboy Slim" },
  { id: 32, title: "Everywhere", artist: "Fleetwood Mac" },
  { id: 33, title: "Only Happy When It Rains", artist: "Garbage" },
  { id: 34, title: "Blame It On Me", artist: "George Ezra" },
  { id: 35, title: "Summer Nights", artist: "Grease (Soundtrack)" },
  { id: 36, title: "What Is Love", artist: "Haddaway" },
  { id: 37, title: "I'm Into Something Good", artist: "Herman's Hermits" },
  { id: 38, title: "Thunder", artist: "Imagine Dragons" },
  { id: 39, title: "Escapade", artist: "Janet Jackson" },
  { id: 40, title: "In The Morning", artist: "Jennifer Lopez" },
  { id: 41, title: "Straight Tequila Night", artist: "John Anderson" },
  {
    id: 42,
    title: "Shell Shocked",
    artist: "Juicy J, Wiz Khalifa, Ty Dolla $ign",
  },
  { id: 43, title: "What Do You Mean", artist: "Justin Bieber" },
  { id: 44, title: "Tik Tok", artist: "Ke$ha" },
  { id: 45, title: "The Gambler", artist: "Kenny Rogers" },
  { id: 46, title: "Celebration", artist: "Kool & the Gang" },
  { id: 47, title: "Young and Beautiful", artist: "Lana Del Rey" },
  { id: 48, title: "Funkytown", artist: "Lipps Inc." },
  { id: 49, title: "Amazed", artist: "Lonestar" },
  { id: 50, title: "7 Years", artist: "Lukas Graham" },
  { id: 51, title: "Papa Don't Preach", artist: "Madonna" },
  { id: 52, title: "One More Night", artist: "Maroon 5" },
  { id: 53, title: "It's A Beautiful Day", artist: "Michael Buble" },
  { id: 54, title: "America", artist: "Neil Diamond" },
  { id: 55, title: "Calendar Girl", artist: "Neil Sedaka" },
  { id: 56, title: "I Only Want To Be With You", artist: "Nicolette Larson" },
  { id: 57, title: "Story Of My Life", artist: "One Direction" },
  { id: 58, title: "Silly Love Songs", artist: "Paul McCartney" },
  { id: 59, title: "Harden My Heart", artist: "Quarterflash" },
  { id: 60, title: "Fight Song", artist: "Rachel Platten" },
  { id: 61, title: "Escape (The Pina Colada Song)", artist: "Rupert Holmes" },
  { id: 62, title: "A Bar Song (Tipsy)", artist: "Shaboozey" },
  { id: 63, title: "All I Wanna Do", artist: "Sheryl Crow" },
  { id: 64, title: "We Are Family", artist: "Sister Sledge" },
  { id: 65, title: "Hey Cinderella", artist: "Suzy Bogguss" },
  { id: 66, title: "Tell It To My Heart", artist: "Taylor Dayne" },
  { id: 67, title: "Boom Boom Pow", artist: "The Black Eyed Peas" },
  { id: 68, title: "Working My Way Back To You", artist: "The Four Seasons" },
  { id: 69, title: "Dumas Walker", artist: "The Kentucky Headhunters" },
  { id: 70, title: "Only The Lonely", artist: "The Motels" },
  { id: 71, title: "Be My Baby", artist: "The Ronettes" },
  { id: 72, title: "She's Not There", artist: "The Zombies" },
  { id: 73, title: "Beer For My Horses", artist: "Toby Keith" },
  { id: 74, title: "Falling", artist: "Trevor Daniel" },
  { id: 75, title: "This Life", artist: "Vampire Weekend" },
];

export const PLAYLIST_2: PlaylistItem[] = [
  { id: 1, title: "Kryptonite", artist: "3 Doors Down" },
  { id: 2, title: "You Shock Me All Night Long", artist: "AC DC" },
  { id: 3, title: "Chattahoochee", artist: "Alan Jackson" },
  { id: 4, title: "Forever Young", artist: "Alphaville" },
  { id: 5, title: "Heat of the Moment", artist: "Asia" },
  { id: 6, title: "Pompeii", artist: "Bastille" },
  { id: 7, title: "Box Me Up", artist: "BigXthaPlug & Jelly Roll" },
  { id: 8, title: "Uptown Girl", artist: "Billy Joel" },
  { id: 9, title: "Bring It All To Me", artist: "Blaque" },
  { id: 10, title: "All The Small Things", artist: "Blink 182" },
  { id: 11, title: "I Want Candy", artist: "Bow Wow Wow" },
  { id: 12, title: "Footing", artist: "BRENN!" },
  { id: 13, title: "Lucky", artist: "Britney Spears" },
  { id: 14, title: "Summer of '69", artist: "Bryan Adams" },
  {
    id: 15,
    title: "Ain't No Rest For The Wicked",
    artist: "Cage the Elephant",
  },
  { id: 16, title: "You're So Vain", artist: "Carly Simon" },
  { id: 17, title: "Attention", artist: "Charlie Puth" },
  { id: 18, title: "Rockabye", artist: "Clean Bandit" },
  { id: 19, title: "A Sky Full Of Stars", artist: "Coldplay" },
  { id: 20, title: "Mr Jones", artist: "Counting Crows" },
  { id: 21, title: "Cupid Shuffle", artist: "Cupid" },
  { id: 22, title: "Daylight", artist: "David Kushner" },
  { id: 23, title: "Smoke on the Water", artist: "Deep Purple" },
  { id: 24, title: "We're Good", artist: "Dua Lipa" },
  { id: 25, title: "Party All The Time", artist: "Eddie Murphy" },
  { id: 26, title: "Bennie and the Jets", artist: "Elton John" },
  { id: 27, title: "Viva Las Vegas", artist: "Elvis Presley" },
  { id: 28, title: "Hero", artist: "Enrique Iglesias" },
  { id: 29, title: "The Final Countdown", artist: "Europe" },
  { id: 30, title: "Dog Days Are Over", artist: "Florence & The Machine" },
  { id: 31, title: "The Pretender", artist: "Foo Fighters" },
  { id: 32, title: "Come Fly With Me", artist: "Frank Sinatra" },
  { id: 33, title: "Slide", artist: "Goo Goo Dolls" },
  { id: 34, title: "American Idiot", artist: "Green Day" },
  { id: 35, title: "Love Myself", artist: "Hailee Steinfeld" },
  { id: 36, title: "So Yesterday", artist: "Hilary Duff" },
  { id: 37, title: "Let It Go", artist: "Idina Menzel" },
  { id: 38, title: "Rhythm Nation", artist: "Janet Jackson" },
  { id: 39, title: "Eastbound and Down", artist: "Jerry Reed" },
  { id: 40, title: "Rocky Mountain High", artist: "John Denver" },
  { id: 41, title: "Issues", artist: "Julia Michaels" },
  { id: 42, title: "Can't Stop The Feeling", artist: "Justin Timberlake" },
  { id: 43, title: "Firework", artist: "Katy Perry" },
  { id: 44, title: "When You Say Nothing At All", artist: "Keith Whitley" },
  { id: 45, title: "Danger Zone", artist: "Kenny Loggins" },
  { id: 46, title: "Rain On Me", artist: "Lady Gaga & Ariana Grande" },
  { id: 47, title: "Stay", artist: "Lisa Loeb" },
  {
    id: 48,
    title: "Don't Leave Me Now",
    artist: "Lost Frequencies & Mathieu Koss",
  },
  { id: 49, title: "Despacito", artist: "Luis Fonsi" },
  { id: 50, title: "Fly", artist: "Maddie & Tae" },
  { id: 51, title: "Safe In The Arms Of Love", artist: "Martina McBride" },
  { id: 52, title: "Black or White", artist: "Michael Jackson" },
  { id: 53, title: "Wonder", artist: "Natalie Merchant" },
  { id: 54, title: "99 Luftballons", artist: "Nena" },
  { id: 55, title: "Sister Christian", artist: "Night Ranger" },
  { id: 56, title: "Counting Stars", artist: "OneRepublic" },
  { id: 57, title: "You Can Call Me Al", artist: "Paul Simon" },
  { id: 58, title: "Little Red Corvette", artist: "Prince" },
  { id: 59, title: "Bohemian Rhapsody", artist: "Queen" },
  { id: 60, title: "Push It", artist: "Salt-N-Pepa" },
  { id: 61, title: "Angel", artist: "Shaggy" },
  { id: 62, title: "Treat You Better", artist: "Shawn Mendes" },
  { id: 63, title: "The Tears of a Clown", artist: "Smokey Robinson" },
  {
    id: 64,
    title: "Signed, Sealed, Delivered I'm Yours",
    artist: "Stevie Wonder",
  },
  { id: 65, title: "Blank Space", artist: "Taylor Swift" },
  { id: 66, title: "I Think I Like You", artist: "The Band Camino" },
  { id: 67, title: "Goodbye Earl", artist: "The Chicks" },
  { id: 68, title: "Walk Away Renee", artist: "The Four Tops" },
  { id: 69, title: "Pretty Fly (For A White Guy)", artist: "The Offspring" },
  { id: 70, title: "1979", artist: "The Smashing Pumpkins" },
  { id: 71, title: "Never Let You Go", artist: "Third Eye Blind" },
  { id: 72, title: "The Motto", artist: "Tiesto & Ava Max" },
  { id: 73, title: "Free Fallin", artist: "Tom Petty and the Heartbreakers" },
  { id: 74, title: "She's In Love With The Boy", artist: "Trisha Yearwood" },
  { id: 75, title: "Hot For Teacher", artist: "Van Halen" },
];

export const PLAYLIST_3: PlaylistItem[] = [
  { id: 1, title: "Let Me Go", artist: "3 Doors Down" },
  { id: 2, title: "How Long", artist: "Ace" },
  { id: 3, title: "All Out of Love", artist: "Air Supply" },
  { id: 4, title: "Ordinary", artist: "Alex Warren" },
  { id: 5, title: "Honey I'm Good", artist: "Andy Grammer" },
  { id: 6, title: "Airplanes", artist: "B.o.B" },
  { id: 7, title: "More Than A Woman", artist: "Bee Gees" },
  { id: 8, title: "Rock Around the Clock", artist: "Bill Haley" },
  { id: 9, title: "We Didn't Start The Fire", artist: "Billy Joel" },
  { id: 10, title: "Footloose", artist: "Blake Shelton" },
  { id: 11, title: "Hooked On A Feeling", artist: "Blue Swede" },
  { id: 12, title: "1985", artist: "Bowling for Soup" },
  { id: 13, title: "Southern Comfort Zone", artist: "Brad Paisley" },
  { id: 14, title: "Boot Scootin' Boogie", artist: "Brooks & Dunn" },
  { id: 15, title: "When I Was Your Man", artist: "Bruno Mars" },
  { id: 16, title: "On My Mind", artist: "Carin Leon" },
  { id: 17, title: "Church Bells", artist: "Carrie Underwood" },
  { id: 18, title: "Le Freak", artist: "Chic" },
  { id: 19, title: "Let's Twist Again", artist: "Chubby Checker" },
  { id: 20, title: "Gasolina", artist: "Daddy Yankee" },
  { id: 21, title: "Tequila", artist: "Dan + Shay" },
  { id: 22, title: "Home", artist: "Daughtry" },
  { id: 23, title: "Let's Dance", artist: "David Bowie" },
  { id: 24, title: "Whip It", artist: "Devo" },
  { id: 25, title: "Son Of A Preacher Man", artist: "Dusty Springfield" },
  { id: 26, title: "Bad Habits", artist: "Ed Sheeran" },
  { id: 27, title: "Dame Tu Cosita", artist: "El Chombo" },
  {
    id: 28,
    title: "I Guess That's Why They Call It The Blues",
    artist: "Elton John",
  },
  { id: 29, title: "Love The Way You Lie", artist: "Eminem" },
  { id: 30, title: "Bring Me To Life", artist: "Evanescence" },
  { id: 31, title: "Blueberry Hill", artist: "Fats Domino" },
  { id: 32, title: "Superman", artist: "Five For Fighting" },
  { id: 33, title: "I Can't Dance", artist: "Genesis" },
  { id: 34, title: "I Cross My Heart", artist: "George Strait" },
  { id: 35, title: "November Rain", artist: "Guns N' Roses" },
  { id: 36, title: "I Can't Go For That", artist: "Hall & Oates" },
  { id: 37, title: "Lips Of An Angel", artist: "Hinder" },
  { id: 38, title: "Bad Boys", artist: "Inner Circle" },
  { id: 39, title: "Burnin' It Down", artist: "Jason Aldean" },
  { id: 40, title: "Surface Pressure", artist: "Jessica Darrow" },
  { id: 41, title: "All of Me", artist: "John Legend" },
  { id: 42, title: "Don't Stop Believin'", artist: "Journey" },
  { id: 43, title: "Mirrors", artist: "Justin Timberlake" },
  { id: 44, title: "Carry On Wayward Son", artist: "Kansas" },
  { id: 45, title: "Part Of Me", artist: "Katy Perry" },
  { id: 46, title: "Raise 'Em Up", artist: "Keith Urban" },
  { id: 47, title: "Bette Davis Eyes", artist: "Kim Carnes" },
  { id: 48, title: "Firestone", artist: "Kygo" },
  { id: 49, title: "Drunk On You", artist: "Luke Bryan" },
  { id: 50, title: "Bittersweet", artist: "Madison Beer" },
  { id: 51, title: "Light It Up", artist: "Major Lazer" },
  { id: 52, title: "Sugar", artist: "Maroon 5" },
  { id: 53, title: "Everywhere", artist: "Michelle Branch" },
  { id: 54, title: "You'll Never Know", artist: "Mindy McCready" },
  { id: 55, title: "Animal", artist: "Neon Trees" },
  { id: 56, title: "Wouldn't It Be Good", artist: "Nik Kershaw" },
  { id: 57, title: "Hey Ya!", artist: "OutKast" },
  { id: 58, title: "Straight Up", artist: "Paula Abdul" },
  { id: 59, title: "Black Betty", artist: "Ram Jam" },
  { id: 60, title: "Forever and Ever, Amen", artist: "Randy Travis" },
  { id: 61, title: "House Party", artist: "Sam Hunt" },
  { id: 62, title: "It Ain't Me", artist: "Selena Gomez" },
  { id: 63, title: "Leave the Door Open", artist: "Silk Sonic" },
  { id: 64, title: "Kiss Me", artist: "Sixpence None the Richer" },
  { id: 65, title: "We Built This City", artist: "Starship" },
  { id: 66, title: "Stuck Like Glue", artist: "Sugarland" },
  { id: 67, title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
  { id: 68, title: "Light My Fire", artist: "The Doors" },
  { id: 69, title: "Mr Brightside", artist: "The Killers" },
  { id: 70, title: "Creeque Alley", artist: "The Mamas & The Papas" },
  { id: 71, title: "End Of The Line", artist: "The Traveling Wilburys" },
  { id: 72, title: "I Think We're Alone Now", artist: "Tiffany" },
  { id: 73, title: "Crimson & Clover", artist: "Tommy James" },
  { id: 74, title: "Leader of the Pack", artist: "Twisted Sister" },
  { id: 75, title: "Brown Eyed Girl", artist: "Van Morrison" },
];

export const PLAYLIST_4: PlaylistItem[] = [
  { id: 1, title: "Mood", artist: "24kGoldn" },
  { id: 2, title: "All That She Wants", artist: "Ace of Base" },
  { id: 3, title: "It's 5 O'Clock Somewhere", artist: "Alan Jackson" },
  { id: 4, title: "Obsession", artist: "Animotion" },
  { id: 5, title: "Barbie Girl", artist: "Aqua" },
  { id: 6, title: "Think", artist: "Aretha Franklin" },
  { id: 7, title: "Side to Side", artist: "Ariana Grande" },
  { id: 8, title: "Who’s Dat Girl", artist: "Ayra Starr, Rema" },
  { id: 9, title: "If I Had $1,000,000", artist: "Barenaked Ladies" },
  { id: 10, title: "Surfin USA", artist: "The Beach Boys" },
  { id: 11, title: "Meant To Be", artist: "Bebe Rexha" },
  { id: 12, title: "You May Be Right", artist: "Billy Joel" },
  { id: 13, title: "Already Gone", artist: "Brett Dennen" },
  { id: 14, title: "Oops", artist: "Britney Spears" },
  { id: 15, title: "Boy With Luv", artist: "BTS" },
  { id: 16, title: "Kung Fu Fighting", artist: "Carl Douglas" },
  { id: 17, title: "Everytime We Touch", artist: "Cascada" },
  { id: 18, title: "This Is America", artist: "Childish Gambino" },
  { id: 19, title: "Girls Just Want To Have Fun", artist: "Cyndi Lauper" },
  { id: 20, title: "Shaky Shaky", artist: "Daddy Yankee" },
  { id: 21, title: "Welcome to Jamrock", artist: "Damian Marley" },
  { id: 22, title: "This", artist: "Darius Rucker" },
  { id: 23, title: "Just A Gigolo", artist: "David Lee Roth" },
  { id: 24, title: "Strawberry Wine", artist: "Deana Carter" },
  { id: 25, title: "Say So", artist: "Doja Cat" },
  { id: 26, title: "South of the Border", artist: "Ed Sheeran" },
  { id: 27, title: "Pinball Wizard", artist: "Elton John" },
  { id: 28, title: "Creepin'", artist: "Eric Church" },
  { id: 29, title: "Inside Out", artist: "Eve 6" },
  { id: 30, title: "I Will Buy You A New Life", artist: "Everclear" },
  { id: 31, title: "Right Round", artist: "Flo Rida" },
  { id: 32, title: "Relax", artist: "Frankie Goes To Hollywood" },
  { id: 33, title: "Killing Me Softly", artist: "Fugees" },
  { id: 34, title: "La Gozadera", artist: "Gente de Zona" },
  { id: 35, title: "Follow You Down", artist: "Gin Blossoms" },
  { id: 36, title: "King of Wishful Thinking", artist: "Go West" },
  { id: 37, title: "Bad At Love", artist: "Halsey" },
  { id: 38, title: "The Reason", artist: "Hoobastank" },
  { id: 39, title: "Need You Tonight", artist: "INXS" },
  { id: 40, title: "I'm Yours", artist: "Jason Mraz" },
  {
    id: 41,
    title: "These Boots Are Made For Walking",
    artist: "Jessica Simpson",
  },
  { id: 42, title: "Say", artist: "John Mayer" },
  { id: 43, title: "Let Me Love You", artist: "Justin Bieber" },
  { id: 44, title: "Last Friday Night", artist: "Katy Perry" },
  { id: 45, title: "Stronger", artist: "Kelly Clarkson" },
  { id: 46, title: "Born This Way", artist: "Lady Gaga" },
  { id: 47, title: "I Hope You Dance", artist: "Lee Ann Womack" },
  { id: 48, title: "Boondocks", artist: "Little Big Town" },
  { id: 49, title: "Reality", artist: "Lost Frequencies" },
  { id: 50, title: "Forever After All", artist: "Luke Combs" },
  { id: 51, title: "Lucky Star", artist: "Madonna" },
  { id: 52, title: "Please Mr Postman", artist: "The Marvelettes" },
  {
    id: 53,
    title: "Phantom of the Opera",
    artist: "Michael Crawford & Sarah Brightman",
  },
  { id: 54, title: "In The Summertime", artist: "Mungo Jerry" },
  { id: 55, title: "Candy Girl", artist: "New Edition" },
  { id: 56, title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { id: 57, title: "High Hopes", artist: "Panic! at the Disco" },
  { id: 58, title: "Major Tom", artist: "Peter Schilling" },
  { id: 59, title: "Killer Queen", artist: "Queen" },
  { id: 60, title: "Round and Round", artist: "Ratt" },
  { id: 61, title: "Desire", artist: "Sam Smith" },
  { id: 62, title: "Hips Don't Lie", artist: "Shakira" },
  { id: 63, title: "Senorita", artist: "Shawn Mendes, Camila Cabello" },
  { id: 64, title: "The Logical Song", artist: "Supertramp" },
  { id: 65, title: "Eye Of The Tiger", artist: "Survivor" },
  { id: 66, title: "Shake It Off", artist: "Taylor Swift" },
  { id: 67, title: "Walk Like An Egyptian", artist: "The Bangles" },
  { id: 68, title: "Rock The Casbah", artist: "The Clash" },
  { id: 69, title: "Louie Louie", artist: "The Kingsmen" },
  { id: 70, title: "The Kids Aren't Alright", artist: "The Offspring" },
  { id: 71, title: "Start Me Up", artist: "The Rolling Stones" },
  { id: 72, title: "Happy Together", artist: "The Turtles" },
  { id: 73, title: "I Like It I Love It", artist: "Tim McGraw" },
  { id: 74, title: "Ride", artist: "Twenty One Pilots" },
  {
    id: 75,
    title: "The Night the Lights Went Out in Georgia",
    artist: "Vicki Lawrence",
  },
];

export const PLAYLIST_5: PlaylistItem[] = [
  { id: 1, title: "Hold On Loosely", artist: "38 Special" },
  { id: 2, title: "Beautiful Life", artist: "Ace of Base" },
  { id: 3, title: "Lost in Love", artist: "Air Supply" },
  { id: 4, title: "Sk8er Boi", artist: "Avril Lavigne" },
  { id: 5, title: "I Want It That Way", artist: "Backstreet Boys" },
  { id: 6, title: "Come and Get It", artist: "Badfinger" },
  { id: 7, title: "Mayores", artist: "Becky G & Bad Bunny" },
  { id: 8, title: "Heaven is a Place on Earth", artist: "Belinda Carlisle" },
  { id: 9, title: "People Are Crazy", artist: "Billy Currington" },
  { id: 10, title: "Heart of Glass", artist: "Blondie" },
  { id: 11, title: "Run Around", artist: "Blues Traveler" },
  { id: 12, title: "Waiting for a Star to Fall", artist: "Boy Meets Girl" },
  { id: 13, title: "Water", artist: "Brad Paisley" },
  { id: 14, title: "My Maria", artist: "Brooks & Dunn" },
  { id: 15, title: "That’s What I Like", artist: "Bruno Mars" },
  { id: 16, title: "The Distance", artist: "Cake" },
  { id: 17, title: "Cowboy Casanova", artist: "Carrie Underwood" },
  {
    id: 18,
    title: "Devil Went Down To Georgia",
    artist: "The Charlie Daniels Band",
  },
  { id: 19, title: "Left And Right", artist: "Charlie Puth" },
  { id: 20, title: "It's In His Kiss", artist: "Cher" },
  { id: 21, title: "Jar of Hearts", artist: "Christina Perri" },
  {
    id: 22,
    title: "Something Just Like This",
    artist: "Coldplay & The Chainsmokers",
  },
  { id: 23, title: "Alright", artist: "Darius Rucker" },
  { id: 24, title: "Come On Eileen", artist: "Dexy's Midnight Runners" },
  { id: 25, title: "Hotline Bling", artist: "Drake" },
  { id: 26, title: "You're Welcome", artist: "Dwayne Johnson" },
  { id: 27, title: "A Little More", artist: "Ed Sheeran" },
  { id: 28, title: "Mr", artist: "Electric Light Orchestra" },
  { id: 29, title: "Bailando", artist: "Enrique Iglesias" },
  { id: 30, title: "More Than Words", artist: "Extreme" },
  { id: 31, title: "Cruise", artist: "Florida Georgia Line" },
  {
    id: 32,
    title: "Big Girls Don't Cry",
    artist: "Frankie Valli & the Four Seasons",
  },
  { id: 33, title: "We Are Young", artist: "fun." },
  {
    id: 34,
    title: "Lifestyles of the Rich & Famous",
    artist: "Good Charlotte",
  },
  { id: 35, title: "Hollaback Girl", artist: "Gwen Stefani" },
  { id: 36, title: "Fool", artist: "Handsome Ghost" },
  { id: 37, title: "Take Me To Church", artist: "Hozier" },
  { id: 38, title: "First Class", artist: "Jack Harlow" },
  { id: 39, title: "Boogie", artist: "Jealous Friend" },
  { id: 40, title: "Papi", artist: "Jennifer Lopez" },
  { id: 41, title: "Jack & Dianne", artist: "John Mellencamp" },
  { id: 42, title: "Constant Craving", artist: "K.D. Lang" },
  { id: 43, title: "I Kissed A Girl", artist: "Katy Perry" },
  { id: 44, title: "No Shoes, No Shirt, No Problems", artist: "Kenny Chesney" },
  { id: 45, title: "Hideaway", artist: "Kiesza" },
  { id: 46, title: "Disease", artist: "Lady Gaga" },
  { id: 47, title: "Everything Is Everything", artist: "Lauryn Hill" },
  { id: 48, title: "Girl Crush", artist: "Little Big Town" },
  { id: 49, title: "What A Wonderful World", artist: "Louis Armstrong" },
  { id: 50, title: "Fast", artist: "Luke Bryan" },
  { id: 51, title: "Lean On", artist: "Major Lazer & DJ Snake" },
  { id: 52, title: "2 Legit 2 Quit", artist: "MC Hammer" },
  { id: 53, title: "Me and Mrs Jones", artist: "Michael Buble" },
  {
    id: 54,
    title: "I Need Never Know",
    artist: "Nathaniel Rateliff & The Night Sweats",
  },
  { id: 55, title: "All Down Hill From Here", artist: "New Found Glory" },
  { id: 56, title: "Don't Speak", artist: "No Doubt" },
  { id: 57, title: "Hit Me With Your Best Shot", artist: "Pat Benatar" },
  { id: 58, title: "Happy", artist: "Pharrell Williams" },
  { id: 59, title: "Raspberry Beret", artist: "Prince" },
  { id: 60, title: "Life Is A Highway", artist: "Rascal Flatts" },
  { id: 61, title: "Smooth", artist: "Santana" },
  { id: 62, title: "Waka Waka", artist: "Shakira" },
  { id: 63, title: "Next to You, Next to Me", artist: "Shenandoah" },
  { id: 64, title: "6 Underground", artist: "Sneaker Pimps" },
  { id: 65, title: "I Can't Hold Back", artist: "Survivor" },
  {
    id: 66,
    title: "We Are Never Ever Getting Back Together",
    artist: "Taylor Swift",
  },
  { id: 67, title: "Let's Get It Started", artist: "The Black Eyed Peas" },
  { id: 68, title: "How to Save a Life", artist: "The Fray" },
  { id: 69, title: "Under the Sea", artist: "The Little Mermaid" },
  { id: 70, title: "Your Love", artist: "The Outfield" },
  { id: 71, title: "Bitter Sweet Symphony", artist: "The Verve" },
  { id: 72, title: "No Scrubs", artist: "TLC" },
  { id: 73, title: "All I Want", artist: "Toad The Wet Sprocket" },
  { id: 74, title: "OMG", artist: "Usher" },
  { id: 75, title: "A Thousand Miles", artist: "Vanessa Carlton" },
];

export const PLAYLIST_6 = [
  { id: 1, title: "So Caught Up In You", artist: "38 Special" },
  { id: 2, title: "The Sign", artist: "Ace of Base" },
  { id: 3, title: "Summertime Blues", artist: "Alan Jackson" },
  { id: 4, title: "I Love the Nightlife", artist: "Alicia Bridges" },
  { id: 5, title: "Spooky", artist: "Atlanta Rhythm Section" },
  { id: 6, title: "Copacabana", artist: "Barry Manilow" },
  { id: 7, title: "If I Were A Boy", artist: "Beyonce" },
  { id: 8, title: "Cold", artist: "BigXthaPlug & Post Malone" },
  { id: 9, title: "Get Outta My Dreams", artist: "Billy Ocean" },
  { id: 10, title: "God Gave Me You", artist: "Blake Shelton" },
  { id: 11, title: "Don't Worry Be Happy", artist: "Bobby McFerrin" },
  { id: 12, title: "I'll Make Love To You", artist: "Boyz II Men" },
  { id: 13, title: "Country Must Be Country Wide", artist: "Brantley Gilbert" },
  { id: 14, title: "Red Dirt Road", artist: "Brooks & Dunn" },
  { id: 15, title: "DNA", artist: "BTS" },
  { id: 16, title: "La Bicicleta", artist: "Carlos Vives & Shakira" },
  { id: 17, title: "My Heart Will Go On", artist: "Celine Dion" },
  { id: 18, title: "If I Could Turn Back Time", artist: "Cher" },
  { id: 19, title: "Adventure of a lifetime", artist: "Coldplay" },
  { id: 20, title: "Con Calma", artist: "Daddy Yankee & Snow" },
  { id: 21, title: "When Doves Cry", artist: "Prince and the Revolution" },
  {
    id: 22,
    title: "You Spin Me Round (Like a Record)",
    artist: "Dead or Alive",
  },
  { id: 23, title: "Groove is in the Heart", artist: "Deee-Lite" },
  { id: 24, title: "Why Do Fools Fall In Love", artist: "Diana Ross" },
  { id: 25, title: "9 to 5", artist: "Dolly Parton" },
  { id: 26, title: "I'm Shipping Up To Boston", artist: "Dropkick Murphys" },
  { id: 27, title: "Azizam", artist: "Ed Sheeran" },
  { id: 28, title: "Sad Songs", artist: "Elton John" },
  { id: 29, title: "Sing For The Moment", artist: "Eminem" },
  { id: 30, title: "Breathe", artist: "Faith Hill" },
  { id: 31, title: "Big Girls Don't Cry", artist: "Fergie" },
  { id: 32, title: "Handclap", artist: "Fitz and The Tantrums" },
  { id: 33, title: "Check Yes or No", artist: "George Strait" },
  { id: 34, title: "You Belong To The City", artist: "Glenn Frey" },
  { id: 35, title: "Here For The Party", artist: "Gretchen Wilson" },
  { id: 36, title: "As It Was", artist: "Harry Styles" },
  { id: 37, title: "Cruisin", artist: "Huey Lewis & The News" },
  { id: 38, title: "Somebody's Baby", artist: "Jackson Browne" },
  { id: 39, title: "Dirt Road Anthem", artist: "Jason Aldean" },
  { id: 40, title: "Bang Bang", artist: "Jessie J" },
  { id: 41, title: "Love Me Again", artist: "John Newman" },
  { id: 42, title: "Lonely", artist: "Justin Bieber" },
  { id: 43, title: "What's Mine Is Yours", artist: "Kane Brown" },
  { id: 44, title: "Waking Up In Vegas", artist: "Katy Perry" },
  { id: 45, title: "Stole The Show", artist: "Kygo" },
  { id: 46, title: "Hold My Hand", artist: "Lady Gaga" },
  { id: 47, title: "I Drive Your Truck", artist: "Lee Brice" },
  { id: 48, title: "Black Magic", artist: "Little Mix" },
  { id: 49, title: "The Mummers' Dance", artist: "Loreena McKennitt" },
  { id: 50, title: "Hurricane", artist: "Luke Combs" },
  { id: 51, title: "Rude", artist: "MAGIC!" },
  { id: 52, title: "3 am", artist: "Matchbox Twenty" },
  { id: 53, title: "Party In The USA", artist: "Miley Cyrus" },
  { id: 54, title: "Lady Marmalade", artist: "Mya" },
  { id: 55, title: "You Get What You Give", artist: "New Radicals" },
  { id: 56, title: "Don't Know Why", artist: "Norah Jones" },
  { id: 57, title: "Misery Business", artist: "Paramore" },
  { id: 58, title: "In The Air Tonight", artist: "Phil Collins" },
  { id: 59, title: "Hit The Road Jack!", artist: "Ray Charles" },
  { id: 60, title: "Fancy", artist: "Reba McEntire" },
  { id: 61, title: "Born to Fly", artist: "Sara Evans" },
  { id: 62, title: "Any Man Of Mine", artist: "Shania Twain" },
  { id: 63, title: "Geronimo", artist: "Sheppard" },
  { id: 64, title: "All Star", artist: "Smash Mouth" },
  { id: 65, title: "King Tut", artist: "Steve Martin" },
  { id: 66, title: "High On You", artist: "Survivor" },
  { id: 67, title: "Get Back", artist: "The Beatles" },
  { id: 68, title: "Wherever You Will Go", artist: "The Calling" },
  { id: 69, title: "Breathless", artist: "The Corrs" },
  {
    id: 70,
    title: "Every Little Thing She Does Is Magic",
    artist: "The Police",
  },
  { id: 71, title: "The Lion Sleeps Tonight", artist: "The Tokens" },
  { id: 72, title: "It's Your Love", artist: "Tim McGraw & Faith Hill" },
  { id: 73, title: "8675309-Jenny", artist: "Tommy Tutone" },
  {
    id: 74,
    title: "Believe Me Baby I Lied",
    artist: "Trisha Yearwood & Kelly Clarkson",
  },
  { id: 75, title: "Riptide", artist: "Vance Joy" },
];

export const PLAYLIST_7 = [
  { id: 1, title: "Candy Shop", artist: "50 Cent" },
  { id: 2, title: "If I Had You", artist: "Adam Lambert" },
  { id: 3, title: "World's Smallest Violin", artist: "AJR" },
  { id: 4, title: "Potential Breakup Song", artist: "Aly & AJ" },
  { id: 5, title: "Depressed", artist: "Anne-Marie" },
  { id: 6, title: "Thank U Next", artist: "Ariana Grande" },
  { id: 7, title: "Wake Me Up", artist: "Avicii" },
  { id: 8, title: "Birds of a Feather", artist: "Billie Eilish" },
  { id: 9, title: "Achy Breaky Heart", artist: "Billy Ray Cyrus" },
  { id: 10, title: "Rapture", artist: "Blondie" },
  { id: 11, title: "Blaze of Glory", artist: "Bon Jovi" },
  { id: 12, title: "Bottoms Up", artist: "Brantley Gilbert" },
  { id: 13, title: "Don't Ya", artist: "Brett Eldredge" },
  { id: 14, title: "Stronger", artist: "Britney Spears" },
  { id: 15, title: "Dynamite", artist: "BTS" },
  { id: 16, title: "Summer", artist: "Calvin Harris" },
  { id: 17, title: "Dirty Laundry", artist: "Carrie Underwood" },
  { id: 18, title: "Marvin Gaye", artist: "Charlie Puth" },
  { id: 19, title: "Need a Bar Sometimes", artist: "Clay Walker" },
  { id: 20, title: "Flatliner", artist: "Cole Swindell" },
  { id: 21, title: "Mmm Mmm Mmm Mmm", artist: "Crash Test Dummies" },
  { id: 22, title: "Bills, Bills, Bills", artist: "Destiny's Child" },
  { id: 23, title: "Meet in the Middle", artist: "Diamond Rio" },
  { id: 24, title: "I Will Survive", artist: "Gloria Gaynor" },
  { id: 25, title: "The Wanderer", artist: "Dion & The Belmonts" },
  { id: 26, title: "Mercy", artist: "Duffy" },
  { id: 27, title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { id: 28, title: "Burn", artist: "Ellie Goulding" },
  { id: 29, title: "Round Here Buzz", artist: "Eric Church" },
  { id: 30, title: "The Way You Love Me", artist: "Faith Hill" },
  { id: 31, title: "Where Them Girls At", artist: "Flo Rida & Nicki Minaj" },
  { id: 32, title: "This is How We Roll", artist: "Florida Georgia Line" },
  { id: 33, title: "Careless Whisper", artist: "George Michael" },
  { id: 34, title: "The Anthem", artist: "Good Charlotte" },
  { id: 35, title: "Let Me Reintroduce Myself", artist: "Gwen Stefani" },
  { id: 36, title: "All I Wanna Do Is Make Love To You", artist: "Heart" },
  { id: 37, title: "Believer", artist: "Imagine Dragons" },
  { id: 38, title: "Lovin On Me", artist: "Jack Harlow" },
  { id: 39, title: "White Rabbit", artist: "Jefferson Airplane" },
  { id: 40, title: "Are You Gonna Be My Girl", artist: "Jet" },
  { id: 41, title: "A Boy Named Sue", artist: "Johnny Cash" },
  { id: 42, title: "Open Arms", artist: "Journey" },
  { id: 43, title: "Blue Ain't Your Color", artist: "Keith Urban" },
  { id: 44, title: "Footloose", artist: "Kenny Loggins" },
  { id: 45, title: "Downtown", artist: "Lady A" },
  { id: 46, title: "On The Road", artist: "Lee Roy Parnell" },
  { id: 47, title: "American Woman", artist: "Lenny Kravitz" },
  { id: 48, title: "Holiday", artist: "Little Mix" },
  {
    id: 49,
    title: "Huntin', Fishin' And Lovin' Every Day",
    artist: "Luke Bryan",
  },
  { id: 50, title: "Yes Baby", artist: "Madison Beer" },
  { id: 51, title: "I Need To Know", artist: "Marc Anthony" },
  { id: 52, title: "U Can't Touch This", artist: "MC Hammer" },
  { id: 53, title: "Rock With You", artist: "Michael Jackson" },
  { id: 54, title: "Sweet Caroline", artist: "Neil Diamond" },
  { id: 55, title: "Photograph", artist: "Nickelback" },
  { id: 56, title: "Wonderwall", artist: "Oasis" },
  { id: 57, title: "Fireflies", artist: "Owl City" },
  { id: 58, title: "Carlene", artist: "Phil Vassar" },
  { id: 59, title: "Firestarter", artist: "The Prodigy" },
  { id: 60, title: "Can't Stop", artist: "Red Hot Chili Peppers" },
  { id: 61, title: "Cotton Eye Joe", artist: "Rednex" },
  { id: 62, title: "Brave", artist: "Sara Bareilles" },
  { id: 63, title: "Forever And For Always", artist: "Shania Twain" },
  { id: 64, title: "I'm Just A Kid", artist: "Simple Plan" },
  { id: 65, title: "Chasing Cars", artist: "Snow Patrol" },
  { id: 66, title: "Once In A Lifetime", artist: "Talking Heads" },
  { id: 67, title: "Help", artist: "The Beatles" },
  { id: 68, title: "My Humps", artist: "The Black Eyed Peas" },
  { id: 69, title: "Our Lips Are Sealed", artist: "The Go-Gos" },
  { id: 70, title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
  { id: 71, title: "Under My Thumb", artist: "The Rolling Stones" },
  { id: 72, title: "Mony Mony", artist: "Tommy James" },
  { id: 73, title: "Dance Monkey", artist: "Tones and I" },
  { id: 74, title: "Save the Best For Last", artist: "Vanessa Williams" },
  { id: 75, title: "Ice Ice Baby", artist: "Vanilla Ice" },
];

export const PLAYLIST_8 = [
  { id: 1, title: "In Da Club", artist: "50 Cent" },
  { id: 2, title: "Hello", artist: "Adele" },
  { id: 3, title: "Faded", artist: "Alan Walker" },
  { id: 4, title: "It's All Been Done", artist: "Barenaked Ladies" },
  { id: 5, title: "I'm A Mess", artist: "Bebe Rexha" },
  { id: 6, title: "Beautiful Things", artist: "Benson Boone" },
  { id: 7, title: "Halo", artist: "Beyoncé" },
  { id: 8, title: "Fake I", artist: "Big & Rich" },
  { id: 9, title: "Everything I Wanted", artist: "Billie Eilish" },
  { id: 10, title: "Girl Like Me", artist: "Black Eyed Peas & Shakira" },
  { id: 11, title: "The Bad Touch", artist: "Bloodhound Gang" },
  { id: 12, title: "Livin' on a Prayer", artist: "Bon Jovi" },
  { id: 13, title: "Motownphilly", artist: "Boyz II Men" },
  { id: 14, title: "Kick It In The Sticks", artist: "Brantley Gilbert" },
  { id: 15, title: "That Ain't No Way to Go", artist: "Brooks & Dunn" },
  { id: 16, title: "The Lazy Song", artist: "Bruno Mars" },
  {
    id: 17,
    title: "How Deep Is Your Love",
    artist: "Calvin Harris & Disciples",
  },
  { id: 18, title: "Ghost Story", artist: "Carrie Underwood" },
  { id: 19, title: "Lollipop", artist: "The Chordettes" },
  { id: 20, title: "She Won't Be Lonely Long", artist: "Clay Walker" },
  { id: 21, title: "We Both Know", artist: "Colbie Caillat & Gavin DeGraw" },
  { id: 22, title: "Axel F", artist: "Crazy Frog" },
  { id: 23, title: "10,000 Hours", artist: "Dan + Shay" },
  { id: 24, title: "Bad Day", artist: "Daniel Powter" },
  { id: 25, title: "Lose My Breath", artist: "Destiny's Child" },
  { id: 26, title: "Drunk On A Plane", artist: "Dierks Bentley" },
  { id: 27, title: "Gorgeous", artist: "Doja Cat" },
  { id: 28, title: "Heavy Metal", artist: "Don Felder" },
  { id: 29, title: "God's Plan", artist: "Drake" },
  { id: 30, title: "Levitating", artist: "Dua Lipa" },
  { id: 31, title: "A Thousand Miles From Nowhere", artist: "Dwight Yoakam" },
  { id: 32, title: "Castle On The Hill", artist: "Ed Sheeran" },
  { id: 33, title: "Ex's & Oh's", artist: "Elle King" },
  { id: 34, title: "SUBEME LA RADIO", artist: "Enrique Iglesias" },
  { id: 35, title: "Paralyzer", artist: "Finger Eleven" },
  { id: 36, title: "What's Up", artist: "4 Non Blondes" },
  { id: 37, title: "Welcome to the Jungle", artist: "Guns N' Roses" },
  { id: 38, title: "Got Your Name On It", artist: "Jade Eagleson" },
  { id: 39, title: "Save Me", artist: "Jelly Roll" },
  { id: 40, title: "The Middle", artist: "Jimmy Eat World" },
  { id: 41, title: "Ring of Fire", artist: "Johnny Cash" },
  { id: 42, title: "Love Yourself", artist: "Justin Bieber" },
  { id: 43, title: "Be Like That", artist: "Kane Brown" },
  { id: 44, title: "Dark Horse", artist: "Katy Perry" },
  { id: 45, title: "Die Young", artist: "Ke$ha" },
  { id: 46, title: "Since U Been Gone", artist: "Kelly Clarkson" },
  { id: 47, title: "Shallow", artist: "Lady Gaga & Bradley Cooper" },
  { id: 48, title: "Long Tall Sally", artist: "Little Richard" },
  { id: 49, title: "Macarena", artist: "Los del Rio" },
  { id: 50, title: "Beer Never Broke My Heart", artist: "Luke Combs" },
  { id: 51, title: "Always Be My Baby", artist: "Mariah Carey" },
  { id: 52, title: "I'd Do Anything For Love", artist: "Meat Loaf" },
  { id: 53, title: "The Way You Make Me Feel", artist: "Michael Jackson" },
  { id: 54, title: "Unwritten", artist: "Natasha Bedingfield" },
  { id: 55, title: "My Friends Over You", artist: "New Found Glory" },
  { id: 56, title: "Little Talks", artist: "Of Monsters and Men" },
  { id: 57, title: "Let Her Go", artist: "Passenger" },
  { id: 58, title: "Gone, Gone, Gone", artist: "Philip Phillips" },
  { id: 59, title: "Gangnam Style", artist: "Psy" },
  { id: 60, title: "Shiny Happy People", artist: "R.E.M." },
  { id: 61, title: "King of Anything", artist: "Sara Bareilles" },
  { id: 62, title: "Buried A Lie", artist: "Senses Fail" },
  { id: 63, title: "The Glamorous Life", artist: "Sheila E" },
  { id: 64, title: "Why Can't We Be Friends", artist: "Smash Mouth" },
  { id: 65, title: "Oh Sherrie", artist: "Steve Perry" },
  { id: 66, title: "You Belong With Me", artist: "Taylor Swift" },
  { id: 67, title: "I Feel Fine", artist: "The Beatles" },
  { id: 68, title: "Summer Sunshine", artist: "The Corrs" },
  { id: 69, title: "Long Cool Woman in a Black Dress", artist: "The Hollies" },
  { id: 70, title: "I'm A Believer", artist: "The Monkees" },
  { id: 71, title: "Glad You Came", artist: "The Wanted" },
  { id: 72, title: "Mickey", artist: "Toni Basil" },
  { id: 73, title: "Knock Three Times", artist: "Tony Orlando & Dawn" },
  { id: 74, title: "I Still Haven't Found What I'm Looking For", artist: "U2" },
  { id: 75, title: "In The Navy", artist: "Village People" },
];

export const PLAYLIST_9 = [
  { id: 1, title: "I Do (Cherish You)", artist: "98º" },
  { id: 2, title: "Rolling in the Deep", artist: "Adele" },
  { id: 3, title: "Fallin'", artist: "Alicia Keys" },
  { id: 4, title: "Girlfriend", artist: "Avril Lavigne" },
  { id: 5, title: "Fire and Gold", artist: "Bea Miller" },
  { id: 6, title: "Intergalactic", artist: "Beastie Boys" },
  { id: 7, title: "Therefore I Am", artist: "Billie Eilish" },
  { id: 8, title: "Don't You Worry", artist: "Black Eyed Peas & Shakira" },
  { id: 9, title: "Hit 'em Up Style (Oops!)", artist: "Blu Cantrell" },
  { id: 10, title: "Wanted Dead or Alive", artist: "Bon Jovi" },
  { id: 11, title: "Two is Better Than One", artist: "Boys Like Girls" },
  { id: 12, title: "When I Get Where I'm Going", artist: "Brad Paisley" },
  { id: 13, title: "It Ain’t My Fault", artist: "Brothers Osborne" },
  { id: 14, title: "Havana", artist: "Camila Cabello" },
  { id: 15, title: "That's The Way It Is", artist: "Celine Dion" },
  { id: 16, title: "One Call Away", artist: "Charlie Puth" },
  { id: 17, title: "Dirty", artist: "Christina Aguilera" },
  { id: 18, title: "Hymn for the Weekend", artist: "Coldplay" },
  { id: 19, title: "Gangsta's Paradise", artist: "Coolio" },
  { id: 20, title: "Talk to Me", artist: "Damiano David & Tyla" },
  { id: 21, title: "Sexy Chick", artist: "David Guetta & Akon" },
  { id: 22, title: "Titanium", artist: "David Guetta & Sia" },
  { id: 23, title: "Pour Some Sugar on Me", artist: "Def Leppard" },
  { id: 24, title: "Perfect", artist: "Ed Sheeran" },
  { id: 25, title: "Tiny Dancer", artist: "Elton John" },
  { id: 26, title: "Without Me", artist: "Eminem" },
  { id: 27, title: "Talladega", artist: "Eric Church" },
  { id: 28, title: "This Kiss", artist: "Faith Hill" },
  { id: 29, title: "Epic", artist: "Faith No More" },
  { id: 30, title: "100 Years", artist: "Five For Fighting" },
  { id: 31, title: "Learn To Fly", artist: "Foo Fighters" },
  { id: 32, title: "Take Me Out", artist: "Franz Ferdinand" },
  { id: 33, title: "Cars", artist: "Gary Numan" },
  { id: 34, title: "Crazy", artist: "Gnarls Barkley" },
  { id: 35, title: "Maneater", artist: "Hall & Oates" },
  { id: 36, title: "Golden", artist: "Harry Styles" },
  { id: 37, title: "American Country Love Song", artist: "Jake Owen" },
  { id: 38, title: "Rearview Town", artist: "Jason Aldean" },
  { id: 39, title: "Take You Dancing", artist: "Jason Derulo" },
  { id: 40, title: "Dirt On My Boots", artist: "Jon Pardi" },
  { id: 41, title: "Eenie Meenie", artist: "Justin Bieber & Sean Kingston" },
  { id: 42, title: "Baby", artist: "Justin Bieber" },
  { id: 43, title: "Asking Us To Dance", artist: "Kathy Mattea" },
  { id: 44, title: "Cop Car", artist: "Keith Urban" },
  { id: 45, title: "Setting the World On Fire", artist: "Kenny Chesney" },
  { id: 46, title: "Telephone", artist: "Lady Gaga" },
  { id: 47, title: "Bleeding Love", artist: "Leona Lewis" },
  { id: 48, title: "Sweet Love", artist: "Liviu Hodor feat. Mona" },
  { id: 49, title: "The Feeling", artist: "Lost Frequencies" },
  { id: 50, title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { id: 51, title: "Ray Of Light", artist: "Madonna" },
  { id: 52, title: "Uptown Funk", artist: "Mark Ronson & Bruno Mars" },
  { id: 53, title: "All About That Bass", artist: "Meghan Trainor" },
  { id: 54, title: "Bad", artist: "Michael Jackson" },
  { id: 55, title: "The House That Built Me", artist: "Miranda Lambert" },
  {
    id: 56,
    title: "These Boots Are Made for Walkin'",
    artist: "Nancy Sinatra",
  },
  { id: 57, title: "It's My Life", artist: "No Doubt" },
  { id: 58, title: "Tearin' Up My Heart", artist: "NSYNC" },
  { id: 59, title: "According to You", artist: "Orianthi" },
  { id: 60, title: "You're My Best Friend", artist: "Queen" },
  { id: 61, title: "Super Freak", artist: "Rick James" },
  { id: 62, title: "Stay With Me", artist: "Sam Smith" },
  { id: 63, title: "If It Makes You Happy", artist: "Sheryl Crow" },
  { id: 64, title: "Everyday People", artist: "Sly & the Family Stone" },
  { id: 65, title: "Copperhead Road", artist: "Steve Earle" },
  { id: 66, title: "Buy You A Drank", artist: "T-Pain" },
  {
    id: 67,
    title: "Everybody Wants To Rule The World",
    artist: "Tears For Fears",
  },
  { id: 68, title: "Where Is The Love", artist: "The Black Eyed Peas" },
  { id: 69, title: "Close To You", artist: "The Carpenters" },
  { id: 70, title: "On Broadway", artist: "The Drifters" },
  { id: 71, title: "Beep", artist: "The Pussycat Dolls" },
  { id: 72, title: "Sympathy For The Devil", artist: "The Rolling Stones" },
  { id: 73, title: "Semi Charmed Life", artist: "Third Eye Blind" },
  { id: 74, title: "YMCA", artist: "Village People" },
  { id: 75, title: "Shut Up and Dance", artist: "Walk the Moon" },
];

export const PLAYLIST_10 = [
  { id: 1, title: "I Ran", artist: "A Flock of Seagulls" },
  { id: 2, title: "Rumor Has It", artist: "Adele" },
  { id: 3, title: "Hero", artist: "Alan Walker & Sasha Alex Sloan" },
  { id: 4, title: "Best Day of My Life", artist: "American Authors" },
  { id: 5, title: "Suga Suga", artist: "Baby Bash" },
  { id: 6, title: "Larger Than Life", artist: "Backstreet Boys" },
  { id: 7, title: "Dancing With Myself", artist: "Billy Idol" },
  { id: 8, title: "Every Once in a While", artist: "Blackhawk" },
  { id: 9, title: "Honey Bee", artist: "Blake Shelton" },
  { id: 10, title: "Something to Talk About", artist: "Bonnie Raitt" },
  { id: 11, title: "Toxic", artist: "BoyWithUke" },
  { id: 12, title: "Small Town Throwdown", artist: "Brantley Gilbert" },
  { id: 13, title: "Toxic", artist: "Britney Spears" },
  { id: 14, title: "Ms", artist: "Bubba Sparxxx" },
  { id: 15, title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { id: 16, title: "Jesus Take The Wheel", artist: "Carrie Underwood" },
  { id: 17, title: "Party 4 U", artist: "Charli XCX" },
  { id: 18, title: "It Was", artist: "Chely Wright" },
  { id: 19, title: "Ain't No Other Man", artist: "Christina Aguilera" },
  { id: 20, title: "Butterfly", artist: "Crazy Town" },
  { id: 21, title: "Sing Me To Sleep", artist: "Alan Walker" },
  { id: 22, title: "That's Amore", artist: "Dean Martin" },
  { id: 23, title: "5", artist: "Dierks Bentley" },
  { id: 24, title: "Anxiety", artist: "Doechii" },
  { id: 25, title: "American Pie", artist: "Don McLean" },
  { id: 26, title: "Sing", artist: "Ed Sheeran" },
  { id: 27, title: "All Over The World", artist: "Electric Light Orchestra" },
  { id: 28, title: "Cold Heart", artist: "Elton John & Dua Lipa" },
  { id: 29, title: "Centuries", artist: "Fall Out Boy" },
  { id: 30, title: "Work From Home", artist: "Fifth Harmony" },
  { id: 31, title: "Criminal", artist: "Fiona Apple" },
  { id: 32, title: "Go Your Own Way", artist: "Fleetwood Mac" },
  { id: 33, title: "Feel Good Inc", artist: "Gorillaz" },
  { id: 34, title: "The Sweet Escape", artist: "Gwen Stefani" },
  { id: 35, title: "Barracuda", artist: "Heart" },
  { id: 36, title: "Hip To Be Square", artist: "Huey Lewis & The News" },
  { id: 37, title: "Say You Won't Let Go", artist: "James Arthur" },
  { id: 38, title: "like", artist: "JENNIE" },
  { id: 39, title: "On The Floor", artist: "Jennifer Lopez" },
  { id: 40, title: "Leave Before You Love Me", artist: "Jonas Brothers" },
  { id: 41, title: "Roar", artist: "Katy Perry" },
  { id: 42, title: "She Thinks My Tractors Sexy", artist: "Kenny Chesney" },
  { id: 43, title: "I Run To You", artist: "Lady A" },
  { id: 44, title: "Shallow", artist: "Lady Gaga" },
  { id: 45, title: "Someone You Loved", artist: "Lewis Capaldi" },
  { id: 46, title: "You And Me", artist: "Lifehouse" },
  { id: 47, title: "Wings", artist: "Little Mix" },
  { id: 48, title: "Royals", artist: "Lorde" },
  { id: 49, title: "I Don't Want This Night To End", artist: "Luke Bryan" },
  { id: 50, title: "Girls Like You", artist: "Maroon 5" },
  { id: 51, title: "Two out of Three Ain't Bad", artist: "Meat Loaf" },
  {
    id: 52,
    title: "I'm Gonna Miss You Girl",
    artist: "Michael Martin Murphey",
  },
  { id: 53, title: "Breaking Up Is Hard To Do", artist: "Neil Sedaka" },
  { id: 54, title: "Hey Mama", artist: "Nicki Minaj" },
  { id: 55, title: "Here It Goes Again", artist: "OK Go" },
  {
    id: 56,
    title: "I Write Sins Not Tragedies",
    artist: "Panic! at the Disco",
  },
  { id: 57, title: "We Belong", artist: "Pat Benatar" },
  { id: 58, title: "Home", artist: "Philip Phillips" },
  { id: 59, title: "Jessie's Girl", artist: "Rick Springfield" },
  { id: 60, title: "Love Song", artist: "Sara Bareilles" },
  { id: 61, title: "Still The One", artist: "Shania Twain" },
  { id: 62, title: "Little Good Byes", artist: "SHeDAISY" },
  { id: 63, title: "Tainted Love", artist: "Soft Cell" },
  { id: 64, title: "AOK", artist: "Tai Verdes" },
  { id: 65, title: "Daydream", artist: "The Aces" },
  { id: 66, title: "Paperback Writer", artist: "The Beatles" },
  { id: 67, title: "Rawhide", artist: "The Blues Brothers" },
  { id: 68, title: "Hypnotize", artist: "The Notorious B.I.G." },
  { id: 69, title: "Buttons", artist: "The Pussycat Dolls" },
  { id: 70, title: "What I Like About You", artist: "The Romantics" },
  { id: 71, title: "Tie A Yellow Ribbon", artist: "Tony Orlando & Dawn" },
  { id: 72, title: "Chrome", artist: "Trace Adkins" },
  { id: 73, title: "Drift Away", artist: "Uncle Kracker" },
  { id: 74, title: "Everybody Have Fun Tonight", artist: "Wang Chung" },
  { id: 75, title: "Clarity", artist: "Zedd" },
];

export const PLAYLIST_11 = [
  { id: 1, title: "Take On Me", artist: "a ha" },
  { id: 2, title: "Someone Like You", artist: "Adele" },
  { id: 3, title: "Smack That", artist: "Akon" },
  {
    id: 4,
    title: "we can't be friends (wait for your love)",
    artist: "Ariana Grande",
  },
  { id: 5, title: "Who Let the Dogs Out", artist: "Baha Men" },
  { id: 6, title: "Sacrifice", artist: "Bebe Rexha" },
  { id: 7, title: "You Should Be Dancing", artist: "Bee Gees" },
  { id: 8, title: "Single Ladies (Put a Ring on It)", artist: "Beyoncé" },
  { id: 9, title: "Mony Mony", artist: "Billy Idol" },
  { id: 10, title: "I Miss You", artist: "Blink 182" },
  { id: 11, title: "You Give Love A Bad Name", artist: "Bon Jovi" },
  { id: 12, title: "I'm Gonna Miss Her", artist: "Brad Paisley" },
  { id: 13, title: "Mean To Me", artist: "Brett Eldredge" },
  { id: 14, title: "Born In The USA", artist: "Bruce Springsteen" },
  { id: 15, title: "Peggy Sue", artist: "Buddy Holly" },
  { id: 16, title: "Desire", artist: "Calvin Harris & Sam Smith" },
  { id: 17, title: "Yes!", artist: "Chad Brock" },
  { id: 18, title: "Residuals", artist: "Chris Brown" },
  { id: 19, title: "Tubthumping", artist: "Chumbawamba" },
  { id: 20, title: "Paradise", artist: "Coldplay" },
  { id: 21, title: "First Rodeo", artist: "Cooper Alan" },
  { id: 22, title: "Lost My Heartbreak", artist: "David J" },
  { id: 23, title: "Soul Meets Body", artist: "Death Cab for Cutie" },
  { id: 24, title: "Burning Man", artist: "Dierks Bentley" },
  { id: 25, title: "Drift Away", artist: "Dobie Gray" },
  { id: 26, title: "I Love A Rainy Night", artist: "Eddie Rabbitt" },
  { id: 27, title: "Don't Bring Me Down", artist: "Electric Light Orchestra" },
  { id: 28, title: "The Real Slim Shady", artist: "Eminem" },
  {
    id: 29,
    title: "My Songs Know What You Did In The Dark (Light Em Up)",
    artist: "Fall Out Boy",
  },
  { id: 30, title: "Like A G6", artist: "Far East Movement" },
  { id: 31, title: "Round Here", artist: "Florida Georgia Line" },
  { id: 32, title: "Cold As Ice", artist: "Foreigner" },
  { id: 33, title: "Got My Mind Set On You", artist: "George Harrison" },
  { id: 34, title: "Somebody That I Used To Know", artist: "Gotye" },
  { id: 35, title: "Basket Case", artist: "Green Day" },
  { id: 36, title: "Sign of the Times", artist: "Harry Styles" },
  { id: 37, title: "Bones", artist: "Imagine Dragons" },
  { id: 38, title: "Barefoot Blue Jean Night", artist: "Jake Owen" },
  { id: 39, title: "Swalla", artist: "Jason Derulo" },
  { id: 40, title: "Burn", artist: "Jo Dee Messina" },
  { id: 41, title: "Buy Dirt", artist: "Jordan Davis" },
  { id: 42, title: "Smile", artist: "Katy Perry" },
  { id: 43, title: "Need You Now", artist: "Lady A" },
  { id: 44, title: "Poker Face", artist: "Lady Gaga" },
  { id: 45, title: "Old Town Road", artist: "Lil Nas X" },
  {
    id: 46,
    title: "Prayer In C",
    artist: "Lilly Wood & The Prick and Robin Schulz",
  },
  { id: 47, title: "Go Insane", artist: "Lindsey Buckingham" },
  { id: 48, title: "Party Rock Anthem", artist: "LMFAO" },
  { id: 49, title: "Working For The Weekend", artist: "Loverboy" },
  { id: 50, title: "When It Rains It Pours", artist: "Luke Combs" },
  { id: 51, title: "Love Somebody", artist: "Maroon 5" },
  { id: 52, title: "Nothing Else Matters", artist: "Metallica" },
  { id: 53, title: "Billie Jean", artist: "Michael Jackson" },
  { id: 54, title: "Carnival", artist: "Natalie Merchant" },
  { id: 55, title: "Rockstar", artist: "Nickelback" },
  { id: 56, title: "Make It Sweet", artist: "Old Dominion" },
  {
    id: 57,
    title: "Blame It On You Lyin' Cheatin' Heart",
    artist: "Patty Loveless",
  },
  { id: 58, title: "Feel It Still", artist: "Portugal, The Man" },
  { id: 59, title: "Livin' La Vida Loca", artist: "Ricky Martin" },
  { id: 60, title: "I'm Too Sexy", artist: "Right Said Fred" },
  { id: 61, title: "Shoop", artist: "Salt-N-Pepa" },
  { id: 62, title: "Kiss From A Rose", artist: "Seal" },
  { id: 63, title: "Soak Up The Sun", artist: "Sheryl Crow" },
  { id: 64, title: "I Got You Babe", artist: "Sonny & Cher" },
  { id: 65, title: "Back In The High Life Again", artist: "Steve Winwood" },
  { id: 66, title: "Dirty Little Secret", artist: "The All-American Rejects" },
  { id: 67, title: "Sweet Home Chicago", artist: "The Blues Brothers" },
  {
    id: 68,
    title: "December, 1963 (Oh, What a Night)",
    artist: "The Four Seasons",
  },
  { id: 69, title: "Ho Hey", artist: "The Lumineers" },
  { id: 70, title: "I Hate This Part", artist: "The Pussycat Dolls" },
  { id: 71, title: "Can't Feel My Face", artist: "The Weeknd" },
  { id: 72, title: "Africa", artist: "Toto" },
  { id: 73, title: "Ten Rounds With Jose Cuervo", artist: "Tracy Byrd" },
  { id: 74, title: "Cherry Pie", artist: "Warrant" },
  { id: 75, title: "Werewolves Of London", artist: "Warren Zevon" },
];

export const PLAYLIST_12 = [
  { id: 1, title: "Are You That Somebody", artist: "Aaliyah" },
  { id: 2, title: "Crazy", artist: "Aerosmith" },
  { id: 3, title: "Black Velvet", artist: "Alannah Myles" },
  { id: 4, title: "Underdog", artist: "Alicia Keys" },
  { id: 5, title: "Walking on Broken Glass", artist: "Annie Lennox" },
  { id: 6, title: "Do I Wanna Know", artist: "Arctic Monkeys" },
  { id: 7, title: "The Tide is High", artist: "Atomic Kittens" },
  { id: 8, title: "Nothin' On You", artist: "B.o.B. feat. Bruno Mars" },
  { id: 9, title: "Tití Me Preguntó", artist: "Bad Bunny" },
  { id: 10, title: "Where's Your Head At", artist: "Basement Jaxx" },
  { id: 11, title: "Rebel Yell", artist: "Billy Idol" },
  { id: 12, title: "Some Beach", artist: "Blake Shelton" },
  { id: 13, title: "The Long Way", artist: "Brett Eldredge" },
  { id: 14, title: "Dancing In The Dark", artist: "Bruce Springsteen" },
  { id: 15, title: "That'll Be The Day", artist: "Buddy Holly" },
  { id: 16, title: "Good Time", artist: "Carly Rae Jepsen" },
  { id: 17, title: "Two Black Cadillacs", artist: "Carrie Underwood" },
  { id: 18, title: "See You Again", artist: "Charlie Puth" },
  { id: 19, title: "Sober Saturday Night", artist: "Chris Young" },
  { id: 20, title: "Rather Be", artist: "Clean Bandit" },
  { id: 21, title: "Sunglasses at Night", artist: "Corey Hart" },
  { id: 22, title: "Higher", artist: "Creed" },
  { id: 23, title: "Instant Crush", artist: "Daft Punk" },
  { id: 24, title: "Falling In love", artist: "Darin" },
  { id: 25, title: "Say My Name", artist: "Destiny's Child" },
  { id: 26, title: "Different For Girls", artist: "Dierks Bentley" },
  { id: 27, title: "The Sound Of Silence", artist: "Disturbed" },
  { id: 28, title: "Don't Start Now", artist: "Dua Lipa" },
  { id: 29, title: "Hell of a Night", artist: "Dustin Lynch" },
  { id: 30, title: "Save Tonight", artist: "Eagle Eye Cherry" },
  { id: 31, title: "Shape of You", artist: "Ed Sheeran" },
  { id: 32, title: "My House", artist: "Flo Rida" },
  { id: 33, title: "Stupid Girl", artist: "Garbage" },
  {
    id: 34,
    title: "Midnight Train to Georgia",
    artist: "Gladys Knight & the Pips",
  },
  { id: 35, title: "Redneck Woman", artist: "Gretchen Wilson" },
  { id: 36, title: "Nothin At All", artist: "Heart" },
  { id: 37, title: "Stuck With You", artist: "Huey Lewis & The News" },
  { id: 38, title: "Get Up Offa That Thing", artist: "James Brown" },
  { id: 39, title: "Try That In A Small Town", artist: "Jason Aldean" },
  { id: 40, title: "Crimson and Clover", artist: "Joan Jett" },
  { id: 41, title: "Queen of Hearts", artist: "Juice Newton" },
  { id: 42, title: "Sorry", artist: "Justin Bieber" },
  { id: 43, title: "Long Hot Summer", artist: "Keith Urban" },
  { id: 44, title: "Ma Mind", artist: "Chris Thrace" },
  { id: 45, title: "Jungle Boogie", artist: "Kool & the Gang" },
  { id: 46, title: "The Dead Dance", artist: "Lady Gaga" },
  { id: 47, title: "Holiday Way", artist: "Lindsey Buckingham" },
  { id: 48, title: "C.O.U.N.T.R.Y", artist: "LoCash" },
  { id: 49, title: "The Kind of Love We Make", artist: "Luke Combs" },
  { id: 50, title: "Material Girl", artist: "Madonna" },
  { id: 51, title: "Animals", artist: "Martin Garrix" },
  { id: 52, title: "Who Can It Be Now", artist: "Men At Work" },
  { id: 53, title: "All You Wanted", artist: "Michelle Branch" },
  { id: 54, title: "Lean On", artist: "MØ" },
  { id: 55, title: "Super Bass", artist: "Nicki Minaj" },
  { id: 56, title: "Hopelessly Devoted to You", artist: "Olivia Newton John" },
  { id: 57, title: "What, Me Worry", artist: "Portugal, The Man" },
  { id: 58, title: "I Wanna Be Your Lover", artist: "Prince" },
  {
    id: 59,
    title: "You've Lost That Loving Feeling",
    artist: "Righteous Brothers",
  },
  { id: 60, title: "This Is What You Came For", artist: "Rihanna" },
  { id: 61, title: "Affirmation", artist: "Savage Garden" },
  { id: 62, title: "That Don't Impress Me Much", artist: "Shania Twain" },
  { id: 63, title: "All For You", artist: "Sister Hazel" },
  { id: 64, title: "There She Goes", artist: "Sixpence None the Richer" },
  { id: 65, title: "Santeria", artist: "Sublime" },
  { id: 66, title: "GIves You Hell", artist: "The All-American Rejects" },
  { id: 67, title: "Revolution", artist: "The Beatles" },
  { id: 68, title: "You Might Think", artist: "The Cars" },
  { id: 69, title: "Holler Back", artist: "The Lost Trailers" },
  { id: 70, title: "Elvira", artist: "The Oak Ridge Boys" },
  { id: 71, title: "Baba O'Riley", artist: "The Who" },
  { id: 72, title: "Fast Car", artist: "Tracy Chapman" },
  { id: 73, title: "Hey, Soul Sister", artist: "Train" },
  { id: 74, title: "Follow Me", artist: "Uncle Kracker" },
  { id: 75, title: "Beverly Hills", artist: "Weezer" },
];

export const PLAYLIST_13 = [
  { id: 1, title: "Dancing Queen", artist: "ABBA" },
  { id: 2, title: "Dude (Looks Like a Lady)", artist: "Aerosmith" },
  { id: 3, title: "Dixieland Delight", artist: "Alabama" },
  { id: 4, title: "Valerie", artist: "Amy Winehouse" },
  { id: 5, title: "Whatever", artist: "Ava Max" },
  { id: 6, title: "Complicated", artist: "Avril Lavigne" },
  { id: 7, title: "Sail", artist: "Awolnation" },
  { id: 8, title: "Staying Alive", artist: "Bee Gees" },
  { id: 9, title: "White Wedding", artist: "Billy Idol" },
  { id: 10, title: "The Tide Is High", artist: "Blondie" },
  { id: 11, title: "Who Says You Can't Go Home", artist: "Bon Jovi" },
  { id: 12, title: "Punk Rock 101", artist: "Bowling for Soup" },
  { id: 13, title: "Whiskey Lullaby", artist: "Brad Paisley" },
  { id: 14, title: "You Drive Me Crazy", artist: "Britney Spears" },
  { id: 15, title: "Tuesday", artist: "Burak Yeter" },
  { id: 16, title: "Over Now", artist: "Calvin Harris & The Weeknd" },
  { id: 17, title: "I'm Every Woman", artist: "Chaka Khan" },
  { id: 18, title: "Boom Clap", artist: "Charli XCX" },
  { id: 19, title: "A Thousand Years", artist: "Christina Perri" },
  { id: 20, title: "The Scientist", artist: "Coldplay" },
  {
    id: 21,
    title: "Up Around the Bend",
    artist: "Creedence Clearwater Revival",
  },
  { id: 22, title: "I Can Dream About You", artist: "Dan Hartman" },
  { id: 23, title: "I Don't Wanna Wait", artist: "David Guetta & OneRepublic" },
  { id: 24, title: "Runaway", artist: "Del Shannon" },
  { id: 25, title: "Lose My Mind", artist: "Don Toliver" },
  { id: 26, title: "Houdini", artist: "Dua Lipa" },
  { id: 27, title: "Shivers", artist: "Ed Sheeran" },
  {
    id: 28,
    title: "My Lovin' You're Never Going To Get It",
    artist: "En Vogue",
  },
  { id: 29, title: "Call On Me", artist: "Eric Prydz" },
  { id: 30, title: "My Immortal", artist: "Evanescence" },
  { id: 31, title: "Drunken Lullabies", artist: "Flogging Molly" },
  { id: 32, title: "I Want to Know What Love Is", artist: "Foreigner" },
  {
    id: 33,
    title: "Ain't Going Down Til The Sun Comes Up",
    artist: "Garth Brooks",
  },
  { id: 34, title: "Budapest", artist: "George Ezra" },
  { id: 35, title: "Rhinestone Cowboy", artist: "Glen Campbell" },
  { id: 36, title: "Sweet Child o' Mine", artist: "Guns N' Roses" },
  { id: 37, title: "Private Eyes", artist: "Hall & Oates" },
  { id: 38, title: "I Was Jack (You Were Diane)", artist: "Jake Owen" },
  { id: 39, title: "Mantra", artist: "JENNIE" },
  { id: 40, title: "I Hate Myself For Loving You", artist: "Joan Jett" },
  { id: 41, title: "Sucker", artist: "Jonas Brothers" },
  { id: 42, title: "You Raise Me Up", artist: "Josh Groban" },
  { id: 43, title: "Homesick", artist: "Kane Brown" },
  { id: 44, title: "Praying", artist: "Ke$ha" },
  { id: 45, title: "Red High Heels", artist: "Kellie Pickler" },
  {
    id: 46,
    title: "When The Sun Goes Down",
    artist: "Kenny Chesney & Uncle Kracker",
  },
  { id: 47, title: "Die With A Smile", artist: "Lady Gaga & Bruno Mars" },
  { id: 48, title: "Like A Prayer", artist: "Miley Cyrus" },
  { id: 49, title: "Mambo No 5", artist: "Lou Bega" },
  { id: 50, title: "Most People Are Good", artist: "Luke Bryan" },
  { id: 51, title: "Dancing In The Streets", artist: "Martha & The Vandellas" },
  { id: 52, title: "Shake It", artist: "Metro Station" },
  { id: 53, title: "Beat It", artist: "Michael Jackson" },
  { id: 54, title: "I Melt With You", artist: "Modern English" },
  { id: 55, title: "Torn", artist: "Natalie Imbruglia" },
  { id: 56, title: "Bye Bye Bye", artist: "*NSYNC" },
  { id: 57, title: "What Makes You Beautiful", artist: "One Direction" },
  { id: 58, title: "Hurt Me Bad", artist: "Patty Loveless" },
  { id: 59, title: "Under Pressure", artist: "Queen" },
  { id: 60, title: "We Found Love", artist: "Rihanna" },
  { id: 61, title: "Wooly Bully", artist: "Sam the Sham and the Pharaohs" },
  { id: 62, title: "Up!", artist: "Shania Twain" },
  { id: 63, title: "Johnny Angel", artist: "Shelley Fabares" },
  { id: 64, title: "Candy Rain", artist: "Soul For Real" },
  { id: 65, title: "Rock This Town", artist: "Stray Cats" },
  { id: 66, title: "Sugar, Sugar", artist: "The Archies" },
  { id: 67, title: "Video Killed The Radio Star", artist: "The Buggles" },
  { id: 68, title: "Closer", artist: "The Chainsmokers" },
  { id: 69, title: "Dreams", artist: "The Cranberries" },
  { id: 70, title: "Build Me Up Buttercup", artist: "The Foundations" },
  { id: 71, title: "Who Are You", artist: "The Who" },
  { id: 72, title: "How Do You Like Me Now", artist: "Toby Keith" },
  { id: 73, title: "Headstrong", artist: "Trapt" },
  { id: 74, title: "Buddy Holly", artist: "Weezer" },
  { id: 75, title: "Tacky", artist: "Weird Al Yankovic" },
];

export const PLAYLIST_14 = [
  { id: 1, title: "S.O.S.", artist: "ABBA" },
  { id: 2, title: "I Don't Want to Miss a Thing", artist: "Aerosmith" },
  { id: 3, title: "Stay", artist: "Alessia Cara" },
  { id: 4, title: "MÍA", artist: "Bad Bunny" },
  { id: 5, title: "One Week", artist: "Barenaked Ladies" },
  { id: 6, title: "Kokomo", artist: "Beach Boys" },
  { id: 7, title: "Sin Pijama", artist: "Becky G" },
  { id: 8, title: "Save a Horse (Ride a Cowboy)", artist: "Big and Rich" },
  { id: 9, title: "It's Still Rock and Roll To Me", artist: "Billy Joel" },
  { id: 10, title: "I'll Name The Dogs", artist: "Blake Shelton" },
  { id: 11, title: "Holding Out For A Hero", artist: "Bonnie Tyler" },
  { id: 12, title: "Mud on the Tires", artist: "Brad Paisley" },
  { id: 13, title: "Hurricane", artist: "Bridgit Mendler" },
  { id: 14, title: "Glory Days", artist: "Bruce Springsteen" },
  { id: 15, title: "TaTaTa", artist: "Burna Boy" },
  { id: 16, title: "My Oh My", artist: "Camila Cabello" },
  { id: 17, title: "The Subway", artist: "Chappell Roan" },
  { id: 18, title: "We Don't Talk Anymore", artist: "Charlie Puth" },
  { id: 19, title: "Raised on Country", artist: "Chris Young" },
  { id: 20, title: "Killin' Time", artist: "Clint Black" },
  { id: 21, title: "I Think About You", artist: "Collin Raye" },
  { id: 22, title: "Time After Time", artist: "Cyndi Lauper" },
  { id: 23, title: "Wagon Wheel", artist: "Darius Rucker" },
  { id: 24, title: "Panda", artist: "Desiigner" },
  { id: 25, title: "September", artist: "Earth Wind & Fire" },
  { id: 26, title: "I'll be", artist: "Edwin McCain" },
  { id: 27, title: "Jailhouse Rock", artist: "Elvis Presley" },
  { id: 28, title: "Hungry Eyes", artist: "Eric Carmen" },
  { id: 29, title: "Sugar, We're Going Down", artist: "Fall Out Boy" },
  { id: 30, title: "The Way", artist: "Fastball" },
  { id: 31, title: "Peru", artist: "Fireboy DML & Ed Sheeran" },
  { id: 32, title: "Stacy's Mom", artist: "Fountains of Wayne" },
  { id: 33, title: "Iris", artist: "Goo Goo Dolls" },
  { id: 34, title: "Backroad Song", artist: "Granger Smith" },
  { id: 35, title: "Treat People With Kindness", artist: "Harry Styles" },
  { id: 36, title: "These Dreams", artist: "Heart" },
  { id: 37, title: "Enemy", artist: "Imagine Dragons" },
  { id: 38, title: "I Feel Good", artist: "James Brown" },
  { id: 39, title: "Lifestyle", artist: "Jason Derulo" },
  { id: 40, title: "One Of Us", artist: "Joan Osborne" },
  { id: 41, title: "Singles You Up", artist: "Jordan Davis" },
  { id: 42, title: "Anyone", artist: "Justin Bieber" },
  { id: 43, title: "Bandaids", artist: "Katy Perry" },
  { id: 44, title: "Already Gone", artist: "Kelly Clarkson" },
  { id: 45, title: "Abracadabra", artist: "Lady Gaga" },
  { id: 46, title: "Heart Like A Truck", artist: "Lainey Wilson" },
  { id: 47, title: "In The End", artist: "Linkin Park" },
  { id: 48, title: "Don't Get Better Than That", artist: "LoCash" },
  { id: 49, title: "Where Are You Now", artist: "Lost Frequencies" },
  { id: 50, title: "Sunrise, Sunburn, Sunset", artist: "Luke Bryan" },
  { id: 51, title: "Memories", artist: "Maroon 5" },
  {
    id: 52,
    title: "How Am I supposed To Live Without You",
    artist: "Michael Bolton",
  },
  { id: 53, title: "The Climb", artist: "Miley Cyrus" },
  { id: 54, title: "Pocketful of Sunshine", artist: "Natasha Bedingfield" },
  { id: 55, title: "You're the One That I Want", artist: "Olivia Newton John" },
  { id: 56, title: "How Bizarre", artist: "OMC" },
  { id: 57, title: "Love Is A Battlefield", artist: "Pat Benatar" },
  { id: 58, title: "Circles", artist: "Post Malone" },
  { id: 59, title: "Hold On Forever", artist: "Rob Thomas" },
  { id: 60, title: "Somebody's Watching Me", artist: "Rockwell" },
  { id: 61, title: "Naturally", artist: "Selena Gomez" },
  { id: 62, title: "Sunny Came Home", artist: "Shawn Colvin" },
  { id: 63, title: "Venus", artist: "Shocking Blue" },
  { id: 64, title: "I'm A Believer", artist: "Smash Mouth" },
  { id: 65, title: "Abracadabra", artist: "Steve Miller Band" },
  { id: 66, title: "Love Shack", artist: "The B-52's" },
  { id: 67, title: "Don't You Forget About Me", artist: "The Barden Bellas" },
  { id: 68, title: "Don't Let Me Down", artist: "The Chainsmokers" },
  { id: 69, title: "Linger", artist: "The Cranberries" },
  { id: 70, title: "When I Grow Up", artist: "The Pussycat Dolls" },
  { id: 71, title: "Leader of the Pack", artist: "The Shangri-Las" },
  {
    id: 72,
    title: "Into the Great Wide Open",
    artist: "Tom Petty and the Heartbreakers",
  },
  { id: 73, title: "Play That Song", artist: "Train" },
  { id: 74, title: "Smile", artist: "Uncle Kracker" },
  { id: 75, title: "I Wanna Dance With Somebody", artist: "Whitney Houston" },
];

export const PLAYLIST_15 = [
  { id: 1, title: "Take a Chance on Me", artist: "ABBA" },
  { id: 2, title: "Janie's Got A Gun", artist: "Aerosmith" },
  { id: 3, title: "Song of the South", artist: "Alabama" },
  { id: 4, title: "When You Say Nothing At All", artist: "Alison Krauss" },
  { id: 5, title: "Rush", artist: "Ayra Starr" },
  { id: 6, title: "Shape Of My Heart", artist: "Backstreet Boys" },
  { id: 7, title: "No Sleep Til Brooklyn", artist: "Beastie Boys" },
  { id: 8, title: "Just The Way You Are", artist: "Billy Joel" },
  { id: 9, title: "No Diggity", artist: "Blacksteet" },
  { id: 10, title: "Ol' Red", artist: "Blake Shelton" },
  { id: 11, title: "Total Eclipse of the Heart", artist: "Bonnie Tyler" },
  { id: 12, title: "Old Alabama", artist: "Brad Paisley" },
  { id: 13, title: "...Baby One More Time", artist: "Britney Spears" },
  { id: 14, title: "24K Magic", artist: "Bruno Mars" },
  { id: 15, title: "For My Hand", artist: "Burna Boy & Ed Sheeran" },
  { id: 16, title: "Safe", artist: "Cardi B" },
  { id: 17, title: "Boys", artist: "Charli XCX" },
  { id: 18, title: "Wicked Game", artist: "Chris Isaak" },
  { id: 19, title: "Famous Friends", artist: "Chris Young" },
  { id: 20, title: "On The Verge", artist: "Collin Raye" },
  { id: 21, title: "Woodstock", artist: "Crosby, Stills & Nash" },
  { id: 22, title: "Digital Love", artist: "Daft Punk" },
  { id: 23, title: "Crash Into Me", artist: "Dave Matthews Band" },
  { id: 24, title: "Give Your Heart a Break", artist: "Demi Lovato" },
  { id: 25, title: "Boogie Wonderland", artist: "Earth Wind & Fire" },
  { id: 26, title: "Lights", artist: "Ellie Goulding" },
  { id: 27, title: "Return To Sender", artist: "Elvis Presley" },
  { id: 28, title: "Walking On A Dream", artist: "Empire Of The Sun" },
  { id: 29, title: "I Shot The Sheriff", artist: "Eric Clapton" },
  { id: 30, title: "Uma Thurman", artist: "Fall Out Boy" },
  { id: 31, title: "Worth It", artist: "Fifth Harmony" },
  { id: 32, title: "The Chain", artist: "Fleetwood Mac" },
  { id: 33, title: "Some Nights", artist: "fun." },
  { id: 34, title: "Faith", artist: "George Michael" },
  { id: 35, title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { id: 36, title: "Watermelon Sugar", artist: "Harry Styles" },
  { id: 37, title: "Eyes Closed", artist: "Imagine Dragons" },
  { id: 38, title: "Living In America", artist: "James Brown" },
  { id: 39, title: "Want to Want Me", artist: "Jason Derulo" },
  { id: 40, title: "Third Rock From The Sun", artist: "Joe Diffie" },
  { id: 41, title: "Any Way You Want It", artist: "Journey" },
  { id: 42, title: "The Fighter", artist: "Keith Urban & Carrie Underwood" },
  { id: 43, title: "Better", artist: "Khalid" },
  { id: 44, title: "Somethin' 'Bout A Truck", artist: "Kip Moore" },
  { id: 45, title: "Bad Romance", artist: "Lady Gaga" },
  { id: 46, title: "Numb", artist: "Linkin Park" },
  { id: 47, title: "Leap Of Faith", artist: "Lionel Cartwright" },
  { id: 48, title: "Sexy and I Know It", artist: "LMFAO" },
  { id: 49, title: "Do You Believe In Magic", artist: "Lovin' Spoonful" },
  { id: 50, title: "Country Girl (Shake It For Me)", artist: "Luke Bryan" },
  { id: 51, title: "Vogue", artist: "Madonna" },
  { id: 52, title: "Haven't Met You Yet", artist: "Michael Buble" },
  { id: 53, title: "Wrecking Ball", artist: "Miley Cyrus" },
  {
    id: 54,
    title: "Welcome To The Black Parade",
    artist: "My Chemical Romance",
  },
  { id: 55, title: "Am I Wrong", artist: "Nico & Vinz" },
  { id: 56, title: "Cheerleader", artist: "OMI" },
  { id: 57, title: "Ms", artist: "OutKast" },
  { id: 58, title: "Congratulations", artist: "Post Malone" },
  { id: 59, title: "Blurred Lines", artist: "Robin Thicke" },
  { id: 60, title: "Stranger In My House", artist: "Ronnie Milsap" },
  { id: 61, title: "Rock You Like A Hurricane", artist: "Scorpions" },
  { id: 62, title: "Stitches", artist: "Shawn Mendes" },
  { id: 63, title: "Chandelier", artist: "Sia" },
  { id: 64, title: "Wannabe", artist: "Spice Girls" },
  { id: 65, title: "She's So High", artist: "Tal Bachman" },
  { id: 66, title: "Fortnight", artist: "Taylor Swift feat. Post Malone" },
  { id: 67, title: "Mr Tambourine Man", artist: "The Byrds" },
  { id: 68, title: "I Want You Back", artist: "The Jackson 5" },
  { id: 69, title: "Juicy", artist: "The Notorious B.I.G." },
  { id: 70, title: "I'll Be There For You", artist: "The Rembrandts" },
  { id: 71, title: "My Girl", artist: "The Temptations" },
  { id: 72, title: "Rosanna", artist: "Toto" },
  { id: 73, title: "Trouble", artist: "Travis Tritt" },
  { id: 74, title: "Island In The Sun", artist: "Weezer" },
  { id: 75, title: "I Will Always Love You", artist: "Whitney Houston" },
];

export const PLAYLIST_16 = [
  { id: 1, title: "Waterloo", artist: "ABBA" },
  { id: 2, title: "Sweet Emotion", artist: "Aerosmith" },
  { id: 3, title: "Bloodline", artist: "Alex Warren" },
  {
    id: 4,
    title: "Time To Say Goodbye",
    artist: "Andrea Bocelli & Sarah Brightman",
  },
  { id: 5, title: "DÁKITI EL ÚLTIMO TOUR DEL MUNDO", artist: "Bad Bunny" },
  { id: 6, title: "Mad About You", artist: "Belinda Carlisle" },
  { id: 7, title: "Poison", artist: "Bell Biv DeVoe" },
  { id: 8, title: "Piano Man", artist: "Billy Joel" },
  { id: 9, title: "Boys 'Round Here", artist: "Blake Shelton" },
  { id: 10, title: "Dear Anxiety", artist: "Blu Eyes" },
  { id: 11, title: "Green Onions", artist: "Booker T. & the M.G.'s" },
  { id: 12, title: "Remind Me", artist: "Brad Paisley" },
  { id: 13, title: "Circus", artist: "Britney Spears" },
  { id: 14, title: "Grenade", artist: "Bruno Mars" },
  { id: 15, title: "Gonna Make You Sweat", artist: "C&C Music Factory" },
  { id: 16, title: "I Like It", artist: "Cardi B" },
  { id: 17, title: "I Really Like You", artist: "Carly Rae Jepsen" },
  { id: 18, title: "Believe", artist: "Cher" },
  { id: 19, title: "The One and Only", artist: "Chesney Hawkes" },
  { id: 20, title: "Tennessee Whiskey", artist: "Chris Stapleton" },
  { id: 21, title: "Genie in a Bottle", artist: "Christina Aguilera" },
  { id: 22, title: "Bubbly", artist: "Colbie Caillat" },
  { id: 23, title: "Yellow", artist: "Coldplay" },
  { id: 24, title: "Little Rock", artist: "Collin Raye" },
  { id: 25, title: "Breakfast at Tiffany's", artist: "Deep Blue Something" },
  { id: 26, title: "I Say A Little Prayer", artist: "Dionne Warwick" },
  { id: 27, title: "Jolene", artist: "Dolly Parton" },
  { id: 28, title: "Still D", artist: "Dr. Dre & Snoop Dogg" },
  { id: 29, title: "New Rules", artist: "Dua Lipa" },
  { id: 30, title: "Two Tickets to Paradise", artist: "Eddie Money" },
  { id: 31, title: "Home", artist: "Edward Sharpe & The Magnetic Zeros" },
  { id: 32, title: "Blue", artist: "Eiffel 65" },
  { id: 33, title: "Handlebars", artist: "Flobots" },
  { id: 34, title: "Unforgettable", artist: "French Montana" },
  { id: 35, title: "Friends In Low Places", artist: "Garth Brooks" },
  { id: 36, title: "Cupid's Chokehold", artist: "Gym Class Heroes" },
  { id: 37, title: "There's a Kind of Hush", artist: "Herman's Hermits" },
  { id: 38, title: "Radioactive", artist: "Imagine Dragons" },
  { id: 39, title: "Here's Your Perfect", artist: "Jamie Miller" },
  { id: 40, title: "Watcha Say", artist: "Jason Derulo" },
  { id: 41, title: "Domino", artist: "Jessie J" },
  {
    id: 42,
    title: "Tequila Makes Her Clothes Fall Off",
    artist: "Joe Nichols",
  },
  { id: 43, title: "Honest", artist: "Justin Bieber" },
  { id: 44, title: "Too Shy", artist: "Kajagoogoo" },
  { id: 45, title: "Champagne Problems", artist: "Katy Perry" },
  { id: 46, title: "Blah Blah Blah", artist: "Ke$ha" },
  { id: 47, title: "Breakaway", artist: "Kelly Clarkson" },
  { id: 48, title: "All Summer Long", artist: "Kid Rock" },
  { id: 49, title: "Rock and Roll All Night", artist: "Kiss" },
  { id: 50, title: "Are You With Me", artist: "Lost Frequencies" },
  { id: 51, title: "I Try", artist: "Macy Gray" },
  { id: 52, title: "Nobody's Love", artist: "Maroon 5" },
  { id: 53, title: "Home", artist: "Michael Bublé" },
  { id: 54, title: "Stolen Dance", artist: "Milky Chance" },
  { id: 55, title: "Whiskey Glasses", artist: "Morgan Wallen" },
  { id: 56, title: "The Shake", artist: "Neal McCoy" },
  { id: 57, title: "Everybody Talks", artist: "Neon Trees" },
  { id: 58, title: "Deja Vu", artist: "Olivia Rodrigo" },
  { id: 59, title: "1999", artist: "Prince" },
  { id: 60, title: "Tonight's The Night", artist: "Rod Stewart" },
  { id: 61, title: "Oh, Pretty Woman", artist: "Roy Orbison" },
  { id: 62, title: "Closing Time", artist: "Semisonic" },
  { id: 63, title: "Cheap Thrills", artist: "Sia" },
  { id: 64, title: "Walkin' On The Sun", artist: "Smash Mouth" },
  { id: 65, title: "Every Morning", artist: "Sugar Ray" },
  { id: 66, title: "Kill Bill", artist: "SZA" },
  { id: 67, title: "Roam", artist: "The B-52's" },
  { id: 68, title: "Hard To Handle", artist: "The Black Crowes" },
  { id: 69, title: "Don't You Want Me", artist: "The Human League" },
  { id: 70, title: "Satisfaction", artist: "The Rolling Stones" },
  { id: 71, title: "Leave The Pieces", artist: "The Wreckers" },
  { id: 72, title: "Waterfalls", artist: "TLC" },
  { id: 73, title: "Made In America", artist: "Toby Keith" },
  { id: 74, title: "DJ Got Us Fallin In Love", artist: "Usher" },
  { id: 75, title: "Word Crimes", artist: "Weird Al Yankovic" },
];
