import type { PlaylistItem } from "./eventConfig";

export const PLAYLIST_1: PlaylistItem[] = [
  { id: 1, title: "Kryptonite", artist: "3 Doors Down" },
  { id: 2, title: "So Caught Up In You", artist: ".38 Special" },
  { id: 3, title: "Take On Me", artist: "a-ha" },
  { id: 4, title: "Take A Chance On Me", artist: "Abba" },
  { id: 5, title: "You Shook Me All Night", artist: "AC/DC" },
  { id: 6, title: "Beautiful Life", artist: "Ace of Base" },
  { id: 7, title: "Rumor Has It", artist: "Adele" },
  { id: 8, title: "Because I Got High", artist: "Afroman" },
  { id: 9, title: "Dixieland Delight", artist: "Alabama" },
  { id: 10, title: "Faded", artist: "Alan Walker" },
  { id: 11, title: "Fallin'", artist: "Alicia Keys" },
  { id: 12, title: "Forever Young", artist: "Alphaville" },
  { id: 13, title: "Best Day Of My Life", artist: "American Authors" },
  { id: 14, title: "Side To Side", artist: "Ariana Grande" },
  { id: 15, title: "Sail", artist: "AWOLNATION" },
  { id: 16, title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys" },
  { id: 17, title: "Come And Get It", artist: "Badfinger" },
  { id: 18, title: "Cruel Summer", artist: "Bananarama" },
  { id: 19, title: "It's All Been Done", artist: "Barenaked Ladies" },
  { id: 20, title: "If I Were A Boy", artist: "Beyoncé" },
  { id: 21, title: "Save A Horse", artist: "Big and Rich" },
  { id: 22, title: "Rebel Yell", artist: "Billy Idol" },
  { id: 23, title: "Piano Man", artist: "Billy Joel" },
  { id: 24, title: "Get Outta My Dreams", artist: "Billy Ocean" },
  { id: 25, title: "No Diggity", artist: "Blackstreet" },
  { id: 26, title: "Blaze of Glory", artist: "Bon Jovi" },
  { id: 27, title: "Something To Talk About", artist: "Bonnie Raitt" },
  { id: 28, title: "1985", artist: "Bowling For Soup" },
  { id: 29, title: "Motownphilly", artist: "Boyz II Men" },
  { id: 30, title: "Lucky", artist: "Britney Spears" },
  { id: 31, title: "My Maria", artist: "Brooks & Dunn" },
  { id: 32, title: "Born In The U.S.A.", artist: "Bruce Springsteen" },
  { id: 33, title: "You're So Vain", artist: "Carly Simon" },
  { id: 34, title: "Cowboy Casanova", artist: "Carrie Underwood" },
  { id: 35, title: "My Heart Will Go On", artist: "Celine Dion" },
  { id: 36, title: "Bootylicious", artist: "Destiny's Child" },
  { id: 37, title: "Meet In The Middle", artist: "Diamond Rio" },
  { id: 38, title: "I Say A Little Prayer", artist: "Dionne Warwick" },
  { id: 39, title: "Goodbye Earl", artist: "Dixie Chicks" },
  { id: 40, title: "Sad Songs", artist: "Elton John" },
  { id: 41, title: "Hungry Eyes", artist: "Eric Carmen" },
  { id: 42, title: "The Final Countdown", artist: "Europe" },
  { id: 43, title: "Sugar, We're Goin' Down", artist: "Fall Out Boy" },
  { id: 44, title: "Superman", artist: "Five For Fighting" },
  { id: 45, title: "The Chain", artist: "Fleetwood Mac" },
  { id: 46, title: "The Pretender", artist: "Foo Fighters" },
  { id: 47, title: "I Want To Know What Love Is", artist: "Foreigner" },
  { id: 48, title: "Ain't Going Down 'Til The Sun Comes Up", artist: "Garth Brooks" },
  { id: 49, title: "I Cross My Heart", artist: "George Strait" },
  { id: 50, title: "I Will Survive", artist: "Gloria Gaynor" },
  { id: 51, title: "Crazy", artist: "Gnarls Barkley" },
  { id: 52, title: "Crimson And Clover", artist: "Joan Jett" },
  { id: 53, title: "Ring Of Fire", artist: "Johnny Cash" },
  { id: 54, title: "Last Friday Night (T.G.I.F.)", artist: "Katy Perry" },
  { id: 55, title: "Tik Tok", artist: "Ke$ha" },
  { id: 56, title: "Since U Been Gone", artist: "Kelly Clarkson" },
  { id: 57, title: "Leap Of Faith", artist: "Lionel Cartwright" },
  { id: 58, title: "Rude", artist: "MAGIC!" },
  { id: 59, title: "I Need To Know", artist: "Marc Anthony" },
  { id: 60, title: "Haven't Met You Yet", artist: "Michael Bublé" },
  { id: 61, title: "Everywhere", artist: "Michelle Branch" },
  { id: 62, title: "Party In The U.S.A.", artist: "Miley Cyrus" },
  { id: 63, title: "You'll Never Know", artist: "Mindy McCready" },
  { id: 64, title: "99 Luftballons", artist: "Nena" },
  { id: 65, title: "You Get What You Give", artist: "New Radicals" },
  { id: 66, title: "It's My Life", artist: "No Doubt" },
  { id: 67, title: "Gone, Gone, Gone", artist: "Phillip Phillips" },
  { id: 68, title: "Jessie's Girl", artist: "Rick Springfield" },
  { id: 69, title: "Stranger In My House", artist: "Ronnie Milsap" },
  { id: 70, title: "Kill Bill", artist: "RZA" },
  { id: 71, title: "King Of Anything", artist: "Sara Bareilles" },
  { id: 72, title: "Any Man Of Mine", artist: "Shania Twain" },
  { id: 73, title: "Venus", artist: "Shocking Blue" },
  { id: 74, title: "All For You", artist: "Sister Hazel" },
];

export const PLAYLIST_2: PlaylistItem[] = [
  { id: 1, title: "Castle On The Hill", artist: "Ed Sheeran" },
  { id: 2, title: "Evil Woman", artist: "ELO" },
  { id: 3, title: "Bring Me To Life", artist: "Evanescence" },
  { id: 4, title: "The Way You Love Me", artist: "Faith Hill" },
  { id: 5, title: "Paralyzer", artist: "finger eleven" },
  { id: 6, title: "My House", artist: "Flo Rida" },
  { id: 7, title: "Handlebars", artist: "Flobots" },
  { id: 8, title: "What's Up", artist: "Four Non-Blondes" },
  { id: 9, title: "Relax", artist: "Frankie Goes To Hollywood" },
  { id: 10, title: "Cars", artist: "Gary Numan" },
  { id: 11, title: "Follow You Down", artist: "Gin Blossoms" },
  { id: 12, title: "Somebody That I Used To Know", artist: "Gotye" },
  { id: 13, title: "Redneck Woman", artist: "Gretchen Wilson" },
  { id: 14, title: "Nothing At All", artist: "Heart" },
  { id: 15, title: "So Yesterday", artist: "Hilary Duff" },
  { id: 16, title: "White Rabbit", artist: "Jefferson Airplane" },
  { id: 17, title: "Eastbound and Down", artist: "Jerry Reed" },
  { id: 18, title: "Straight Tequila Night", artist: "John Anderson" },
  { id: 19, title: "Gravity", artist: "John Mayer" },
  { id: 20, title: "Waking Up In Vegas", artist: "Katy Perry" },
  { id: 21, title: "Footloose", artist: "Kenny Loggins" },
  { id: 22, title: "I Wanna Rock N Roll All Night", artist: "KISS" },
  { id: 23, title: "Need You Now", artist: "Lady Antebellum" },
  { id: 24, title: "Killing Me Softly", artist: "Lauryn Hill" },
  { id: 25, title: "American Woman", artist: "Lenny Kravitz" },
  { id: 26, title: "Do You Believe In Magic", artist: "Lovin' Spoonful" },
  { id: 27, title: "Despacito", artist: "Luis Fonsi" },
  { id: 28, title: "3AM", artist: "Matchbox Twenty" },
  { id: 29, title: "Wrecking Ball", artist: "Miley Cyrus" },
  { id: 30, title: "I Melt With You", artist: "Modern English" },
  { id: 31, title: "Sweet Caroline", artist: "Neil Diamond" },
  { id: 32, title: "Calendar Girl", artist: "Neil Sedaka" },
  { id: 33, title: "My Friends Over You", artist: "New Found Glory" },
  { id: 34, title: "Super Bass", artist: "Nicki Minaj" },
  { id: 35, title: "Cheerleader", artist: "OMI" },
  { id: 36, title: "Round and Round", artist: "Ratt" },
  { id: 37, title: "Somebody's Watching Me", artist: "Rockwell" },
  { id: 38, title: "Shoop", artist: "Salt-N-Pepa" },
  { id: 39, title: "Born To Fly", artist: "Sara Evans" },
  { id: 40, title: "Still the One", artist: "Shania Twain" },
  { id: 41, title: "Sunny Came Home", artist: "Shawn Colvin" },
  { id: 42, title: "Soak Up The Sun", artist: "Sheryl Crow" },
  { id: 43, title: "Chandelier", artist: "Sia" },
  { id: 44, title: "We Are Family", artist: "Sister Sledge" },
  { id: 45, title: "Everyday People", artist: "Sly & the Family Stone" },
  { id: 46, title: "All Star", artist: "Smashmouth" },
  { id: 47, title: "Sugar, Sugar", artist: "The Archies" },
  { id: 48, title: "Love Shack", artist: "The B-52's" },
  { id: 49, title: "Revolution", artist: "The Beatles" },
  { id: 50, title: "Close To You", artist: "The Carpenters" },
  { id: 51, title: "Light My Fire", artist: "The Doors" },
  { id: 52, title: "How to Save a Life", artist: "The Fray" },
  { id: 53, title: "Long Cool Woman in a Black Dress", artist: "The Hollies" },
  { id: 54, title: "Mr. Brightside", artist: "The Killers" },
  { id: 55, title: "Creeque Alley", artist: "The Mamas & The Papas" },
  { id: 56, title: "Beep", artist: "The Pussycat Dolls" },
  { id: 57, title: "I'll Be There For You", artist: "The Rembrandts" },
  { id: 58, title: "My Girl", artist: "The Temptations" },
  { id: 59, title: "The Lion Sleeps Tonight", artist: "The Tokens" },
  { id: 60, title: "Never Let You Go", artist: "Third Eye Blind" },
  { id: 61, title: "I Like It I Love It", artist: "Tim McGraw" },
  { id: 62, title: "How Do You Like Me Now", artist: "Toby Keith" },
  { id: 63, title: "Crimson & Clover", artist: "Tommy James" },
  { id: 64, title: "Rosanna", artist: "Toto" },
  { id: 65, title: "Trouble", artist: "Travis Tritt" },
  { id: 66, title: "Riptide", artist: "Vance Joy" },
  { id: 67, title: "A Thousand Miles", artist: "Vanessa Carlton" },
  { id: 68, title: "YMCA", artist: "Village People" },
  { id: 69, title: "Cherry Pie", artist: "Warrant" },
  { id: 70, title: "Beverly Hills", artist: "Weezer" },
  { id: 71, title: "Tacky", artist: "Weird Al Yankovic" },
  { id: 72, title: "I Will Always Love You", artist: "Whitney Houston" },
  { id: 73, title: "I Saw the Light", artist: "Wynonna Judd" },
  { id: 74, title: "The Fox", artist: "Ylvis" },
  { id: 75, title: "Clarity", artist: "Zedd" },
];

export const PLAYLIST_3: PlaylistItem[] = [
  { id: 1, title: "Are You That Somebody", artist: "Aaliyah" },
  { id: 2, title: "The Sign", artist: "Ace of Base" },
  { id: 3, title: "Dude (Looks Like A Lady)", artist: "Aerosmith" },
  { id: 4, title: "All Out of Love", artist: "Air Supply" },
  { id: 5, title: "Song of the South", artist: "Alabama" },
  { id: 6, title: "It's 5 O'Clock Somewhere", artist: "Alan Jackson" },
  { id: 7, title: "Black Velvet", artist: "Alannah Myles" },
  { id: 8, title: "Potential Breakup Song", artist: "Aly & AJ" },
  { id: 9, title: "Time to Say Goodbye", artist: "Andrea Bocelli" },
  { id: 10, title: "Cups", artist: "Anna Kendrick" },
  { id: 11, title: "Do I Wanna Know", artist: "Arctic Monkeys" },
  { id: 12, title: "Complicated", artist: "Avril Lavigne" },
  { id: 13, title: "It's All Been Done", artist: "Barenaked Ladies" },
  { id: 14, title: "Intergalactic", artist: "Beastie Boys" },
  { id: 15, title: "More than a Woman", artist: "Bee Gees" },
  { id: 16, title: "Rock Around the Clock", artist: "Billy Haley & His Comets" },
  { id: 17, title: "You May Be Right", artist: "Billy Joel" },
  { id: 18, title: "Hit 'Em Up Style", artist: "Blu Cantrell" },
  { id: 19, title: "Hooked on a Feeling", artist: "Blue Swede" },
  { id: 20, title: "Runaround", artist: "Blues Traveler" },
  { id: 21, title: "Green Onions", artist: "Booker T. & The M.G.'s" },
  { id: 22, title: "Stronger", artist: "Britney Spears" },
  { id: 23, title: "That'll Be The Day", artist: "Buddy Holly & The Crickets" },
  { id: 24, title: "Ain't No Rest for the Wicked", artist: "Cage the Elephant" },
  { id: 25, title: "Havana", artist: "Camila Cabello" },
  { id: 26, title: "We Don't Talk Anymore", artist: "Charlie Puth" },
  { id: 27, title: "Believe", artist: "Cher" },
  { id: 28, title: "Hymn for the Weekend", artist: "Coldplay" },
  { id: 29, title: "Mr. Jones", artist: "Counting Crows" },
  { id: 30, title: "Higher", artist: "Creed" },
  { id: 31, title: "Bad Day", artist: "Daniel Powter" },
  { id: 32, title: "That's Amore", artist: "Dean Martin" },
  { id: 33, title: "Groove Is in the Heart", artist: "Deee-Lite" },
  { id: 34, title: "Say My Name", artist: "Destiny's Child" },
  { id: 35, title: "Come on Eileen", artist: "Dexy's Midnight Runners" },
  { id: 36, title: "I'm Shipping Up to Boston", artist: "Dropkick Murphy's" },
  { id: 37, title: "Mercy", artist: "Duffy" },
  { id: 38, title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { id: 39, title: "Tiny Dancer", artist: "Elton John" },
  { id: 40, title: "Centuries", artist: "Fall Out Boy" },
  { id: 41, title: "HandClap", artist: "Fitz and The Tantrums" },
  { id: 42, title: "I Ran", artist: "Flock of Seagulls" },
  { id: 43, title: "Round Here", artist: "Florida Georgia Line" },
  { id: 44, title: "Learn To Fly", artist: "Foo Fighters" },
  { id: 45, title: "Careless Whisper", artist: "George Michael" },
  { id: 46, title: "Rhinestone Cowboy", artist: "Glen Campbell" },
  { id: 47, title: "Lifestyles of the Rich and Famous", artist: "Good Charlotte" },
  { id: 48, title: "Basket Case", artist: "Green Day" },
  { id: 49, title: "The Reason", artist: "Hoobastank" },
  { id: 50, title: "Say You Won't Let Go", artist: "James Arthur" },
  { id: 51, title: "Living In America", artist: "James Brown" },
  { id: 52, title: "Domino", artist: "Jessie J" },
  { id: 53, title: "Third Rock From The Sun", artist: "Joe Diffie" },
  { id: 54, title: "Jack & Diane", artist: "John Mellencamp" },
  { id: 55, title: "Firework", artist: "Katy Perry" },
  { id: 56, title: "She Think's My Tractor's Sexy", artist: "Kenny Chesney" },
  { id: 57, title: "Shallow", artist: "Lady Gaga" },
  { id: 58, title: "Party Rock Anthem", artist: "LMFAO" },
  { id: 59, title: "What A Wonderful World", artist: "Louis Armstrong" },
  { id: 60, title: "Material Girl", artist: "Madonna" },
  { id: 61, title: "Safe in the Arms of Love", artist: "Martina McBride" },
  { id: 62, title: "Forever and Ever, Amen", artist: "Randy Travis" },
  { id: 63, title: "Smooth", artist: "Santana" },
  { id: 64, title: "Kiss Me", artist: "Sixpence None the Richer" },
  { id: 65, title: "Wannabe", artist: "Spice Girls" },
  { id: 66, title: "We Are Never Getting Back Together", artist: "Taylor Swift" },
  { id: 67, title: "Who Let the Dogs Out", artist: "The Baja Men" },
  { id: 68, title: "On Broadway", artist: "The Drifters" },
  { id: 69, title: "Working My Way Back to You", artist: "The Four Seasons" },
  { id: 70, title: "Juicy", artist: "The Notorious B.I.G." },
  { id: 71, title: "Leader of the Pack", artist: "The Shangri-Las" },
  { id: 72, title: "Semi-Charmed Life", artist: "Third Eye Blind" },
  { id: 73, title: "Chrome", artist: "Trace Adkins" },
  { id: 74, title: "Everybody Have Fun Tonight", artist: "Wang Chung" },
  { id: 75, title: "Owner of a Lonely Heart", artist: "Yes" },
];

export const PLAYLIST_4: PlaylistItem[] = [
  { id: 1, title: "Let Me Go", artist: "3 Doors Down" },
  { id: 2, title: "Sweet Emotion", artist: "Aerosmith" },
  { id: 3, title: "Spooky", artist: "Atlanta Rhythm Section" },
  { id: 4, title: "Pompeii", artist: "Bastille" },
  { id: 5, title: "Mony Mony", artist: "Billy Idol" },
  { id: 6, title: "Achy Breaky Heart", artist: "Billy Ray Cyrus" },
  { id: 7, title: "Ol' Red", artist: "Blake Shelton" },
  { id: 8, title: "You Give Love a Bad Name", artist: "Bon Jovi" },
  { id: 9, title: "Holding Out For a Hero", artist: "Bonnie Tyler" },
  { id: 10, title: "Mud On The Tires", artist: "Brad Paisley" },
  { id: 11, title: "Glory Days", artist: "Bruce Springsteen" },
  { id: 12, title: "The Distance", artist: "Cake" },
  { id: 13, title: "Summer", artist: "Calvin Harris" },
  { id: 14, title: "Word Up", artist: "Cameo" },
  { id: 15, title: "Good Time", artist: "Carly Rae Jepsen" },
  { id: 16, title: "Yes!", artist: "Chad Brock" },
  { id: 17, title: "Lollipop", artist: "Chordettes" },
  { id: 18, title: "Bubbly", artist: "Colbie Caillet" },
  { id: 19, title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper" },
  { id: 20, title: "Gasolina", artist: "Daddy Yankee" },
  { id: 21, title: "Alright", artist: "Darius Rucker" },
  { id: 22, title: "Heavy Metal", artist: "Don Felder" },
  { id: 23, title: "American Pie", artist: "Don McLean" },
  { id: 24, title: "New Rules", artist: "Dua Lipa" },
  { id: 25, title: "Son of a Preacher Man", artist: "Dusty Springfield" },
  { id: 26, title: "Sing", artist: "Ed Sheeran" },
  { id: 27, title: "Mr. Blue Sky", artist: "ELO" },
  { id: 28, title: "Return to Sender", artist: "Elvis Presley" },
  { id: 29, title: "Hero", artist: "Enrique Iglesias" },
  { id: 30, title: "This Kiss", artist: "Faith Hill" },
  { id: 31, title: "Drunken Lullabies", artist: "Flogging Molly" },
  { id: 32, title: "Blame It on Me", artist: "George Ezra" },
  { id: 33, title: "American Idiot", artist: "Green Day" },
  { id: 34, title: "Welcome to the Jungle", artist: "Guns N' Roses" },
  { id: 35, title: "These Dreams", artist: "Heart" },
  { id: 36, title: "Escapade", artist: "Janet Jackson" },
  { id: 37, title: "I'm Yours", artist: "Jason Mraz" },
  { id: 38, title: "On the Floor", artist: "Jennifer Lopez" },
  { id: 39, title: "Your Raise Me Up", artist: "Josh Groban" },
  { id: 40, title: "Roar", artist: "Katy Perry" },
  { id: 41, title: "All Summer", artist: "Kid Rock" },
  { id: 42, title: "Hideaway", artist: "Kiesza" },
  { id: 43, title: "Telephone", artist: "Lady Gaga" },
  { id: 44, title: "Young and Beautiful", artist: "Lana Del Rey" },
  { id: 45, title: "On the Road", artist: "Lee Roy Parnell" },
  { id: 46, title: "Bleeding Love", artist: "Leona Lewis" },
  { id: 47, title: "Wings", artist: "Little Mix" },
  { id: 48, title: "Always Be My Baby", artist: "Mariah Carey" },
  { id: 49, title: "Two Out of Three Ain't Bad", artist: "Meat Loaf" },
  { id: 50, title: "All About That Bass", artist: "Meghan Trainor" },
  { id: 51, title: "Wonder", artist: "Natalie Merchant" },
  { id: 52, title: "Everybody Talks", artist: "Neon Trees" },
  { id: 53, title: "Wouldn't It Be Good", artist: "Nik Kershaw" },
  { id: 54, title: "Tearin' Up My Heart", artist: "NSYNC" },
  { id: 55, title: "Carlene", artist: "Phil Vassar" },
  { id: 56, title: "Home", artist: "Phillip Phillips" },
  { id: 57, title: "Bohemian Rhapsody", artist: "Queen" },
  { id: 58, title: "Black Betty", artist: "Ram Jam" },
  { id: 59, title: "Cotton Eye Joe", artist: "Rednex" },
  { id: 60, title: "Super Freak", artist: "Rick James" },
  { id: 61, title: "Tonight's the Night", artist: "Rod Stewart" },
  { id: 62, title: "Dirty Little Secret", artist: "The All-American Rejects" },
  { id: 63, title: "Boom Boom Pow", artist: "The Black Eyed Peas" },
  { id: 64, title: "Linger", artist: "The Cranberries" },
  { id: 65, title: "Dumas Walker", artist: "The Kentucky Headhunters" },
  { id: 66, title: "Hypnotize", artist: "The Notorious B.I.G." },
  { id: 67, title: "Be My Baby", artist: "The Ronettes" },
  { id: 68, title: "Bittersweet Symphony", artist: "The Verve" },
  { id: 69, title: "It's Your Love", artist: "Tim McGraw" },
  { id: 70, title: "Free Fallin'", artist: "Tom Petty" },
  { id: 71, title: "Africa", artist: "Toto" },
  { id: 72, title: "Hey, Soul Sister", artist: "Train" },
  { id: 73, title: "Save the Best For Last", artist: "Vanessa Williams" },
  { id: 74, title: "Shut Up and Dance", artist: "Walk the Moon" },
  { id: 75, title: "Buddy Holly", artist: "Weezer" },
];

export const PLAYLIST_5: PlaylistItem[] = [
  { id: 1, title: "Summer of '69", artist: "Bryan Adams" },
  { id: 2, title: "Runaway", artist: "Del Shannon" },
  { id: 3, title: "Shape of You", artist: "Ed Sheeran" },
  { id: 4, title: "Lights", artist: "Ellie Goulding" },
  { id: 5, title: "I Guess That's Why They Call It the Blues", artist: "Elton John" },
  { id: 6, title: "I Shot the Sheriff", artist: "Eric Clapton" },
  { id: 7, title: "Uma Thurman", artist: "Fall Out Boy" },
  { id: 8, title: "Like A G6", artist: "Far East Movement" },
  { id: 9, title: "Big Girls Don't Cry", artist: "Fergie" },
  { id: 10, title: "Work From Home", artist: "Fifth Harmony" },
  { id: 11, title: "Criminal", artist: "Fiona Apple" },
  { id: 12, title: "Stacy's Mom", artist: "Fountains of Wayne" },
  { id: 13, title: "Budapest", artist: "George Ezra" },
  { id: 14, title: "King of Wishful Thinking", artist: "Go West" },
  { id: 15, title: "Feel Good Inc.", artist: "Gorillaz" },
  { id: 16, title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { id: 17, title: "Barracuda", artist: "Heart" },
  { id: 18, title: "Lips of an Angel", artist: "Hinder" },
  { id: 19, title: "Somebody's Baby", artist: "Jackson Browne" },
  { id: 20, title: "Bang Bang", artist: "Jessie J" },
  { id: 21, title: "Are You Gonna Be My Girl", artist: "Jet" },
  { id: 22, title: "Burn", artist: "Jo Dee Messina" },
  { id: 23, title: "Love Me Again", artist: "John Newman" },
  { id: 24, title: "Queen of Hearts", artist: "Juice Newton" },
  { id: 25, title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
  { id: 26, title: "Die Young", artist: "Ke$ha" },
  { id: 27, title: "Stronger", artist: "Kelly Clarkson" },
  { id: 28, title: "Bette Davis Eyes", artist: "Kim Carnes" },
  { id: 29, title: "Macarena", artist: "Los del Rio" },
  { id: 30, title: "Mambo No. 5", artist: "Lou Bega" },
  { id: 31, title: "I Don't Want This Night to End", artist: "Luke Bryan" },
  { id: 32, title: "Papa Don't Preach", artist: "Madonna" },
  { id: 33, title: "Sugar", artist: "Maroon 5" },
  { id: 34, title: "Shake It", artist: "Metro Station" },
  { id: 35, title: "Bad", artist: "Michael Jackson" },
  { id: 36, title: "Unwritten", artist: "Natasha Bedingfield" },
  { id: 37, title: "I Need Never Get Old", artist: "Nathaniel Rateliff" },
  { id: 38, title: "The Shake", artist: "Neal McCoy" },
  { id: 39, title: "Am I Wrong", artist: "Nico & Vinz" },
  { id: 40, title: "How Bizarre", artist: "OMC" },
  { id: 41, title: "Silly Love Songs", artist: "Paul McCartney" },
  { id: 42, title: "Gangnam Style", artist: "PSY" },
  { id: 43, title: "You're My Best Friend", artist: "Queen" },
  { id: 44, title: "Shiny Happy People", artist: "R.E.M." },
  { id: 45, title: "Life is a Highway", artist: "Rascall Flatts" },
  { id: 46, title: "Fancy", artist: "Reba McEntire" },
  { id: 47, title: "This is What Your Came For", artist: "Rihanna" },
  { id: 48, title: "Blurred Lines", artist: "Robin Thicke" },
  { id: 49, title: "House Party", artist: "Sam Hunt" },
  { id: 50, title: "Affirmation", artist: "Savage Garden" },
  { id: 51, title: "Up!", artist: "Shania Twain" },
  { id: 52, title: "Stitches", artist: "Shawn Mendes" },
  { id: 53, title: "Johnny Angel", artist: "Shelley Fabares" },
  { id: 54, title: "Geronimo", artist: "Sheppard" },
  { id: 55, title: "I'm a Believer", artist: "Smashmouth" },
  { id: 56, title: "Tears of a Clown", artist: "Smokey Robinson" },
  { id: 57, title: "Chasing Cars", artist: "Snow Patrol" },
  { id: 58, title: "I Got You Babe", artist: "Sonny and Cher" },
  { id: 59, title: "We Built This City", artist: "Starship" },
  { id: 60, title: "King Tut", artist: "Steve Martin" },
  { id: 61, title: "Back in the High Life Again", artist: "Steve Winwood" },
  { id: 62, title: "The Logical Song", artist: "Supertramp" },
  { id: 63, title: "She's So High", artist: "Tal Bachman" },
  { id: 64, title: "You Belong with Me", artist: "Taylor Swift" },
  { id: 65, title: "Everybody Wants to Rule the World", artist: "Tears for Fears" },
  { id: 66, title: "Sweet Home Chicago", artist: "The Blues Brothers" },
  { id: 67, title: "Your Love", artist: "The Outfield" },
  { id: 68, title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
  { id: 69, title: "Under My Thumb", artist: "The Rolling Stones" },
  { id: 70, title: "Can't Feel My Face", artist: "The Weeknd" },
  { id: 71, title: "Beer for My Horses", artist: "Toby Keith" },
  { id: 72, title: "Ten Rounds with Jose Cuervo", artist: "Tracy Byrd" },
  { id: 73, title: "She's in Love With the Boy", artist: "Trisha Yearwood" },
  { id: 74, title: "In The Navy", artist: "Village People" },
  { id: 75, title: "Renegades", artist: "X Ambassadors" },
];
export const PLAYLIST_6 = [
  { id: 1, title: "Waterloo", artist: "ABBA" },
  { id: 2, title: "Janie's Got A Gun", artist: "Aerosmith" },
  { id: 3, title: "Girlfriend", artist: "Avril Lavigne" },
  { id: 4, title: "Suga Suga", artist: "Baby Bash" },
  { id: 5, title: "Shape Of My Heart", artist: "Backstreet Boys" },
  { id: 6, title: "One Week", artist: "Barenaked Ladies" },
  { id: 7, title: "Kokomo", artist: "Beach Boys" },
  { id: 8, title: "No Sleep Till Brooklyn", artist: "Beastie Boys" },
  { id: 9, title: "Meant to Be", artist: "Bebe Rexha" },
  { id: 10, title: "Poison", artist: "Bell Biv DeVoe" },
  { id: 11, title: "We Didn't Start the Fire", artist: "Billy Joel" },
  { id: 12, title: "Every Once In a While", artist: "BlackHawk" },
  { id: 13, title: "Honey Bee", artist: "Blake Shelton" },
  { id: 14, title: "I Miss You", artist: "Blink-182" },
  { id: 15, title: "The Tide Is High", artist: "Blondie" },
  { id: 16, title: "Two is Better Than One", artist: "Boys Like Girls" },
  { id: 17, title: "Hurricane", artist: "Bridgit Mendler" },
  { id: 18, title: "You Drive Me Crazy", artist: "Britney Spears" },
  { id: 19, title: "Red Dirt Road", artist: "Brooks & Dunn" },
  { id: 20, title: "Dancing In the Dark", artist: "Bruce Springsteen" },
  { id: 21, title: "Grenade", artist: "Bruno Mars" },
  { id: 22, title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory" },
  { id: 23, title: "See You Again", artist: "Charlie Puth" },
  { id: 24, title: "A Thousand Years", artist: "Christina Perri" },
  { id: 25, title: "Let's Twist Again", artist: "Chubby Checker" },
  { id: 26, title: "Tubthumping", artist: "Chumbawamba" },
  { id: 27, title: "Rockabye", artist: "Clean Bandit" },
  { id: 28, title: "Killin' Time", artist: "Clint Black" },
  { id: 29, title: "Adventure Of A Lifetime", artist: "Coldplay" },
  { id: 30, title: "Gangsta's Paradise", artist: "Coolio" },
  { id: 31, title: "Mmm Mmm Mmm Mmm", artist: "Crash Test Dummies" },
  { id: 32, title: "Time After Time", artist: "Cyndi Lauper" },
  { id: 33, title: "That's The Way It Is", artist: "Céline Dion" },
  { id: 34, title: "Digital Love", artist: "Daft Punk" },
  { id: 35, title: "Welcome To Jamrock", artist: "Damian Marley" },
  { id: 36, title: "Wagon Wheel", artist: "Darius Rucker" },
  { id: 37, title: "Home", artist: "Daughtry" },
  { id: 38, title: "Crash Into Me", artist: "Dave Matthews Band" },
  { id: 39, title: "Just a Gigolo", artist: "David Lee Roth" },
  { id: 40, title: "Breakfast At Tiffany's", artist: "Deep Blue Something" },
  { id: 41, title: "We Are Young", artist: "Fun." },
  { id: 42, title: "Stupid Girl", artist: "Garbage" },
  { id: 43, title: "Friends In Low Places", artist: "Garth Brooks" },
  { id: 44, title: "Midnight Train to Georgia", artist: "Gladys Knight and the Pips" },
  { id: 45, title: "You Belong To The City", artist: "Glenn Frey" },
  { id: 46, title: "Slide", artist: "Goo Goo Dolls" },
  { id: 47, title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { id: 48, title: "I Feel Good", artist: "James Brown" },
  { id: 49, title: "One Of Us", artist: "Joan Osborne" },
  { id: 50, title: "All of Me", artist: "John Legend" },
  { id: 51, title: "Say", artist: "John Mayer" },
  { id: 52, title: "Constant Craving", artist: "k.d. lang" },
  { id: 53, title: "Bad Romance", artist: "Lady Gaga" },
  { id: 54, title: "Amazed", artist: "Lonestar" },
  { id: 55, title: "Royals", artist: "Lorde" },
  { id: 56, title: "Home", artist: "Michael Bublé" },
  { id: 57, title: "The Climb", artist: "Miley Cyrus" },
  { id: 58, title: "Photograph", artist: "Nickelback" },
  { id: 59, title: "I Write Sins Not Tragedies", artist: "Panic! At The Disco" },
  { id: 60, title: "Hurt Me Bad", artist: "Patty Loveless" },
  { id: 61, title: "Feel It Still", artist: "Portugal. The Man" },
  { id: 62, title: "Love Song", artist: "Sara Bareilles" },
  { id: 63, title: "That Don't Impress Me Much", artist: "Shania Twain" },
  { id: 64, title: "Walkin' On The Sun", artist: "Smash Mouth" },
  { id: 65, title: "Rock This Town", artist: "Stray Cats" },
  { id: 66, title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
  { id: 67, title: "Video Killed the Radio Star", artist: "The Buggles" },
  { id: 68, title: "Don't Let Me Down", artist: "The Chainsmokers" },
  { id: 69, title: "Build Me Up Buttercup", artist: "The Foundations" },
  { id: 70, title: "Louie Louie", artist: "The Kingsmen" },
  { id: 71, title: "Under the Sea", artist: "The Little Mermaid" },
  { id: 72, title: "Satisfaction", artist: "The Rolling Stones" },
  { id: 73, title: "Werewolves Of London", artist: "Warren Zevon" },
  { id: 74, title: "Play That Funky Music", artist: "Wild Cherry" },
  { id: 75, title: "If I Can't Have You", artist: "Yvonne Elliman" },
];

export const PLAYLIST_7 = [
  { id: 1, title: "All That She Wants", artist: "Ace of Base" },
  { id: 2, title: "If I Had You", artist: "Adam Lambert" },
  { id: 3, title: "Rolling in the Deep", artist: "Adele" },
  { id: 4, title: "Crazy", artist: "Aerosmith" },
  { id: 5, title: "Summertime Blues", artist: "Alan Jackson" },
  { id: 6, title: "When You Say Nothing At All", artist: "Alison Krauss" },
  { id: 7, title: "Obsession", artist: "Animotion" },
  { id: 8, title: "I Want It That Way", artist: "Backstreet Boys" },
  { id: 9, title: "If I Had $1,000,000", artist: "Barenaked Ladies" },
  { id: 10, title: "Where's Your Head At", artist: "Basement Jaxx" },
  { id: 11, title: "Fire N Gold", artist: "Bea Miller" },
  { id: 12, title: "Heaven Is A Place On Earth", artist: "Belinda Carlisle" },
  { id: 13, title: "Uptown Girls", artist: "Billy Joel" },
  { id: 14, title: "Bring It All to Me", artist: "Blaque" },
  { id: 15, title: "Rapture", artist: "Blondie" },
  { id: 16, title: "Don't Worry Be Happy", artist: "Bobby McFerrin" },
  { id: 17, title: "Who Says You Can't Go Home", artist: "Bon Jovi" },
  { id: 18, title: "Bottoms Up", artist: "Brantley Gilbert" },
  { id: 19, title: "Oops!...I Did It Again", artist: "Britney Spears" },
  { id: 20, title: "Just The Way You Are", artist: "Bruno Mars" },
  { id: 21, title: "Two Black Cadillacs", artist: "Carrie Underwood" },
  { id: 22, title: "Marvin Gaye", artist: "Charlie Puth" },
  { id: 23, title: "If I Could Turn Back Time", artist: "Cher" },
  { id: 24, title: "The One And Only", artist: "Chesney Hawkes" },
  { id: 25, title: "Dirty", artist: "Christina Aguilera" },
  { id: 26, title: "Little Rock", artist: "Collin Raye" },
  { id: 27, title: "Butterfly", artist: "Crazy Town" },
  { id: 28, title: "Boogie Wonderland", artist: "Earth, Wind & Fire" },
  { id: 29, title: "Burn", artist: "Ellie Goulding" },
  { id: 30, title: "Don't Bring Me Down", artist: "ELO" },
  { id: 31, title: "Pinball Wizard", artist: "Elton John" },
  { id: 32, title: "Jailhouse Rock", artist: "Elvis Presley" },
  { id: 33, title: "The Real Slim Shady", artist: "Eminem" },
  { id: 34, title: "Cruise", artist: "Florida Georgia Line" },
  { id: 35, title: "I Kissed A Girl", artist: "Katy Perry" },
  { id: 36, title: "Celebration", artist: "Kool and the Gang" },
  { id: 37, title: "Black Or White", artist: "Michael Jackson" },
  { id: 38, title: "Pocketful of Sunshine", artist: "Natasha Bedingfield" },
  { id: 39, title: "Sister Christian", artist: "Night Ranger" },
  { id: 40, title: "Don't Know Why", artist: "Norah Jones" },
  { id: 41, title: "Little Talks", artist: "Of Monsters And Men" },
  { id: 42, title: "What Makes You Beautiful", artist: "One Direction" },
  { id: 43, title: "Major Tom", artist: "Peter Schilling" },
  { id: 44, title: "I Wanna Be Your Lover", artist: "Prince" },
  { id: 45, title: "Fight Song", artist: "Rachel Platten" },
  { id: 46, title: "I'm Too Sexy", artist: "Right Said Fred" },
  { id: 47, title: "Push It", artist: "Salt-N-Pepa" },
  { id: 48, title: "Wooly Bully", artist: "Sam the Sham and the Pharaohs" },
  { id: 49, title: "Kiss From a Rose", artist: "Seal" },
  { id: 50, title: "Hips Don't Lie", artist: "Shakira" },
  { id: 51, title: "There She Goes", artist: "Sixpence None the Richer" },
  { id: 52, title: "Tainted Love", artist: "Soft Cell" },
  { id: 53, title: "Oh Sherrie", artist: "Steve Perry" },
  { id: 54, title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder" },
  { id: 55, title: "Eye Of The Tiger", artist: "Survivor" },
  { id: 56, title: "Gives You Hell", artist: "The All-American Rejects" },
  { id: 57, title: "Walk Like an Egyptian", artist: "The Bangles" },
  { id: 58, title: "Hard To Handle", artist: "The Black Crowes" },
  { id: 59, title: "My Humps", artist: "The Black Eyed Peas" },
  { id: 60, title: "Wherever You Will Go", artist: "The Calling" },
  { id: 61, title: "Dreams", artist: "The Cranberries" },
  { id: 62, title: "December, 1963 (Oh, What a Night)", artist: "The Four Seasons" },
  { id: 63, title: "Pretty Fly (For A White Guy)", artist: "The Offspring" },
  { id: 64, title: "Who Are You", artist: "The Who" },
  { id: 65, title: "Leave The Pieces", artist: "The Wreckers" },
  { id: 66, title: "She's Not There", artist: "The Zombies" },
  { id: 67, title: "No Scrubs", artist: "TLC" },
  { id: 68, title: "All I Want", artist: "Toad The Wet Sprocket" },
  { id: 69, title: "Made In America", artist: "Toby Keith" },
  { id: 70, title: "Into the Great Wide Open", artist: "Tom Petty" },
  { id: 71, title: "Mony Mony", artist: "Tommy James" },
  { id: 72, title: "Knock Three Times", artist: "Tony Orlando & Dawn" },
  { id: 73, title: "Fast Car", artist: "Tracy Chapman" },
  { id: 74, title: "Brown Eyed Girl", artist: "Van Morrison" },
  { id: 75, title: "Ice Ice Baby", artist: "Vanilla Ice" },
];

export const PLAYLIST_8 = [
  { id: 1, title: "S.O.S.", artist: "ABBA" },
  { id: 2, title: "Thunderstruck", artist: "AC/DC" },
  { id: 3, title: "I Don't Want to Miss a Thing", artist: "Aerosmith" },
  { id: 4, title: "Honey I'm Good", artist: "Andy Grammer" },
  { id: 5, title: "Walking on Broken Glass", artist: "Annie Lennox" },
  { id: 6, title: "Barbie Girl", artist: "Aqua" },
  { id: 7, title: "thank u, next", artist: "Ariana Grande" },
  { id: 8, title: "Larger Than Life", artist: "Backstreet Boys" },
  { id: 9, title: "Mad About You", artist: "Belinda Carlisle" },
  { id: 10, title: "Dancing With Myself", artist: "Billy Idol" },
  { id: 11, title: "I Want Candy", artist: "Bow Wow Wow" },
  { id: 12, title: "Punk Rock 101", artist: "Bowling For Soup" },
  { id: 13, title: "I'll Make Love To You", artist: "Boyz II Men" },
  { id: 14, title: "I'm Gonna Miss Her", artist: "Brad Paisley" },
  { id: 15, title: "Toxic", artist: "Britney Spears" },
  { id: 16, title: "Boot Scootin' Boogie", artist: "Brooks and Dunn" },
  { id: 17, title: "Ms. New Booty", artist: "Bubba Sparxxx" },
  { id: 18, title: "Tuesday", artist: "Burak Yeter" },
  { id: 19, title: "Bad Bunny", artist: "Cardi B" },
  { id: 20, title: "Kung Fu Fighting", artist: "Carl Douglas" },
  { id: 21, title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { id: 22, title: "I'm Every Woman", artist: "Chaka Khan" },
  { id: 23, title: "One Call Away", artist: "Charlie Puth" },
  { id: 24, title: "Genie in a Bottle", artist: "Christina Aguilera" },
  { id: 25, title: "A Sky Full Of Stars", artist: "Coldplay" },
  { id: 26, title: "Going Up Around the Bend", artist: "Creedence Clearwater Revival" },
  { id: 27, title: "Titanium", artist: "David Guetta" },
  { id: 28, title: "Strawberry Wine", artist: "Deana Carter" },
  { id: 29, title: "Give Your Heart a Break", artist: "Demi Lovato" },
  { id: 30, title: "Runaround Sue", artist: "Dion & The Belmonts" },
  { id: 31, title: "9 To 5", artist: "Dolly Parton" },
  { id: 32, title: "Suspicious Minds", artist: "Dwight Yoakam" },
  { id: 33, title: "Save Tonight", artist: "Eagle-Eye Cherry" },
  { id: 34, title: "I Love a Rainy Night", artist: "Eddie Rabbitt" },
  { id: 35, title: "Blue", artist: "Eiffel 65" },
  { id: 36, title: "Ex's & Oh's", artist: "Elle King" },
  { id: 37, title: "Love Me Like You Do", artist: "Ellie Goulding" },
  { id: 38, title: "Benny and the Jets", artist: "Elton John" },
  { id: 39, title: "Sweet Dreams", artist: "Eurythmics" },
  { id: 40, title: "I Will Buy You A New Life", artist: "Everclear" },
  { id: 41, title: "The Way", artist: "Fastball" },
  { id: 42, title: "100 Years", artist: "Five for Fighting" },
  { id: 43, title: "Some Nights", artist: "Fun." },
  { id: 44, title: "I Can't Dance", artist: "Genesis" },
  { id: 45, title: "Check Yes Or No", artist: "George Strait" },
  { id: 46, title: "Iris", artist: "Goo Goo Dolls" },
  { id: 47, title: "Here for The Party", artist: "Gretchen Wilson" },
  { id: 48, title: "What Is Love", artist: "Haddaway" },
  { id: 49, title: "Take Me To Church", artist: "Hozier" },
  { id: 50, title: "Let It Go", artist: "Idina Menzel" },
  { id: 51, title: "Need You Tonight", artist: "INXS" },
  { id: 52, title: "Papi", artist: "Jennifer Lopez" },
  { id: 53, title: "Carry on Wayward Son", artist: "Kansas" },
  { id: 54, title: "Dark Horse", artist: "Katy Perry" },
  { id: 55, title: "Red High Heels", artist: "Kellie Pickler" },
  { id: 56, title: "Breakaway", artist: "Kelly Clarkson" },
  { id: 57, title: "Born This Way", artist: "Lady Gaga" },
  { id: 58, title: "Funky Town", artist: "Lipps Inc." },
  { id: 59, title: "The Mummers' Dance", artist: "Loreena McKennitt" },
  { id: 60, title: "Fly", artist: "Maddie & Tae" },
  { id: 61, title: "The House That Built Me", artist: "Miranda Lambert" },
  { id: 62, title: "Carnival", artist: "Natalie Merchant" },
  { id: 63, title: "Hit Me With Your Best Shot", artist: "Pat Benatar" },
  { id: 64, title: "Blame It On Your Lyin' Cheatin' Heart", artist: "Patty Loveless" },
  { id: 65, title: "Harden My Heart", artist: "Quarterflash" },
  { id: 66, title: "Pretty Woman", artist: "Roy Orbison" },
  { id: 67, title: "Little Good-Byes", artist: "SHeDAISY" },
  { id: 68, title: "Why Can't We Be Friends", artist: "Smash Mouth" },
  { id: 69, title: "Copperhead Road", artist: "Steve Earle" },
  { id: 70, title: "Paperback Writer", artist: "The Beatles" },
  { id: 71, title: "Rawhide", artist: "The Blues Brothers" },
  { id: 72, title: "Holler Back", artist: "The Lost Trailers" },
  { id: 73, title: "The Kids Aren't Alright", artist: "The Offspring" },
  { id: 74, title: "Buttons", artist: "The Pussycat Dolls" },
  { id: 75, title: "Leader of the Pack", artist: "Twisted Sister" },
];

export const PLAYLIST_9 = [
  { id: 1, title: "Dancing Queen", artist: "Abba" },
  { id: 2, title: "I Love the Nightlife", artist: "Alicia Bridges" },
  { id: 3, title: "Wake Me Up", artist: "Avicii" },
  { id: 4, title: "Copacabana", artist: "Barry Manilow" },
  { id: 5, title: "I Got You", artist: "Bebe Rexha" },
  { id: 6, title: "Stayin' Alive", artist: "Bee Gees" },
  { id: 7, title: "Just the Way You Are", artist: "Billy Joel" },
  { id: 8, title: "Wanted Dead Or Alive", artist: "Bon Jovi" },
  { id: 9, title: "That Ain't No Way To Go", artist: "Brooks & Dunn" },
  { id: 10, title: "The Lazy Song", artist: "Bruno Mars" },
  { id: 11, title: "Before He Cheats", artist: "Carrie Underwood" },
  { id: 12, title: "Everytime We Touch", artist: "Cascada" },
  { id: 13, title: "It Was", artist: "Chely Wright" },
  { id: 14, title: "Jar of Hearts", artist: "Christina Perri" },
  { id: 15, title: "Sunglasses At Night", artist: "Corey Hart" },
  { id: 16, title: "True Colors", artist: "Cyndi Lauper" },
  { id: 17, title: "Tequila", artist: "Dan + Shay" },
  { id: 18, title: "I Can Dream About You", artist: "Dan Hartman" },
  { id: 19, title: "You Spin Me Round", artist: "Dead Or Alive" },
  { id: 20, title: "Bills, Bills, Bills", artist: "Destiny's Child" },
  { id: 21, title: "Whip It!", artist: "Devo" },
  { id: 22, title: "The Wanderer", artist: "Dion & The Belmonts" },
  { id: 23, title: "You're Welcome", artist: "Dwayne Johnson" },
  { id: 24, title: "Two Tickets To Paradise", artist: "Eddie Money" },
  { id: 25, title: "All Over The World", artist: "ELO" },
  { id: 26, title: "Bailando", artist: "Enrique Iglesias" },
  { id: 27, title: "Springsteen", artist: "Eric Church" },
  { id: 28, title: "My Immortal", artist: "Evanescence" },
  { id: 29, title: "Breathe", artist: "Faith Hill" },
  { id: 30, title: "My Songs Know What You Did In The Dark", artist: "Fall Out Boy" },
  { id: 31, title: "Dog Days Are Over", artist: "Florence & the Machine" },
  { id: 32, title: "This Is How We Roll", artist: "Florida Georgia Line" },
  { id: 33, title: "Only Happy When It Rains", artist: "Garbage" },
  { id: 34, title: "Got My Mind Set On You", artist: "George Harrison" },
  { id: 35, title: "Summer Nights", artist: "Grease" },
  { id: 36, title: "November Rain", artist: "Guns N' Roses" },
  { id: 37, title: "All I Wanna Do Is Make Love To You", artist: "Heart" },
  { id: 38, title: "Stuck With You", artist: "Huey Lewis And The News" },
  { id: 39, title: "Get Up Offa That Thing", artist: "James Brown" },
  { id: 40, title: "Tequila Makes Her Clothes Fall Off", artist: "Joe Nichols" },
  { id: 41, title: "Issues", artist: "Julia Michaels" },
  { id: 42, title: "Praying", artist: "Ke$ha" },
  { id: 43, title: "Already Gone", artist: "Kelly Clarkson" },
  { id: 44, title: "The Gambler", artist: "Kenny Rogers" },
  { id: 45, title: "Poker Face", artist: "Lady Gaga" },
  { id: 46, title: "Black Magic", artist: "Little Mix" },
  { id: 47, title: "7 Years", artist: "Lukas Graham" },
  { id: 48, title: "Ray Of Light", artist: "Madonna" },
  { id: 49, title: "Love Somebody", artist: "Maroon 5" },
  { id: 50, title: "Please Mr. Postman", artist: "Marvelettes" },
  { id: 51, title: "U Can't Touch This", artist: "MC Hammer" },
  { id: 52, title: "Who Can It Be Now", artist: "Men At Work" },
  { id: 53, title: "It's A Beautiful Day", artist: "Michael Bublé" },
  { id: 54, title: "Rock With You", artist: "Michael Jackson" },
  { id: 55, title: "I'm Gonna Miss You Girl", artist: "Michael Martin Murphey" },
  { id: 56, title: "Lady Marmalade", artist: "Mya" },
  { id: 57, title: "These Boots Are Made for Walkin'", artist: "Nancy Sinatra" },
  { id: 58, title: "America", artist: "Neil Diamond" },
  { id: 59, title: "Rockstar", artist: "Nickelback" },
  { id: 60, title: "Don't Speak", artist: "No Doubt" },
  { id: 61, title: "Wonderwall", artist: "Oasis" },
  { id: 62, title: "Hey Ya!", artist: "OutKast" },
  { id: 63, title: "High Hopes", artist: "Panic! At The Disco" },
  { id: 64, title: "We Belong", artist: "Pat Benatar" },
  { id: 65, title: "Happy", artist: "Pharrell Williams" },
  { id: 66, title: "Livin' La Vida Loca", artist: "Ricky Martin" },
  { id: 67, title: "Forever And For Always", artist: "Shania Twain" },
  { id: 68, title: "Candy Rain", artist: "Soul For Real" },
  { id: 69, title: "Every Morning", artist: "Sugar Ray" },
  { id: 70, title: "Tell It to My Heart", artist: "Taylor Dayne" },
  { id: 71, title: "Shake It Off", artist: "Taylor Swift" },
  { id: 72, title: "Home", artist: "The Magnetic Zeros" },
  { id: 73, title: "Firestarter", artist: "The Prodigy" },
  { id: 74, title: "When I Grow Up", artist: "The Pussycat Dolls" },
  { id: 75, title: "Happy Together", artist: "The Turtles" },
];

export const PLAYLIST_10 = [
  { id: 1, title: "Chattahoochee", artist: "Alan Jackson" },
  { id: 2, title: "Think", artist: "Aretha Franklin" },
  { id: 3, title: "Airplanes", artist: "B.o.B" },
  { id: 4, title: "Who Let The Dogs Out", artist: "Baha Men" },
  { id: 5, title: "Surfin USA", artist: "Beach Boys" },
  { id: 6, title: "(You Gotta) Fight For Your Right (To Party)", artist: "Beastie Boys" },
  { id: 7, title: "White Wedding", artist: "Billy Idol" },
  { id: 8, title: "All The Small Things", artist: "blink-182" },
  { id: 9, title: "Heart of Glass", artist: "Blondie" },
  { id: 10, title: "The Bad Touch", artist: "Bloodhound Gang" },
  { id: 11, title: "Total Eclipse of the Heart", artist: "Bonnie Tyler" },
  { id: 12, title: "Baby One More Time", artist: "Britney Spears" },
  { id: 13, title: "Uptown Funk", artist: "Bruno Mars" },
  { id: 14, title: "Devil Went Down to Georgia", artist: "Charlie Daniels Band" },
  { id: 15, title: "Le Freak", artist: "Chic" },
  { id: 16, title: "On The Verge", artist: "Collin Raye" },
  { id: 17, title: "Woodstock", artist: "Crosby, Stills & Nash" },
  { id: 18, title: "Instant Crush", artist: "Daft Punk" },
  { id: 19, title: "Let's Dance", artist: "David Bowie" },
  { id: 20, title: "Soul Meets Body", artist: "Death Cab for Cutie" },
  { id: 21, title: "Smoke On The Water", artist: "Deep Purple" },
  { id: 22, title: "September", artist: "Earth, Wind & Fire" },
  { id: 23, title: "Perfect", artist: "Ed Sheeran" },
  { id: 24, title: "I'll Be", artist: "Edwin McCain" },
  { id: 25, title: "My Lovin' You're Never Gonna Get It", artist: "En Vogue" },
  { id: 26, title: "Call On Me", artist: "Eric Prydz" },
  { id: 27, title: "Inside Out", artist: "Eve 6" },
  { id: 28, title: "Epic", artist: "Faith No More" },
  { id: 29, title: "Blueberry Hill", artist: "Fats Domino" },
  { id: 30, title: "Go Your Own Way", artist: "Fleetwood Mac" },
  { id: 31, title: "Take Me Out", artist: "Franz Ferdinand" },
  { id: 32, title: "The Anthem", artist: "Good Charlotte" },
  { id: 33, title: "Hollaback Girl", artist: "Gwen Stefani" },
  { id: 34, title: "Maneater", artist: "Hall & Oates" },
  { id: 35, title: "Thunder", artist: "Imagine Dragons" },
  { id: 36, title: "Want to Want Me", artist: "Jason Derulo" },
  { id: 37, title: "Bye Bye", artist: "Jo Dee Messina" },
  { id: 38, title: "Don't Stop Believin'", artist: "Journey" },
  { id: 39, title: "Asking Us To Dance", artist: "Kathy Mattea" },
  { id: 40, title: "Cop Car", artist: "Keith Urban" },
  { id: 41, title: "When You Say Nothing at All", artist: "Keith Whitley" },
  { id: 42, title: "Danger Zone", artist: "Kenny Loggins" },
  { id: 43, title: "Jungle Boogie", artist: "Kool and the Gang" },
  { id: 44, title: "Downtown", artist: "Lady Antebellum" },
  { id: 45, title: "Stay", artist: "Lisa Loeb" },
  { id: 46, title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { id: 47, title: "Dancing in the Streets", artist: "Martha & The Vandellas" },
  { id: 48, title: "Animals", artist: "Martin Garrix" },
  { id: 49, title: "2 Legit 2 Quit", artist: "MC Hammer" },
  { id: 50, title: "I'd Do Anything For Love", artist: "Meat Loaf" },
  { id: 51, title: "Nothing Else Matters", artist: "Metallica" },
  { id: 52, title: "How Am I Supposed To Live Without You", artist: "Michael Bolton" },
  { id: 53, title: "Billie Jean", artist: "Michael Jackson" },
  { id: 54, title: "In the summertime", artist: "Mungo Jerry" },
  { id: 55, title: "Lean On", artist: "MO" },
  { id: 56, title: "Torn", artist: "Natalie Imbruglia" },
  { id: 57, title: "Candy Girl", artist: "New Edition" },
  { id: 58, title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { id: 59, title: "Bye Bye Bye", artist: "NSYNC" },
  { id: 60, title: "Counting Stars", artist: "One Republic" },
  { id: 61, title: "Let Her Go", artist: "Passenger" },
  { id: 62, title: "You Can Call Me Al", artist: "Paul Simon" },
  { id: 63, title: "Hit the road Jack!", artist: "Ray Charles" },
  { id: 64, title: "Waka Waka", artist: "Shakira" },
  { id: 65, title: "Next To You, Next To Me", artist: "Shenandoah" },
  { id: 66, title: "Hey Cinderella", artist: "Suzy Bogguss" },
  { id: 67, title: "Let's Get It Started", artist: "The Black Eyed Peas" },
  { id: 68, title: "Our Lips Are Sealed", artist: "The Go-Gos" },
  { id: 69, title: "I Want You Back", artist: "The Jackson 5" },
  { id: 70, title: "Ho Hey", artist: "The Lumineers" },
  { id: 71, title: "I'm a Believer", artist: "The Monkees" },
  { id: 72, title: "Elvira", artist: "The Oak Ridge Boys" },
  { id: 73, title: "I Hate This Part", artist: "The Pussycat Dolls" },
  { id: 74, title: "End Of The Line", artist: "The Traveling Wilburys" },
  { id: 75, title: "Baba O'Riley", artist: "The Who" },
];

export const PLAYLIST_11 = [
  { id: 1, title: "Smile", artist: "Avril Lavigne" },
  { id: 2, title: "More Than A Feeling", artist: "Boston" },
  { id: 3, title: "Peggy Sue", artist: "Buddy Holly" },
  { id: 4, title: "All That Jazz", artist: "Catherine Zeta-Jones" },
  { id: 5, title: "Wicked Game", artist: "Chris Isaak" },
  { id: 6, title: "Rockabye", artist: "Clean Bandit" },
  { id: 7, title: "Pour Some Sugar On Me", artist: "Def Leppard" },
  { id: 8, title: "Sunflower", artist: "Dizzy" },
  { id: 9, title: "Let Me Love You", artist: "DJ Snake" },
  { id: 10, title: "Jolene", artist: "Dolly Parton" },
  { id: 11, title: "Viva Las Vegas", artist: "Elvis Presley" },
  { id: 12, title: "Lithium", artist: "Evanescence" },
  { id: 13, title: "Still Alive", artist: "Evynne Hollens" },
  { id: 14, title: "Big Girls Don't Cry", artist: "Frankie Valli & The Four Seasons" },
  { id: 15, title: "Shotgun", artist: "George Ezra" },
  { id: 16, title: "Faith", artist: "George Michael" },
  { id: 17, title: "Ooh Aah Just a Little Bit", artist: "Gina G" },
  { id: 18, title: "I Just Wanna Live", artist: "Good Charlotte" },
  { id: 19, title: "You Can't Stop The Beat", artist: "Hairspray" },
  { id: 20, title: "MMMBop", artist: "Hanson" },
  { id: 21, title: "Ohio Is For Lovers", artist: "Hawthorne Heights" },
  { id: 22, title: "There's a Kind of Hush", artist: "Herman's Hermits" },
  { id: 23, title: "Running On Empty", artist: "Jackson Browne" },
  { id: 24, title: "A Boy Named Sue", artist: "Johnny Cash" },
  { id: 25, title: "Big Yellow Taxi", artist: "Joni Mitchell" },
  { id: 26, title: "Chemicals", artist: "JVNA" },
  { id: 27, title: "Too Shy", artist: "Kajagoogoo" },
  { id: 28, title: "The One That Got Away", artist: "Katy Perry" },
  { id: 29, title: "Hard Man to Love", artist: "Kevin Fowler" },
  { id: 30, title: "Go Insane", artist: "Lindsay Buckingham" },
  { id: 31, title: "Last Train Home", artist: "Lostprophets" },
  { id: 32, title: "Welcome to the Black Parade", artist: "My Chemical Romance" },
  { id: 33, title: "Promises", artist: "Nero" },
  { id: 34, title: "All Downhill From Here", artist: "New Found Glory" },
  { id: 35, title: "Since We're Alone", artist: "Niall Horan" },
  { id: 36, title: "Late Night", artist: "Odesza" },
  { id: 37, title: "Here It Goes Again", artist: "OK Go" },
  { id: 38, title: "Make It Sweet", artist: "Old Dominion" },
  { id: 39, title: "High Hopes", artist: "Panic! At The Disco" },
  { id: 40, title: "That's What You Get", artist: "Paramore" },
  { id: 41, title: "Sledgehammer", artist: "Peter Gabriel" },
  { id: 42, title: "Downtown", artist: "Petula Clark" },
  { id: 43, title: "Son of Man", artist: "Phil Collins" },
  { id: 44, title: "Little Red Corvette", artist: "Prince" },
  { id: 45, title: "Blurry", artist: "Puddle of Mudd" },
  { id: 46, title: "We Will Rock You", artist: "Queen" },
  { id: 47, title: "Can't Stop", artist: "Red Hot Chili Peppers" },
  { id: 48, title: "You've Lost That Loving Feeling", artist: "Righteous Brothers" },
  { id: 49, title: "King of the Road", artist: "Roger Miller" },
  { id: 50, title: "The Piña Colada Song", artist: "Rupert Holmes" },
  { id: 51, title: "Brave", artist: "Sara Bareilles" },
  { id: 52, title: "I Want You", artist: "Savage Garden" },
  { id: 53, title: "Buried A Lie", artist: "Senses Fall" },
  { id: 54, title: "Perfect", artist: "Simple Plan" },
  { id: 55, title: "6 Underground", artist: "Sneaker Pimps" },
  { id: 56, title: "Stand Back", artist: "Stevie Nicks" },
  { id: 57, title: "I Can't Hold Back", artist: "Survivor" },
  { id: 58, title: "Once In A Lifetime", artist: "Talking Heads" },
  { id: 59, title: "Guys", artist: "The 1975" },
  { id: 60, title: "You Might Think", artist: "The Cars" },
  { id: 61, title: "Closer", artist: "The Chainsmokers" },
  { id: 62, title: "Rock The Casbah", artist: "The Clash" },
  { id: 63, title: "I Believe In A Thing Called Love", artist: "The Darkness" },
  { id: 64, title: "People Are Strange", artist: "The Doors" },
  { id: 65, title: "Walk Away Renee", artist: "The Four Tops" },
  { id: 66, title: "Every Little Thing...Magic", artist: "The Police" },
  { id: 67, title: "Seven Nation Army", artist: "The White Stripes" },
  { id: 68, title: "Jenny", artist: "Tommy Tutone" },
  { id: 69, title: "Believe Me Baby, I Lied", artist: "Trisha Yearwood & Kelly Clarkson" },
  { id: 70, title: "Cantaloop", artist: "Us3" },
  { id: 71, title: "This Is Life", artist: "Vampire Weekend" },
  { id: 72, title: "We Like To Party!", artist: "Vengaboys" },
  { id: 73, title: "Word Crimes", artist: "Weird Al Yankovic" },
  { id: 74, title: "Gettin' Jiggy Wit It", artist: "Will Smith" },
  { id: 75, title: "Only One", artist: "Yellowcard" },
];

export const PLAYLIST_12 = [
  { id: 1, title: "Mood", artist: "24kGoldn" },
  { id: 2, title: "Back In Black", artist: "ACDC" },
  { id: 3, title: "Lost In Love", artist: "Air Supply" },
  { id: 4, title: "Stay", artist: "Alessia Cara" },
  { id: 5, title: "Heat Of The Moment", artist: "Asia" },
  { id: 6, title: "Turn Up the Radio", artist: "Autograph" },
  { id: 7, title: "The Motto", artist: "Ava Max" },
  { id: 8, title: "Sk8er Boi", artist: "Avril Lavigne" },
  { id: 9, title: "bad guy", artist: "Billie Eilish" },
  { id: 10, title: "Eyes Without A Face", artist: "Billy Idol" },
  { id: 11, title: "Coffee and TV", artist: "Blur" },
  { id: 12, title: "It's My Life", artist: "Bon Jovi" },
  { id: 13, title: "Remind Me", artist: "Brad Paisley" },
  { id: 14, title: "Circus", artist: "Britney Spears" },
  { id: 15, title: "When I Was Your Man", artist: "Bruno Mars" },
  { id: 16, title: "Don't Go Yet", artist: "Camila Cabello" },
  { id: 17, title: "Church Bells", artist: "Carrie Underwood" },
  { id: 18, title: "See You Again", artist: "Charlie Puth" },
  { id: 19, title: "It's In His Kiss", artist: "Cher" },
  { id: 20, title: "Oh", artist: "Ciara" },
  { id: 21, title: "We Both Know", artist: "Colbie Caillat" },
  { id: 22, title: "The Scientist", artist: "Coldplay" },
  { id: 23, title: "10,000 Hours", artist: "Dan + Shay" },
  { id: 24, title: "True Survivor", artist: "David Hasselhoff" },
  { id: 25, title: "OK Not To Be OK", artist: "Demi Lovato" },
  { id: 26, title: "Lose My Breath", artist: "Destiny's Child" },
  { id: 27, title: "Why Do Fools Fall In Love", artist: "Diana Ross" },
  { id: 28, title: "Drift Away", artist: "Dobie Gray" },
  { id: 29, title: "Don't Start Now", artist: "Dua Lipa" },
  { id: 30, title: "Rio", artist: "Duran Duran" },
  { id: 31, title: "Party All the Time", artist: "Eddie Murphy" },
  { id: 32, title: "Walking On A Dream", artist: "Empire Of The Sun" },
  { id: 33, title: "Dance, Dance", artist: "Fall Out Boy" },
  { id: 34, title: "Cold As Ice", artist: "Foreigner" },
  { id: 35, title: "The Sweet Escape", artist: "Gwen Stefani" },
  { id: 36, title: "Love Myself", artist: "Hailee Steinfeld" },
  { id: 37, title: "Private Eyes", artist: "Hall and Oates" },
  { id: 38, title: "I Am Not a Woman I'm a God", artist: "Halsey" },
  { id: 39, title: "I'm Into Something Good", artist: "Hermans Hermits" },
  { id: 40, title: "Into the Unknown", artist: "Idina Menzel" },
  { id: 41, title: "The Number Of The Beast", artist: "Iron Maiden" },
  { id: 42, title: "Jenny from the Block", artist: "Jennifer Lopez" },
  { id: 43, title: "Aqualung", artist: "Jethro Tull" },
  { id: 44, title: "I Love Rock 'N Roll", artist: "Joan Jett" },
  { id: 45, title: "Take Me Home, Country Roads", artist: "John Denver" },
  { id: 46, title: "Sucker", artist: "Jonas Brothers" },
  { id: 47, title: "Anyone", artist: "Justin Bieber" },
  { id: 48, title: "Dilemma", artist: "Kelly Rowland" },
  { id: 49, title: "Paparazzi", artist: "Lady Gaga" },
  { id: 50, title: "Someone You Loved", artist: "Lewis Capaldi" },
  { id: 51, title: "Numb", artist: "Linkin Park" },
  { id: 52, title: "Beer Never Broke My Heart", artist: "Luke Combs" },
  { id: 53, title: "I Try", artist: "Macy Gray" },
  { id: 54, title: "Fantasy", artist: "Mariah Carey" },
  { id: 55, title: "One More Night", artist: "Maroon 5" },
  { id: 56, title: "Right Back Where We Started From", artist: "Maxine Nightingale" },
  { id: 57, title: "Me and Mrs. Jones", artist: "Michael Bublé" },
  { id: 58, title: "The Way You Make Me Feel", artist: "Michael Jackson" },
  { id: 59, title: "Stolen Dance", artist: "Milky Chance" },
  { id: 60, title: "Breakin' Up Is Hard To Do", artist: "Neil Sedaka" },
  { id: 61, title: "Everybody Talks", artist: "Neon Trees" },
  { id: 62, title: "Absolutely (Story of a Girl)", artist: "Nine Days" },
  { id: 63, title: "Hopelessly Devoted To You", artist: "Olivia Newton-John" },
  { id: 64, title: "drivers license", artist: "Olivia Rodrigo" },
  { id: 65, title: "According To You", artist: "Orianthi" },
  { id: 66, title: "Straight Up", artist: "Paula Abdul" },
  { id: 67, title: "In The Air Tonight", artist: "Phil Collins" },
  { id: 68, title: "Comfortably Numb", artist: "Pink Floyd" },
  { id: 69, title: "1999", artist: "Prince" },
  { id: 70, title: "Killer Queen", artist: "Queen" },
  { id: 71, title: "Otherside", artist: "Red Hot Chili Peppers" },
  { id: 72, title: "Stay With Me", artist: "Sam Smith" },
  { id: 73, title: "Closing Time", artist: "Semisonic" },
  { id: 74, title: "Treat You Better", artist: "Shawn Mendes" },
  { id: 75, title: "If It Makes You Happy", artist: "Sheryl Crow" },
];

export const PLAYLIST_13 = [
  { id: 1, title: "How Long", artist: "Ace" },
  { id: 2, title: "Thank U", artist: "Alanis Morissette" },
  { id: 3, title: "Tide is High", artist: "Atomic Kittens" },
  { id: 4, title: "Sweet but Psycho", artist: "Ava Max" },
  { id: 5, title: "Mad About You", artist: "Belinda Carlisle" },
  { id: 6, title: "everything i wanted", artist: "Billie Eilish" },
  { id: 7, title: "Bloody Sabbath", artist: "Black Sabbath" },
  { id: 8, title: "Livin' On A Prayer", artist: "Bon Jovi" },
  { id: 9, title: "In Case You Didnt Know", artist: "Brett Young" },
  { id: 10, title: "Summer Of 69", artist: "Bryan Adams" },
  { id: 11, title: "My Oh My", artist: "Camila Cabello" },
  { id: 12, title: "Ghost Story", artist: "Carrie Underwood" },
  { id: 13, title: "Gypsys Tramps and Thieves", artist: "Cher" },
  { id: 14, title: "Dont Know What You Got Till Its Gone", artist: "Cinderella" },
  { id: 15, title: "Cupid Shuffle", artist: "Cupid" },
  { id: 16, title: "Lost My Heartbreak", artist: "David J" },
  { id: 17, title: "Ain't That a Kick in the Head", artist: "Dean Martin" },
  { id: 18, title: "I Will Survive", artist: "Diana Ross" },
  { id: 19, title: "Levitating", artist: "Dua Lipa" },
  { id: 20, title: "Shivers", artist: "Ed Sheeran" },
  { id: 21, title: "Whatta Man", artist: "En Vogue" },
  { id: 22, title: "Wild Ones", artist: "Flo Rida" },
  { id: 23, title: "Cruisin", artist: "Gwyneth Paltrow & Huey Lewis" },
  { id: 24, title: "I Cant Go For That", artist: "Hall and Oates" },
  { id: 25, title: "Adore You", artist: "Harry Styles" },
  { id: 26, title: "Bad Boys", artist: "Inner Circle" },
  { id: 27, title: "Whatcha Say", artist: "Jason Derulo" },
  { id: 28, title: "The Middle", artist: "Jimmy Eat World" },
  { id: 29, title: "I Hate Myself for Loving You", artist: "Joan Jett" },
  { id: 30, title: "Any Way You Want It", artist: "Journey" },
  { id: 31, title: "Wuthering Heights", artist: "Kate Bush" },
  { id: 32, title: "Gloria", artist: "Laura Branigan" },
  { id: 33, title: "Old Town Road", artist: "Lil Nas X" },
  { id: 34, title: "Working for the Weekend", artist: "Loverboy" },
  { id: 35, title: "When It Rains It Pours", artist: "Luke Combs" },
  { id: 36, title: "Nobodys Love", artist: "Maroon 5" },
  { id: 37, title: "Down Under", artist: "Men At Work" },
  { id: 38, title: "Beat It", artist: "Michael Jackson" },
  { id: 39, title: "Beds Are Burning", artist: "Midnight Oil" },
  { id: 40, title: "Im Like A Bird", artist: "Nelly Furtado" },
  { id: 41, title: "How You Remind Me", artist: "Nickelback" },
  { id: 42, title: "The Internet", artist: "Oliver Tree" },
  { id: 43, title: "Story of My Life", artist: "One Direction" },
  { id: 44, title: "Ms. Jackson", artist: "OutKast" },
  { id: 45, title: "Misery Business", artist: "Paramore" },
  { id: 46, title: "Another Day In Paradise", artist: "Phil Collins" },
  { id: 47, title: "Congratulations", artist: "Post Malone" },
  { id: 48, title: "Under Pressure", artist: "Queen" },
  { id: 49, title: "We Found Love", artist: "Rihanna" },
  { id: 50, title: "Rock You Like A Hurricane", artist: "Scorpions" },
  { id: 51, title: "Can't Be Saved", artist: "Senses Fail" },
  { id: 52, title: "Summer Of Love", artist: "Shawn Mendes" },
  { id: 53, title: "All I Wanna Do", artist: "Sheryl Crow" },
  { id: 54, title: "Leave the Door Open", artist: "Silk Sonic" },
  { id: 55, title: "Abracadabra", artist: "Steve Miller Band" },
  { id: 56, title: "Santeria", artist: "Sublime" },
  { id: 57, title: "Stuck Like Glue", artist: "Sugarland" },
  { id: 58, title: "Get Back", artist: "The Beatles" },
  { id: 59, title: "Don't You Forget About Me", artist: "The Bellas" },
  { id: 60, title: "So Young", artist: "The Corrs" },
  { id: 61, title: "Summer In The City", artist: "The Lovin' Spoonful" },
  { id: 62, title: "Book Of Love", artist: "The Monotones" },
  { id: 63, title: "Sympathy For The Devil", artist: "The Rolling Stones" },
  { id: 64, title: "Man of Constant Sorrow", artist: "The Soggy Bottom Boys" },
  { id: 65, title: "Dizzy", artist: "Tommy Roe" },
  { id: 66, title: "Tie A Yellow Ribbon", artist: "Tony Orlando & Dawn" },
  { id: 67, title: "Stressed Out", artist: "twenty one pilots" },
  { id: 68, title: "Sunday Bloody Sunday", artist: "U2" },
  { id: 69, title: "Drift Away", artist: "Uncle Kracker" },
  { id: 70, title: "OMG", artist: "Usher" },
  { id: 71, title: "Royals", artist: "Walk off the Earth" },
  { id: 72, title: "Island In The Sun", artist: "Weezer" },
  { id: 73, title: "I'm Every Woman", artist: "Whitney Houston" },
  { id: 74, title: "hope for the underrated youth", artist: "YUNGBLUD" },
  { id: 75, title: "TV Dinners", artist: "ZZ Top" },
];

export const PLAYLIST_14 = [
  { id: 1, title: "Hold On Loosely", artist: "38 Special" },
  { id: 2, title: "Take On Me", artist: "a-ha" },
  { id: 3, title: "Forever Young", artist: "Alphaville" },
  { id: 4, title: "Like a Stone", artist: "Audioslave" },
  { id: 5, title: "You Should Be Dancing", artist: "Bee Gees" },
  { id: 6, title: "Ocean Eyes", artist: "Billie Eilish" },
  { id: 7, title: "Jeff Bezos", artist: "Bo Burnham" },
  { id: 8, title: "Waiting for a Star to Fall", artist: "Boy Meets Girl" },
  { id: 9, title: "Hold Me Closer", artist: "Britney Spears and Elton John" },
  { id: 10, title: "Bam Bam", artist: "Camila Cabello" },
  { id: 11, title: "Dirty Laundry", artist: "Carrie Underwood" },
  { id: 12, title: "Lets Twist Again", artist: "Chubby Checker" },
  { id: 13, title: "Rather Be", artist: "Clean Bandit" },
  { id: 14, title: "I Think About You", artist: "Colin Raye" },
  { id: 15, title: "Life After You", artist: "Daughtry" },
  { id: 16, title: "Panda", artist: "Desiigner" },
  { id: 17, title: "Sultans Of Swing", artist: "Dire Straits" },
  { id: 18, title: "Sharing The Night Together", artist: "Dr Hook" },
  { id: 19, title: "A Thousand Miles From Nowhere", artist: "Dwight Yoakam" },
  { id: 20, title: "Numb Little Bug", artist: "Em Beihold" },
  { id: 21, title: "Everywhere", artist: "Fleetwood Mac" },
  { id: 22, title: "Careless Whisper", artist: "George Michael" },
  { id: 23, title: "Most Girls", artist: "Hailee Steinfeld" },
  { id: 24, title: "Fool", artist: "Handsome Ghost" },
  { id: 25, title: "The Greatest Show", artist: "Hugh Jackman" },
  { id: 26, title: "Centerfold", artist: "J. Geils Band" },
  { id: 27, title: "Great Balls Of Fire", artist: "Jerry Lee Lewis" },
  { id: 28, title: "Rocky Mountain High", artist: "John Denver" },
  { id: 29, title: "Open Arms", artist: "Journey" },
  { id: 30, title: "Blah Blah Blah", artist: "Ke$ha" },
  { id: 31, title: "I Drive Your Truck", artist: "Lee Brice" },
  { id: 32, title: "Long Tall Sally", artist: "Little Richard" },
  { id: 33, title: "Like A Prayer", artist: "Madonna" },
  { id: 34, title: "Whenever You're On My Mind", artist: "Marshall Crenshaw" },
  { id: 35, title: "The Unforgiven", artist: "Metallica" },
  { id: 36, title: "All You Wanted", artist: "Michelle Branch" },
  { id: 37, title: "Broken Wings", artist: "Mr. Mister" },
  { id: 38, title: "I Only Want To Be With You", artist: "Nicolette Larson" },
  { id: 39, title: "You're the One That I Want", artist: "Olivia Newton John" },
  { id: 40, title: "I Ain't Worried", artist: "OneRepublic" },
  { id: 41, title: "Stupid Girls", artist: "P!nk" },
  { id: 42, title: "Opposites Attract", artist: "Paula Abdul" },
  { id: 43, title: "What, Me Worry", artist: "Portugal. The Man" },
  { id: 44, title: "Raspberry Beret", artist: "Prince" },
  { id: 45, title: "Ghostbusters", artist: "Ray Parker Jr." },
  { id: 46, title: "Hold On Forever", artist: "Rob Thomas" },
  { id: 47, title: "Eenie Meenie", artist: "Sean Kingston" },
  { id: 48, title: "Angel", artist: "Shaggy" },
  { id: 49, title: "Señorita", artist: "Shawn Mendes Camila Cabello" },
  { id: 50, title: "Cheap Thrills", artist: "Sia" },
  { id: 51, title: "I'm Just A Kid", artist: "Simple Plan" },
  { id: 52, title: "Rapper's Delight", artist: "Sugarhill Gang" },
  { id: 53, title: "High On You", artist: "Survivor" },
  { id: 54, title: "Buy U A Drank", artist: "T-Pain" },
  { id: 55, title: "Blank Space", artist: "Taylor Swift" },
  { id: 56, title: "Roam", artist: "The B52s" },
  { id: 57, title: "Manic Monday", artist: "The Bangles" },
  { id: 58, title: "I Feel Fine", artist: "The Beatles" },
  { id: 59, title: "Mr Tambourine Man", artist: "The Byrds" },
  { id: 60, title: "Summer Sunshine", artist: "The Corrs" },
  { id: 61, title: "California Dreamin", artist: "The Mamas and The Papas" },
  { id: 62, title: "Start Me Up", artist: "The Rolling Stones" },
  { id: 63, title: "1979", artist: "The Smashing Pumpkins" },
  { id: 64, title: "Take My Breath", artist: "The Weeknd" },
  { id: 65, title: "I Think We're Alone Now", artist: "Tiffany" },
  { id: 66, title: "Dance Monkey", artist: "Tones and I" },
  { id: 67, title: "Headstrong", artist: "Trapt" },
  { id: 68, title: "Ride", artist: "twenty one pilots" },
  { id: 69, title: "I Still Haven't Found What I'm Looking For", artist: "U2" },
  { id: 70, title: "Smile", artist: "Uncle Kracker" },
  { id: 71, title: "Yeah", artist: "Usher" },
  { id: 72, title: "The Night the Lights Went Out in Georgia", artist: "Vicki Lawrence" },
  { id: 73, title: "Beverly Hills", artist: "Weezer" },
  { id: 74, title: "I Wanna Dance With Somebody", artist: "Whitney Houston" },
  { id: 75, title: "Roundabout", artist: "Yes" },
];

export const PLAYLIST_15 = [
  { id: 1, title: "Does Your Mother Know", artist: "ABBA" },
  { id: 2, title: "Lonely", artist: "Akon" },
  { id: 3, title: "Chemicals React", artist: "Aly & AJ" },
  { id: 4, title: "i remember", artist: "bbno$" },
  { id: 5, title: "Bellyache", artist: "Billie Eilish" },
  { id: 6, title: "Still Rock and Roll To Me", artist: "Billy Joel" },
  { id: 7, title: "Nothin On You", artist: "BoB" },
  { id: 8, title: "Already Gone", artist: "Brett Dennen" },
  { id: 9, title: "Let Go", artist: "Brother Phelps" },
  { id: 10, title: "I Really Like You", artist: "Carly Rae Jepsen" },
  { id: 11, title: "Jesus Take The Wheel", artist: "Carrie Underwood" },
  { id: 12, title: "1_2 Step", artist: "Ciara" },
  { id: 13, title: "Something Just Like This", artist: "Coldplay" },
  { id: 14, title: "This", artist: "Darius Rucker" },
  { id: 15, title: "Power Over Me", artist: "Dermot Kennedy" },
  { id: 16, title: "A Teenager In Love", artist: "Dion The Belmonts" },
  { id: 17, title: "Say So", artist: "Doja Cat" },
  { id: 18, title: "Hungry Like the Wolf", artist: "Duran Duran" },
  { id: 19, title: "Cold Heart (PNAU Remix)", artist: "Elton John & Dua Lipa" },
  { id: 20, title: "Talladega", artist: "Eric Church" },
  { id: 21, title: "Come Fly With Me", artist: "Frank Sinatra" },
  { id: 22, title: "Cupid's Chokehold", artist: "Gym Class Heroes" },
  { id: 23, title: "Bad At Love", artist: "Halsey" },
  { id: 24, title: "Hip To Be Square", artist: "Huey Lewis & The News" },
  { id: 25, title: "Love You Down", artist: "INOJ" },
  { id: 26, title: "The Time Of My Life", artist: "Jennifer Warnes & Bill Medley" },
  { id: 27, title: "Bad Reputation", artist: "Joan Jett" },
  { id: 28, title: "Leave Before You Love Me", artist: "Jonas Brothers" },
  { id: 29, title: "Mirrors", artist: "Justin Timberlake" },
  { id: 30, title: "Better", artist: "Khalid" },
  { id: 31, title: "Holiday Road", artist: "Lindsey Buckingham" },
  { id: 32, title: "Forever After All", artist: "Luke Combs" },
  { id: 33, title: "Emotions", artist: "Mariah Carey" },
  { id: 34, title: "Bent", artist: "Matchbox Twenty" },
  { id: 35, title: "Phantom of the Opera", artist: "Michael Crawford" },
  { id: 36, title: "Whiskey Glasses", artist: "Morgan Wallen" },
  { id: 37, title: "Animal", artist: "Neon Trees" },
  { id: 38, title: "Hey Baby", artist: "No Doubt" },
  { id: 39, title: "deja vu", artist: "Olivia Rodrigo" },
  { id: 40, title: "Fireflies", artist: "Owl City" },
  { id: 41, title: "Love Is a Battlefield", artist: "Pat Benatar" },
  { id: 42, title: "Another Brick In The Wall", artist: "Pink Floyd" },
  { id: 43, title: "Circles", artist: "Post Malone" },
  { id: 44, title: "Another One Bites the Dust", artist: "Queen" },
  { id: 45, title: "Californication", artist: "Red Hot Chili Peppers" },
  { id: 46, title: "Crash and Burn", artist: "Savage Garden" },
  { id: 47, title: "Naturally", artist: "Selena Gomez" },
  { id: 48, title: "Whenever Wherever", artist: "Shakira" },
  { id: 49, title: "The Glamorous Life", artist: "Sheila E" },
  { id: 50, title: "Watch Me", artist: "Silentó" },
  { id: 51, title: "Two Princes", artist: "Spin Doctors" },
  { id: 52, title: "Babe", artist: "Sugarland" },
  { id: 53, title: "AOK", artist: "Tai Verdes" },
  { id: 54, title: "Daydream", artist: "The Aces" },
  { id: 55, title: "I Think I Like You", artist: "The Band Camino" },
  { id: 56, title: "Help", artist: "The Beatles" },
  { id: 57, title: "Where Is The Love", artist: "The Black Eyed Peas" },
  { id: 58, title: "Breathless", artist: "The Corrs" },
  { id: 59, title: "Don't You Want Me", artist: "The Human League" },
  { id: 60, title: "Only The Lonely", artist: "The Motels" },
  { id: 61, title: "What I Like About You", artist: "The Romantics" },
  { id: 62, title: "Glad You Came", artist: "The Wanted" },
  { id: 63, title: "She Blinded Me With Science", artist: "Thomas Dolby" },
  { id: 64, title: "Waterfalls", artist: "TLC" },
  { id: 65, title: "Mickey", artist: "Toni Basil" },
  { id: 66, title: "Play That Song", artist: "Train" },
  { id: 67, title: "Falling", artist: "Trevor Daniel" },
  { id: 68, title: "We're Not Gonna Take It", artist: "Twisted Sister" },
  { id: 69, title: "Follow Me", artist: "Uncle Kracker" },
  { id: 70, title: "DJ Got Us Fallin' In Love", artist: "Usher" },
  { id: 71, title: "Hot For Teacher", artist: "Van Halen" },
  { id: 72, title: "Werewolves of London", artist: "Warren Zevon" },
  { id: 73, title: "I Lost On Jeopardy", artist: "Weird Al Yankovic" },
  { id: 74, title: "Men In Black", artist: "Will Smith" },
  { id: 75, title: "Pillowtalk", artist: "Zayn" },
];



export const PLAYLIST_16 = PLAYLIST_6;
export const PLAYLIST_17 = PLAYLIST_7;

