import type { PlaylistItem } from "./eventConfig";

export const PLAYLIST_1: PlaylistItem[] = [
  { id: 1, title: "Kryptonite", artist: "3 Doors Down" },
  { id: 2, title: "So Caught Up In You", artist: ".38 Special" },
  { id: 3, title: "Take On Me", artist: "a-ha" },
  { id: 4, title: "Take A Chance On Me", artist: "Abba" },
  { id: 5, title: "You Shook Me All Night", artist: "AC/DC" },
  { id: 6, title: "Beautiful Life", artist: "Ace of Base" },
  { id: 7, title: "Rumor Has It", artist: "Adele" },
  { id: 8, title: "Because I Got High", artist: "Afroman" },
  { id: 9, title: "Dixieland Delight", artist: "Alabama" },
  { id: 10, title: "Faded", artist: "Alan Walker" },
  { id: 11, title: "Fallin'", artist: "Alicia Keys" },
  { id: 12, title: "Forever Young", artist: "Alphaville" },
  { id: 13, title: "Best Day Of My Life", artist: "American Authors" },
  { id: 14, title: "Side To Side", artist: "Ariana Grande" },
  { id: 15, title: "Sail", artist: "AWOLNATION" },
  { id: 16, title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys" },
  { id: 17, title: "Come And Get It", artist: "Badfinger" },
  { id: 18, title: "Cruel Summer", artist: "Bananarama" },
  { id: 19, title: "It's All Been Done", artist: "Barenaked Ladies" },
  { id: 20, title: "If I Were A Boy", artist: "Beyoncé" },
  { id: 21, title: "Save A Horse", artist: "Big and Rich" },
  { id: 22, title: "Rebel Yell", artist: "Billy Idol" },
  { id: 23, title: "Piano Man", artist: "Billy Joel" },
  { id: 24, title: "Get Outta My Dreams", artist: "Billy Ocean" },
  { id: 25, title: "No Diggity", artist: "Blackstreet" },
  { id: 26, title: "Blaze of Glory", artist: "Bon Jovi" },
  { id: 27, title: "Something To Talk About", artist: "Bonnie Raitt" },
  { id: 28, title: "1985", artist: "Bowling For Soup" },
  { id: 29, title: "Motownphilly", artist: "Boyz II Men" },
  { id: 30, title: "Lucky", artist: "Britney Spears" },
  { id: 31, title: "My Maria", artist: "Brooks & Dunn" },
  { id: 32, title: "Born In The U.S.A.", artist: "Bruce Springsteen" },
  { id: 33, title: "You're So Vain", artist: "Carly Simon" },
  { id: 34, title: "Cowboy Casanova", artist: "Carrie Underwood" },
  { id: 35, title: "My Heart Will Go On", artist: "Celine Dion" },
  { id: 36, title: "Bootylicious", artist: "Destiny's Child" },
  { id: 37, title: "Meet In The Middle", artist: "Diamond Rio" },
  { id: 38, title: "I Say A Little Prayer", artist: "Dionne Warwick" },
  { id: 39, title: "Goodbye Earl", artist: "Dixie Chicks" },
  { id: 40, title: "Sad Songs", artist: "Elton John" },
  { id: 41, title: "Hungry Eyes", artist: "Eric Carmen" },
  { id: 42, title: "The Final Countdown", artist: "Europe" },
  { id: 43, title: "Sugar, We're Goin' Down", artist: "Fall Out Boy" },
  { id: 44, title: "Superman", artist: "Five For Fighting" },
  { id: 45, title: "The Chain", artist: "Fleetwood Mac" },
  { id: 46, title: "The Pretender", artist: "Foo Fighters" },
  { id: 47, title: "I Want To Know What Love Is", artist: "Foreigner" },
  { id: 48, title: "Ain't Going Down 'Til The Sun Comes Up", artist: "Garth Brooks" },
  { id: 49, title: "I Cross My Heart", artist: "George Strait" },
  { id: 50, title: "I Will Survive", artist: "Gloria Gaynor" },
  { id: 51, title: "Crazy", artist: "Gnarls Barkley" },
  { id: 52, title: "Crimson And Clover", artist: "Joan Jett" },
  { id: 53, title: "Ring Of Fire", artist: "Johnny Cash" },
  { id: 54, title: "Last Friday Night (T.G.I.F.)", artist: "Katy Perry" },
  { id: 55, title: "Tik Tok", artist: "Ke$ha" },
  { id: 56, title: "Since U Been Gone", artist: "Kelly Clarkson" },
  { id: 57, title: "Leap Of Faith", artist: "Lionel Cartwright" },
  { id: 58, title: "Rude", artist: "MAGIC!" },
  { id: 59, title: "I Need To Know", artist: "Marc Anthony" },
  { id: 60, title: "Haven't Met You Yet", artist: "Michael Bublé" },
  { id: 61, title: "Everywhere", artist: "Michelle Branch" },
  { id: 62, title: "Party In The U.S.A.", artist: "Miley Cyrus" },
  { id: 63, title: "You'll Never Know", artist: "Mindy McCready" },
  { id: 64, title: "99 Luftballons", artist: "Nena" },
  { id: 65, title: "You Get What You Give", artist: "New Radicals" },
  { id: 66, title: "It's My Life", artist: "No Doubt" },
  { id: 67, title: "Gone, Gone, Gone", artist: "Phillip Phillips" },
  { id: 68, title: "Jessie's Girl", artist: "Rick Springfield" },
  { id: 69, title: "Stranger In My House", artist: "Ronnie Milsap" },
  { id: 70, title: "Kill Bill", artist: "RZA" },
  { id: 71, title: "King Of Anything", artist: "Sara Bareilles" },
  { id: 72, title: "Any Man Of Mine", artist: "Shania Twain" },
  { id: 73, title: "Venus", artist: "Shocking Blue" },
  { id: 74, title: "All For You", artist: "Sister Hazel" },
];

export const PLAYLIST_2: PlaylistItem[] = [
  { id: 1, title: "Kryptonite", artist: "Ed Sheeran" },
  { id: 2, title: "So Caught Up In You", artist: "ELO" },
  { id: 3, title: "Take On Me", artist: "Evanescence" },
  { id: 4, title: "Take A Chance On Me", artist: "Faith Hill" },
  { id: 5, title: "You Shook Me All Night", artist: "Finger Eleven" },
  { id: 6, title: "Beautiful Life", artist: "Flo Rida" },
  { id: 7, title: "Rumor Has It", artist: "Flobots" },
  { id: 8, title: "Because I Got High", artist: "Four Non-Blondes" },
  { id: 9, title: "Dixieland Delight", artist: "Frankie Goes To Hollywood" },
  { id: 10, title: "Faded", artist: "Gary Numan" },
  { id: 11, title: "Fallin'", artist: "Gin Blossoms" },
  { id: 12, title: "Forever Young", artist: "Gotye" },
  { id: 13, title: "Best Day Of My Life", artist: "Gretchen Wilson" },
  { id: 14, title: "Side To Side", artist: "Heart" },
  { id: 15, title: "Sail", artist: "Hilary Duff" },
  { id: 16, title: "Everybody (Backstreet's Back)", artist: "Jefferson Airplane" },
  { id: 17, title: "Come And Get It", artist: "Jerry Reed" },
  { id: 18, title: "Cruel Summer", artist: "John Anderson" },
  { id: 19, title: "It's All Been Done", artist: "John Mayer" },
  { id: 20, title: "If I Were A Boy", artist: "Katy Perry" },
  { id: 21, title: "Save A Horse", artist: "Kenny Loggins" },
  { id: 22, title: "Rebel Yell", artist: "KISS" },
  { id: 23, title: "Piano Man", artist: "Lady Antebellum" },
  { id: 24, title: "Get Outta My Dreams", artist: "Lauryn Hill" },
  { id: 25, title: "No Diggity", artist: "Lenny Kravitz" },
  { id: 26, title: "Blaze of Glory", artist: "Lovin' Spoonful" },
  { id: 27, title: "Something To Talk About", artist: "Luis Fonsi" },
  { id: 28, title: "1985", artist: "Matchbox Twenty" },
  { id: 29, title: "Motownphilly", artist: "Miley Cyrus" },
  { id: 30, title: "Lucky", artist: "Modern English" },
  { id: 31, title: "My Maria", artist: "Neil Diamond" },
  { id: 32, title: "Born In The U.S.A.", artist: "Neil Sedaka" },
  { id: 33, title: "You're So Vain", artist: "New Found Glory" },
  { id: 34, title: "Cowboy Casanova", artist: "Nicki Minaj" },
  { id: 35, title: "My Heart Will Go On", artist: "OMI" },
  { id: 36, title: "Bootylicious", artist: "Ratt" },
  { id: 37, title: "Meet In The Middle", artist: "Rockwell" },
  { id: 38, title: "I Say A Little Prayer", artist: "Salt-N-Pepa" },
  { id: 39, title: "Goodbye Earl", artist: "Sara Evans" },
  { id: 40, title: "Sad Songs", artist: "Shania Twain" },
  { id: 41, title: "Hungry Eyes", artist: "Shawn Colvin" },
  { id: 42, title: "The Final Countdown", artist: "Sheryl Crow" },
  { id: 43, title: "Sugar, We're Goin' Down", artist: "Sia" },
  { id: 44, title: "Superman", artist: "Sister Sledge" },
  { id: 45, title: "The Chain", artist: "Sly & The Family Stone" },
  { id: 46, title: "The Pretender", artist: "Smashmouth" },
  { id: 47, title: "I Want To Know What Love Is", artist: "The Archies" },
  { id: 48, title: "Ain't Going Down 'Til The Sun Comes Up", artist: "The B-52s" },
  { id: 49, title: "I Cross My Heart", artist: "The Beatles" },
  { id: 50, title: "I Will Survive", artist: "The Carpenters" },
  { id: 51, title: "Crazy", artist: "The Doors" },
  { id: 52, title: "Crimson And Clover", artist: "The Fray" },
  { id: 53, title: "Ring Of Fire", artist: "The Hollies" },
  { id: 54, title: "Last Friday Night (T.G.I.F.)", artist: "The Killers" },
  { id: 55, title: "Tik Tok", artist: "The Mamas & The Papas" },
  { id: 56, title: "Since U Been Gone", artist: "The Pussycat Dolls" },
  { id: 57, title: "Leap Of Faith", artist: "The Rembrandts" },
  { id: 58, title: "Rude", artist: "The Temptations" },
  { id: 59, title: "I Need To Know", artist: "The Tokens" },
  { id: 60, title: "Haven't Met You Yet", artist: "Third Eye Blind" },
  { id: 61, title: "Everywhere", artist: "Tim McGraw" },
  { id: 62, title: "Party In The U.S.A.", artist: "Toby Keith" },
  { id: 63, title: "You'll Never Know", artist: "Tommy James" },
  { id: 64, title: "99 Luftballons", artist: "Toto" },
  { id: 65, title: "You Get What You Give", artist: "Travis Tritt" },
  { id: 66, title: "It's My Life", artist: "Vance Joyo" },
  { id: 67, title: "Gone, Gone, Gone", artist: "Vanessa Carlton" },
  { id: 68, title: "Jessie's Girl", artist: "Village People" },
  { id: 69, title: "Stranger In My House", artist: "Warrant" },
  { id: 70, title: "Kill Bill", artist: "Weezer" },
  { id: 71, title: "King Of Anything", artist: "Weird Al Yankovic" },
  { id: 72, title: "Any Man Of Mine", artist: "Whitney Houston" },
  { id: 73, title: "Venus", artist: "Wynonna Judd" },
  { id: 74, title: "All For You", artist: "Ylvis" },
  { id: 75, title: "Clarity", artist: "Zedd" },
];

export const PLAYLIST_3: PlaylistItem[] = [
  { id: 1, title: "Are You That Somebody", artist: "Aaliyah" },
  { id: 2, title: "The Sign", artist: "Ace of Base" },
  { id: 3, title: "Dude (Looks Like A Lady)", artist: "Aerosmith" },
  { id: 4, title: "All Out of Love", artist: "Air Supply" },
  { id: 5, title: "Song of the South", artist: "Alabama" },
  { id: 6, title: "It's 5 O'Clock Somewhere", artist: "Alan Jackson" },
  { id: 7, title: "Black Velvet", artist: "Alannah Myles" },
  { id: 8, title: "Potential Breakup Song", artist: "Aly & AJ" },
  { id: 9, title: "Time to Say Goodbye", artist: "Andrea Bocelli" },
  { id: 10, title: "Cups", artist: "Anna Kendrick" },
  { id: 11, title: "Do I Wanna Know", artist: "Arctic Monkeys" },
  { id: 12, title: "Complicated", artist: "Avril Lavigne" },
  { id: 13, title: "It's All Been Done", artist: "Barenaked Ladies" },
  { id: 14, title: "Intergalactic", artist: "Beastie Boys" },
  { id: 15, title: "More than a Woman", artist: "Bee Gees" },
  { id: 16, title: "Rock Around the Clock", artist: "Billy Haley & His Comets" },
  { id: 17, title: "You May Be Right", artist: "Billy Joel" },
  { id: 18, title: "Hit 'Em Up Style", artist: "Blu Cantrell" },
  { id: 19, title: "Hooked on a Feeling", artist: "Blue Swede" },
  { id: 20, title: "Runaround", artist: "Blues Traveler" },
  { id: 21, title: "Green Onions", artist: "Booker T. & The M.G.'s" },
  { id: 22, title: "Stronger", artist: "Britney Spears" },
  { id: 23, title: "That'll Be The Day", artist: "Buddy Holly & The Crickets" },
  { id: 24, title: "Ain't No Rest for the Wicked", artist: "Cage the Elephant" },
  { id: 25, title: "Havana", artist: "Camila Cabello" },
  { id: 26, title: "We Don't Talk Anymore", artist: "Charlie Puth" },
  { id: 27, title: "Believe", artist: "Cher" },
  { id: 28, title: "Hymn for the Weekend", artist: "Coldplay" },
  { id: 29, title: "Mr. Jones", artist: "Counting Crows" },
  { id: 30, title: "Higher", artist: "Creed" },
  { id: 31, title: "Bad Day", artist: "Daniel Powter" },
  { id: 32, title: "That's Amore", artist: "Dean Martin" },
  { id: 33, title: "Groove Is in the Heart", artist: "Deee-Lite" },
  { id: 34, title: "Say My Name", artist: "Destiny's Child" },
  { id: 35, title: "Come on Eileen", artist: "Dexy's Midnight Runners" },
  { id: 36, title: "I'm Shipping Up to Boston", artist: "Dropkick Murphy's" },
  { id: 37, title: "Mercy", artist: "Duffy" },
  { id: 38, title: "Thinking Out Loud", artist: "Ed Sheeran" },
  { id: 39, title: "Tiny Dancer", artist: "Elton John" },
  { id: 40, title: "Centuries", artist: "Fall Out Boy" },
  { id: 41, title: "HandClap", artist: "Fitz and The Tantrums" },
  { id: 42, title: "I Ran", artist: "Flock of Seagulls" },
  { id: 43, title: "Round Here", artist: "Florida Georgia Line" },
  { id: 44, title: "Learn To Fly", artist: "Foo Fighters" },
  { id: 45, title: "Careless Whisper", artist: "George Michael" },
  { id: 46, title: "Rhinestone Cowboy", artist: "Glen Campbell" },
  { id: 47, title: "Lifestyles of the Rich and Famous", artist: "Good Charlotte" },
  { id: 48, title: "Basket Case", artist: "Green Day" },
  { id: 49, title: "The Reason", artist: "Hoobastank" },
  { id: 50, title: "Say You Won't Let Go", artist: "James Arthur" },
  { id: 51, title: "Living In America", artist: "James Brown" },
  { id: 52, title: "Domino", artist: "Jessie J" },
  { id: 53, title: "Third Rock From The Sun", artist: "Joe Diffie" },
  { id: 54, title: "Jack & Diane", artist: "John Mellencamp" },
  { id: 55, title: "Firework", artist: "Katy Perry" },
  { id: 56, title: "She Think's My Tractor's Sexy", artist: "Kenny Chesney" },
  { id: 57, title: "Shallow", artist: "Lady Gaga" },
  { id: 58, title: "Party Rock Anthem", artist: "LMFAO" },
  { id: 59, title: "What A Wonderful World", artist: "Louis Armstrong" },
  { id: 60, title: "Material Girl", artist: "Madonna" },
  { id: 61, title: "Safe in the Arms of Love", artist: "Martina McBride" },
  { id: 62, title: "Forever and Ever, Amen", artist: "Randy Travis" },
  { id: 63, title: "Smooth", artist: "Santana" },
  { id: 64, title: "Kiss Me", artist: "Sixpence None the Richer" },
  { id: 65, title: "Wannabe", artist: "Spice Girls" },
  { id: 66, title: "We Are Never Getting Back Together", artist: "Taylor Swift" },
  { id: 67, title: "Who Let the Dogs Out", artist: "The Baja Men" },
  { id: 68, title: "On Broadway", artist: "The Drifters" },
  { id: 69, title: "Working My Way Back to You", artist: "The Four Seasons" },
  { id: 70, title: "Juicy", artist: "The Notorious B.I.G." },
  { id: 71, title: "Leader of the Pack", artist: "The Shangri-Las" },
  { id: 72, title: "Semi-Charmed Life", artist: "Third Eye Blind" },
  { id: 73, title: "Chrome", artist: "Trace Adkins" },
  { id: 74, title: "Everybody Have Fun Tonight", artist: "Wang Chung" },
  { id: 75, title: "Owner of a Lonely Heart", artist: "Yes" },
];

export const PLAYLIST_4: PlaylistItem[] = [
  { id: 1, title: "Let Me Go", artist: "3 Doors Down" },
  { id: 2, title: "Sweet Emotion", artist: "Aerosmith" },
  { id: 3, title: "Spooky", artist: "Atlanta Rhythm Section" },
  { id: 4, title: "Pompeii", artist: "Bastille" },
  { id: 5, title: "Mony Mony", artist: "Billy Idol" },
  { id: 6, title: "Achy Breaky Heart", artist: "Billy Ray Cyrus" },
  { id: 7, title: "Ol' Red", artist: "Blake Shelton" },
  { id: 8, title: "You Give Love a Bad Name", artist: "Bon Jovi" },
  { id: 9, title: "Holding Out For a Hero", artist: "Bonnie Tyler" },
  { id: 10, title: "Mud On The Tires", artist: "Brad Paisley" },
  { id: 11, title: "Glory Days", artist: "Bruce Springsteen" },
  { id: 12, title: "The Distance", artist: "Cake" },
  { id: 13, title: "Summer", artist: "Calvin Harris" },
  { id: 14, title: "Word Up", artist: "Cameo" },
  { id: 15, title: "Good Time", artist: "Carly Rae Jepsen" },
  { id: 16, title: "Yes!", artist: "Chad Brock" },
  { id: 17, title: "Lollipop", artist: "Chordettes" },
  { id: 18, title: "Bubbly", artist: "Colbie Caillet" },
  { id: 19, title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper" },
  { id: 20, title: "Gasolina", artist: "Daddy Yankee" },
  { id: 21, title: "Alright", artist: "Darius Rucker" },
  { id: 22, title: "Heavy Metal", artist: "Don Felder" },
  { id: 23, title: "American Pie", artist: "Don McLean" },
  { id: 24, title: "New Rules", artist: "Dua Lipa" },
  { id: 25, title: "Son of a Preacher Man", artist: "Dusty Springfield" },
  { id: 26, title: "Sing", artist: "Ed Sheeran" },
  { id: 27, title: "Mr. Blue Sky", artist: "ELO" },
  { id: 28, title: "Return to Sender", artist: "Elvis Presley" },
  { id: 29, title: "Hero", artist: "Enrique Iglesias" },
  { id: 30, title: "This Kiss", artist: "Faith Hill" },
  { id: 31, title: "Drunken Lullabies", artist: "Flogging Molly" },
  { id: 32, title: "Blame It on Me", artist: "George Ezra" },
  { id: 33, title: "American Idiot", artist: "Green Day" },
  { id: 34, title: "Welcome to the Jungle", artist: "Guns N' Roses" },
  { id: 35, title: "These Dreams", artist: "Heart" },
  { id: 36, title: "Escapade", artist: "Janet Jackson" },
  { id: 37, title: "I'm Yours", artist: "Jason Mraz" },
  { id: 38, title: "On the Floor", artist: "Jennifer Lopez" },
  { id: 39, title: "Your Raise Me Up", artist: "Josh Groban" },
  { id: 40, title: "Roar", artist: "Katy Perry" },
  { id: 41, title: "All Summer", artist: "Kid Rock" },
  { id: 42, title: "Hideaway", artist: "Kiesza" },
  { id: 43, title: "Telephone", artist: "Lady Gaga" },
  { id: 44, title: "Young and Beautiful", artist: "Lana Del Rey" },
  { id: 45, title: "On the Road", artist: "Lee Roy Parnell" },
  { id: 46, title: "Bleeding Love", artist: "Leona Lewis" },
  { id: 47, title: "Wings", artist: "Little Mix" },
  { id: 48, title: "Always Be My Baby", artist: "Mariah Carey" },
  { id: 49, title: "Two Out of Three Ain't Bad", artist: "Meat Loaf" },
  { id: 50, title: "All About That Bass", artist: "Meghan Trainor" },
  { id: 51, title: "Wonder", artist: "Natalie Merchant" },
  { id: 52, title: "Everybody Talks", artist: "Neon Trees" },
  { id: 53, title: "Wouldn't It Be Good", artist: "Nik Kershaw" },
  { id: 54, title: "Tearin' Up My Heart", artist: "NSYNC" },
  { id: 55, title: "Carlene", artist: "Phil Vassar" },
  { id: 56, title: "Home", artist: "Phillip Phillips" },
  { id: 57, title: "Bohemian Rhapsody", artist: "Queen" },
  { id: 58, title: "Black Betty", artist: "Ram Jam" },
  { id: 59, title: "Cotton Eye Joe", artist: "Rednex" },
  { id: 60, title: "Super Freak", artist: "Rick James" },
  { id: 61, title: "Tonight's the Night", artist: "Rod Stewart" },
  { id: 62, title: "Dirty Little Secret", artist: "The All-American Rejects" },
  { id: 63, title: "Boom Boom Pow", artist: "The Black Eyed Peas" },
  { id: 64, title: "Linger", artist: "The Cranberries" },
  { id: 65, title: "Dumas Walker", artist: "The Kentucky Headhunters" },
  { id: 66, title: "Hypnotize", artist: "The Notorious B.I.G." },
  { id: 67, title: "Be My Baby", artist: "The Ronettes" },
  { id: 68, title: "Bittersweet Symphony", artist: "The Verve" },
  { id: 69, title: "It's Your Love", artist: "Tim McGraw" },
  { id: 70, title: "Free Fallin'", artist: "Tom Petty" },
  { id: 71, title: "Africa", artist: "Toto" },
  { id: 72, title: "Hey, Soul Sister", artist: "Train" },
  { id: 73, title: "Save the Best For Last", artist: "Vanessa Williams" },
  { id: 74, title: "Shut Up and Dance", artist: "Walk the Moon" },
  { id: 75, title: "Buddy Holly", artist: "Weezer" },
];

export const PLAYLIST_5: PlaylistItem[] = [
  { id: 1, title: "Summer of '69", artist: "Bryan Adams" },
  { id: 2, title: "Runaway", artist: "Del Shannon" },
  { id: 3, title: "Shape of You", artist: "Ed Sheeran" },
  { id: 4, title: "Lights", artist: "Ellie Goulding" },
  { id: 5, title: "I Guess That's Why They Call It the Blues", artist: "Elton John" },
  { id: 6, title: "I Shot the Sheriff", artist: "Eric Clapton" },
  { id: 7, title: "Uma Thurman", artist: "Fall Out Boy" },
  { id: 8, title: "Like A G6", artist: "Far East Movement" },
  { id: 9, title: "Big Girls Don't Cry", artist: "Fergie" },
  { id: 10, title: "Work From Home", artist: "Fifth Harmony" },
  { id: 11, title: "Criminal", artist: "Fiona Apple" },
  { id: 12, title: "Stacy's Mom", artist: "Fountains of Wayne" },
  { id: 13, title: "Budapest", artist: "George Ezra" },
  { id: 14, title: "King of Wishful Thinking", artist: "Go West" },
  { id: 15, title: "Feel Good Inc.", artist: "Gorillaz" },
  { id: 16, title: "Boulevard of Broken Dreams", artist: "Green Day" },
  { id: 17, title: "Barracuda", artist: "Heart" },
  { id: 18, title: "Lips of an Angel", artist: "Hinder" },
  { id: 19, title: "Somebody's Baby", artist: "Jackson Browne" },
  { id: 20, title: "Bang Bang", artist: "Jessie J" },
  { id: 21, title: "Are You Gonna Be My Girl", artist: "Jet" },
  { id: 22, title: "Burn", artist: "Jo Dee Messina" },
  { id: 23, title: "Love Me Again", artist: "John Newman" },
  { id: 24, title: "Queen of Hearts", artist: "Juice Newton" },
  { id: 25, title: "Can't Stop the Feeling!", artist: "Justin Timberlake" },
  { id: 26, title: "Die Young", artist: "Ke$ha" },
  { id: 27, title: "Stronger", artist: "Kelly Clarkson" },
  { id: 28, title: "Bette Davis Eyes", artist: "Kim Carnes" },
  { id: 29, title: "Macarena", artist: "Los del Rio" },
  { id: 30, title: "Mambo No. 5", artist: "Lou Bega" },
  { id: 31, title: "I Don't Want This Night to End", artist: "Luke Bryan" },
  { id: 32, title: "Papa Don't Preach", artist: "Madonna" },
  { id: 33, title: "Sugar", artist: "Maroon 5" },
  { id: 34, title: "Shake It", artist: "Metro Station" },
  { id: 35, title: "Bad", artist: "Michael Jackson" },
  { id: 36, title: "Unwritten", artist: "Natasha Bedingfield" },
  { id: 37, title: "I Need Never Get Old", artist: "Nathaniel Rateliff" },
  { id: 38, title: "The Shake", artist: "Neal McCoy" },
  { id: 39, title: "Am I Wrong", artist: "Nico & Vinz" },
  { id: 40, title: "How Bizarre", artist: "OMC" },
  { id: 41, title: "Silly Love Songs", artist: "Paul McCartney" },
  { id: 42, title: "Gangnam Style", artist: "PSY" },
  { id: 43, title: "You're My Best Friend", artist: "Queen" },
  { id: 44, title: "Shiny Happy People", artist: "R.E.M." },
  { id: 45, title: "Life is a Highway", artist: "Rascall Flatts" },
  { id: 46, title: "Fancy", artist: "Reba McEntire" },
  { id: 47, title: "This is What Your Came For", artist: "Rihanna" },
  { id: 48, title: "Blurred Lines", artist: "Robin Thicke" },
  { id: 49, title: "House Party", artist: "Sam Hunt" },
  { id: 50, title: "Affirmation", artist: "Savage Garden" },
  { id: 51, title: "Up!", artist: "Shania Twain" },
  { id: 52, title: "Stitches", artist: "Shawn Mendes" },
  { id: 53, title: "Johnny Angel", artist: "Shelley Fabares" },
  { id: 54, title: "Geronimo", artist: "Sheppard" },
  { id: 55, title: "I'm a Believer", artist: "Smashmouth" },
  { id: 56, title: "Tears of a Clown", artist: "Smokey Robinson" },
  { id: 57, title: "Chasing Cars", artist: "Snow Patrol" },
  { id: 58, title: "I Got You Babe", artist: "Sonny and Cher" },
  { id: 59, title: "We Built This City", artist: "Starship" },
  { id: 60, title: "King Tut", artist: "Steve Martin" },
  { id: 61, title: "Back in the High Life Again", artist: "Steve Winwood" },
  { id: 62, title: "The Logical Song", artist: "Supertramp" },
  { id: 63, title: "She's So High", artist: "Tal Bachman" },
  { id: 64, title: "You Belong with Me", artist: "Taylor Swift" },
  { id: 65, title: "Everybody Wants to Rule the World", artist: "Tears for Fears" },
  { id: 66, title: "Sweet Home Chicago", artist: "The Blues Brothers" },
  { id: 67, title: "Your Love", artist: "The Outfield" },
  { id: 68, title: "I'm Gonna Be (500 Miles)", artist: "The Proclaimers" },
  { id: 69, title: "Under My Thumb", artist: "The Rolling Stones" },
  { id: 70, title: "Can't Feel My Face", artist: "The Weeknd" },
  { id: 71, title: "Beer for My Horses", artist: "Toby Keith" },
  { id: 72, title: "Ten Rounds with Jose Cuervo", artist: "Tracy Byrd" },
  { id: 73, title: "She's in Love With the Boy", artist: "Trisha Yearwood" },
  { id: 74, title: "In The Navy", artist: "Village People" },
  { id: 75, title: "Renegades", artist: "X Ambassadors" },
];
