// AUTO-GENERATED FROM CSV
// Paste into lib/realPlaylists.ts (or replace the matching constants)

export const PLAYLIST_6 = [
  { id: 1, title: "Waterloo", artist: "ABBA" },
  { id: 2, title: "Janie's Got A Gun", artist: "Aerosmith" },
  { id: 3, title: "Girlfriend", artist: "Avril Lavigne" },
  { id: 4, title: "Suga Suga", artist: "Baby Bash" },
  { id: 5, title: "Shape Of My Heart", artist: "Backstreet Boys" },
  { id: 6, title: "One Week", artist: "Barenaked Ladies" },
  { id: 7, title: "Kokomo", artist: "Beach Boys" },
  { id: 8, title: "No Sleep Till Brooklyn", artist: "Beastie Boys" },
  { id: 9, title: "Meant to Be", artist: "Bebe Rexha" },
  { id: 10, title: "Poison", artist: "Bell Biv DeVoe" },
  { id: 11, title: "We Didn't Start the Fire", artist: "Billy Joel" },
  { id: 12, title: "Every Once In a While", artist: "BlackHawk" },
  { id: 13, title: "Honey Bee", artist: "Blake Shelton" },
  { id: 14, title: "I Miss You", artist: "Blink-182" },
  { id: 15, title: "The Tide Is High", artist: "Blondie" },
  { id: 16, title: "Two is Better Than One", artist: "Boys Like Girls" },
  { id: 17, title: "Hurricane", artist: "Bridgit Mendler" },
  { id: 18, title: "You Drive Me Crazy", artist: "Britney Spears" },
  { id: 19, title: "Red Dirt Road", artist: "Brooks & Dunn" },
  { id: 20, title: "Dancing In the Dark", artist: "Bruce Springsteen" },
  { id: 21, title: "Grenade", artist: "Bruno Mars" },
  { id: 22, title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory" },
  { id: 23, title: "See You Again", artist: "Charlie Puth" },
  { id: 24, title: "A Thousand Years", artist: "Christina Perri" },
  { id: 25, title: "Let's Twist Again", artist: "Chubby Checker" },
  { id: 26, title: "Tubthumping", artist: "Chumbawamba" },
  { id: 27, title: "Rockabye", artist: "Clean Bandit" },
  { id: 28, title: "Killin' Time", artist: "Clint Black" },
  { id: 29, title: "Adventure Of A Lifetime", artist: "Coldplay" },
  { id: 30, title: "Gangsta's Paradise", artist: "Coolio" },
  { id: 31, title: "Mmm Mmm Mmm Mmm", artist: "Crash Test Dummies" },
  { id: 32, title: "Time After Time", artist: "Cyndi Lauper" },
  { id: 33, title: "That's The Way It Is", artist: "Céline Dion" },
  { id: 34, title: "Digital Love", artist: "Daft Punk" },
  { id: 35, title: "Welcome To Jamrock", artist: "Damian Marley" },
  { id: 36, title: "Wagon Wheel", artist: "Darius Rucker" },
  { id: 37, title: "Home", artist: "Daughtry" },
  { id: 38, title: "Crash Into Me", artist: "Dave Matthews Band" },
  { id: 39, title: "Just a Gigolo", artist: "David Lee Roth" },
  { id: 40, title: "Breakfast At Tiffany's", artist: "Deep Blue Something" },
  { id: 41, title: "We Are Young", artist: "Fun." },
  { id: 42, title: "Stupid Girl", artist: "Garbage" },
  { id: 43, title: "Friends In Low Places", artist: "Garth Brooks" },
  { id: 44, title: "Midnight Train to Georgia", artist: "Gladys Knight and the Pips" },
  { id: 45, title: "You Belong To The City", artist: "Glenn Frey" },
  { id: 46, title: "Slide", artist: "Goo Goo Dolls" },
  { id: 47, title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  { id: 48, title: "I Feel Good", artist: "James Brown" },
  { id: 49, title: "One Of Us", artist: "Joan Osborne" },
  { id: 50, title: "All of Me", artist: "John Legend" },
  { id: 51, title: "Say", artist: "John Mayer" },
  { id: 52, title: "Constant Craving", artist: "k.d. lang" },
  { id: 53, title: "Bad Romance", artist: "Lady Gaga" },
  { id: 54, title: "Amazed", artist: "Lonestar" },
  { id: 55, title: "Royals", artist: "Lorde" },
  { id: 56, title: "Home", artist: "Michael Bublé" },
  { id: 57, title: "The Climb", artist: "Miley Cyrus" },
  { id: 58, title: "Photograph", artist: "Nickelback" },
  { id: 59, title: "I Write Sins Not Tragedies", artist: "Panic! At The Disco" },
  { id: 60, title: "Hurt Me Bad", artist: "Patty Loveless" },
  { id: 61, title: "Feel It Still", artist: "Portugal. The Man" },
  { id: 62, title: "Love Song", artist: "Sara Bareilles" },
  { id: 63, title: "That Don't Impress Me Much", artist: "Shania Twain" },
  { id: 64, title: "Walkin' On The Sun", artist: "Smash Mouth" },
  { id: 65, title: "Rock This Town", artist: "Stray Cats" },
  { id: 66, title: "I Gotta Feeling", artist: "The Black Eyed Peas" },
  { id: 67, title: "Video Killed the Radio Star", artist: "The Buggles" },
  { id: 68, title: "Don't Let Me Down", artist: "The Chainsmokers" },
  { id: 69, title: "Build Me Up Buttercup", artist: "The Foundations" },
  { id: 70, title: "Louie Louie", artist: "The Kingsmen" },
  { id: 71, title: "Under the Sea", artist: "The Little Mermaid" },
  { id: 72, title: "Satisfaction", artist: "The Rolling Stones" },
  { id: 73, title: "Werewolves Of London", artist: "Warren Zevon" },
  { id: 74, title: "Play That Funky Music", artist: "Wild Cherry" },
  { id: 75, title: "If I Can't Have You", artist: "Yvonne Elliman" },
];

export const PLAYLIST_7 = [
  { id: 1, title: "All That She Wants", artist: "Ace of Base" },
  { id: 2, title: "If I Had You", artist: "Adam Lambert" },
  { id: 3, title: "Rolling in the Deep", artist: "Adele" },
  { id: 4, title: "Crazy", artist: "Aerosmith" },
  { id: 5, title: "Summertime Blues", artist: "Alan Jackson" },
  { id: 6, title: "When You Say Nothing At All", artist: "Alison Krauss" },
  { id: 7, title: "Obsession", artist: "Animotion" },
  { id: 8, title: "I Want It That Way", artist: "Backstreet Boys" },
  { id: 9, title: "If I Had $1,000,000", artist: "Barenaked Ladies" },
  { id: 10, title: "Where's Your Head At", artist: "Basement Jaxx" },
  { id: 11, title: "Fire N Gold", artist: "Bea Miller" },
  { id: 12, title: "Heaven Is A Place On Earth", artist: "Belinda Carlisle" },
  { id: 13, title: "Uptown Girls", artist: "Billy Joel" },
  { id: 14, title: "Bring It All to Me", artist: "Blaque" },
  { id: 15, title: "Rapture", artist: "Blondie" },
  { id: 16, title: "Don't Worry Be Happy", artist: "Bobby McFerrin" },
  { id: 17, title: "Who Says You Can't Go Home", artist: "Bon Jovi" },
  { id: 18, title: "Bottoms Up", artist: "Brantley Gilbert" },
  { id: 19, title: "Oops!...I Did It Again", artist: "Britney Spears" },
  { id: 20, title: "Just The Way You Are", artist: "Bruno Mars" },
  { id: 21, title: "Two Black Cadillacs", artist: "Carrie Underwood" },
  { id: 22, title: "Marvin Gaye", artist: "Charlie Puth" },
  { id: 23, title: "If I Could Turn Back Time", artist: "Cher" },
  { id: 24, title: "The One And Only", artist: "Chesney Hawkes" },
  { id: 25, title: "Dirty", artist: "Christina Aguilera" },
  { id: 26, title: "Little Rock", artist: "Collin Raye" },
  { id: 27, title: "Butterfly", artist: "Crazy Town" },
  { id: 28, title: "Boogie Wonderland", artist: "Earth, Wind & Fire" },
  { id: 29, title: "Burn", artist: "Ellie Goulding" },
  { id: 30, title: "Don't Bring Me Down", artist: "ELO" },
  { id: 31, title: "Pinball Wizard", artist: "Elton John" },
  { id: 32, title: "Jailhouse Rock", artist: "Elvis Presley" },
  { id: 33, title: "The Real Slim Shady", artist: "Eminem" },
  { id: 34, title: "Cruise", artist: "Florida Georgia Line" },
  { id: 35, title: "I Kissed A Girl", artist: "Katy Perry" },
  { id: 36, title: "Celebration", artist: "Kool and the Gang" },
  { id: 37, title: "Black Or White", artist: "Michael Jackson" },
  { id: 38, title: "Pocketful of Sunshine", artist: "Natasha Bedingfield" },
  { id: 39, title: "Sister Christian", artist: "Night Ranger" },
  { id: 40, title: "Don't Know Why", artist: "Norah Jones" },
  { id: 41, title: "Little Talks", artist: "Of Monsters And Men" },
  { id: 42, title: "What Makes You Beautiful", artist: "One Direction" },
  { id: 43, title: "Major Tom", artist: "Peter Schilling" },
  { id: 44, title: "I Wanna Be Your Lover", artist: "Prince" },
  { id: 45, title: "Fight Song", artist: "Rachel Platten" },
  { id: 46, title: "I'm Too Sexy", artist: "Right Said Fred" },
  { id: 47, title: "Push It", artist: "Salt-N-Pepa" },
  { id: 48, title: "Wooly Bully", artist: "Sam the Sham and the Pharaohs" },
  { id: 49, title: "Kiss From a Rose", artist: "Seal" },
  { id: 50, title: "Hips Don't Lie", artist: "Shakira" },
  { id: 51, title: "There She Goes", artist: "Sixpence None the Richer" },
  { id: 52, title: "Tainted Love", artist: "Soft Cell" },
  { id: 53, title: "Oh Sherrie", artist: "Steve Perry" },
  { id: 54, title: "Signed, Sealed, Delivered I'm Yours", artist: "Stevie Wonder" },
  { id: 55, title: "Eye Of The Tiger", artist: "Survivor" },
  { id: 56, title: "Gives You Hell", artist: "The All-American Rejects" },
  { id: 57, title: "Walk Like an Egyptian", artist: "The Bangles" },
  { id: 58, title: "Hard To Handle", artist: "The Black Crowes" },
  { id: 59, title: "My Humps", artist: "The Black Eyed Peas" },
  { id: 60, title: "Wherever You Will Go", artist: "The Calling" },
  { id: 61, title: "Dreams", artist: "The Cranberries" },
  { id: 62, title: "December, 1963 (Oh, What a Night)", artist: "The Four Seasons" },
  { id: 63, title: "Pretty Fly (For A White Guy)", artist: "The Offspring" },
  { id: 64, title: "Who Are You", artist: "The Who" },
  { id: 65, title: "Leave The Pieces", artist: "The Wreckers" },
  { id: 66, title: "She's Not There", artist: "The Zombies" },
  { id: 67, title: "No Scrubs", artist: "TLC" },
  { id: 68, title: "All I Want", artist: "Toad The Wet Sprocket" },
  { id: 69, title: "Made In America", artist: "Toby Keith" },
  { id: 70, title: "Into the Great Wide Open", artist: "Tom Petty" },
  { id: 71, title: "Mony Mony", artist: "Tommy James" },
  { id: 72, title: "Knock Three Times", artist: "Tony Orlando & Dawn" },
  { id: 73, title: "Fast Car", artist: "Tracy Chapman" },
  { id: 74, title: "Brown Eyed Girl", artist: "Van Morrison" },
  { id: 75, title: "Ice Ice Baby", artist: "Vanilla Ice" },
];

export const PLAYLIST_8 = [
  { id: 1, title: "S.O.S.", artist: "ABBA" },
  { id: 2, title: "Thunderstruck", artist: "AC/DC" },
  { id: 3, title: "I Don't Want to Miss a Thing", artist: "Aerosmith" },
  { id: 4, title: "Honey I'm Good", artist: "Andy Grammer" },
  { id: 5, title: "Walking on Broken Glass", artist: "Annie Lennox" },
  { id: 6, title: "Barbie Girl", artist: "Aqua" },
  { id: 7, title: "thank u, next", artist: "Ariana Grande" },
  { id: 8, title: "Larger Than Life", artist: "Backstreet Boys" },
  { id: 9, title: "Mad About You", artist: "Belinda Carlisle" },
  { id: 10, title: "Dancing With Myself", artist: "Billy Idol" },
  { id: 11, title: "I Want Candy", artist: "Bow Wow Wow" },
  { id: 12, title: "Punk Rock 101", artist: "Bowling For Soup" },
  { id: 13, title: "I'll Make Love To You", artist: "Boyz II Men" },
  { id: 14, title: "I'm Gonna Miss Her", artist: "Brad Paisley" },
  { id: 15, title: "Toxic", artist: "Britney Spears" },
  { id: 16, title: "Boot Scootin' Boogie", artist: "Brooks and Dunn" },
  { id: 17, title: "Ms. New Booty", artist: "Bubba Sparxxx" },
  { id: 18, title: "Tuesday", artist: "Burak Yeter" },
  { id: 19, title: "Bad Bunny", artist: "Cardi B" },
  { id: 20, title: "Kung Fu Fighting", artist: "Carl Douglas" },
  { id: 21, title: "Call Me Maybe", artist: "Carly Rae Jepsen" },
  { id: 22, title: "I'm Every Woman", artist: "Chaka Khan" },
  { id: 23, title: "One Call Away", artist: "Charlie Puth" },
  { id: 24, title: "Genie in a Bottle", artist: "Christina Aguilera" },
  { id: 25, title: "A Sky Full Of Stars", artist: "Coldplay" },
  { id: 26, title: "Going Up Around the Bend", artist: "Creedence Clearwater Revival" },
  { id: 27, title: "Titanium", artist: "David Guetta" },
  { id: 28, title: "Strawberry Wine", artist: "Deana Carter" },
  { id: 29, title: "Give Your Heart a Break", artist: "Demi Lovato" },
  { id: 30, title: "Runaround Sue", artist: "Dion & The Belmonts" },
  { id: 31, title: "9 To 5", artist: "Dolly Parton" },
  { id: 32, title: "Suspicious Minds", artist: "Dwight Yoakam" },
  { id: 33, title: "Save Tonight", artist: "Eagle-Eye Cherry" },
  { id: 34, title: "I Love a Rainy Night", artist: "Eddie Rabbitt" },
  { id: 35, title: "Blue", artist: "Eiffel 65" },
  { id: 36, title: "Ex's & Oh's", artist: "Elle King" },
  { id: 37, title: "Love Me Like You Do", artist: "Ellie Goulding" },
  { id: 38, title: "Benny and the Jets", artist: "Elton John" },
  { id: 39, title: "Sweet Dreams", artist: "Eurythmics" },
  { id: 40, title: "I Will Buy You A New Life", artist: "Everclear" },
  { id: 41, title: "The Way", artist: "Fastball" },
  { id: 42, title: "100 Years", artist: "Five for Fighting" },
  { id: 43, title: "Some Nights", artist: "Fun." },
  { id: 44, title: "I Can't Dance", artist: "Genesis" },
  { id: 45, title: "Check Yes Or No", artist: "George Strait" },
  { id: 46, title: "Iris", artist: "Goo Goo Dolls" },
  { id: 47, title: "Here for The Party", artist: "Gretchen Wilson" },
  { id: 48, title: "What Is Love", artist: "Haddaway" },
  { id: 49, title: "Take Me To Church", artist: "Hozier" },
  { id: 50, title: "Let It Go", artist: "Idina Menzel" },
  { id: 51, title: "Need You Tonight", artist: "INXS" },
  { id: 52, title: "Papi", artist: "Jennifer Lopez" },
  { id: 53, title: "Carry on Wayward Son", artist: "Kansas" },
  { id: 54, title: "Dark Horse", artist: "Katy Perry" },
  { id: 55, title: "Red High Heels", artist: "Kellie Pickler" },
  { id: 56, title: "Breakaway", artist: "Kelly Clarkson" },
  { id: 57, title: "Born This Way", artist: "Lady Gaga" },
  { id: 58, title: "Funky Town", artist: "Lipps Inc." },
  { id: 59, title: "The Mummers' Dance", artist: "Loreena McKennitt" },
  { id: 60, title: "Fly", artist: "Maddie & Tae" },
  { id: 61, title: "The House That Built Me", artist: "Miranda Lambert" },
  { id: 62, title: "Carnival", artist: "Natalie Merchant" },
  { id: 63, title: "Hit Me With Your Best Shot", artist: "Pat Benatar" },
  { id: 64, title: "Blame It On Your Lyin' Cheatin' Heart", artist: "Patty Loveless" },
  { id: 65, title: "Harden My Heart", artist: "Quarterflash" },
  { id: 66, title: "Pretty Woman", artist: "Roy Orbison" },
  { id: 67, title: "Little Good-Byes", artist: "SHeDAISY" },
  { id: 68, title: "Why Can't We Be Friends", artist: "Smash Mouth" },
  { id: 69, title: "Copperhead Road", artist: "Steve Earle" },
  { id: 70, title: "Paperback Writer", artist: "The Beatles" },
  { id: 71, title: "Rawhide", artist: "The Blues Brothers" },
  { id: 72, title: "Holler Back", artist: "The Lost Trailers" },
  { id: 73, title: "The Kids Aren't Alright", artist: "The Offspring" },
  { id: 74, title: "Buttons", artist: "The Pussycat Dolls" },
  { id: 75, title: "Leader of the Pack", artist: "Twisted Sister" },
];

export const PLAYLIST_9 = [
  { id: 1, title: "Dancing Queen", artist: "Abba" },
  { id: 2, title: "I Love the Nightlife", artist: "Alicia Bridges" },
  { id: 3, title: "Wake Me Up", artist: "Avicii" },
  { id: 4, title: "Copacabana", artist: "Barry Manilow" },
  { id: 5, title: "I Got You", artist: "Bebe Rexha" },
  { id: 6, title: "Stayin' Alive", artist: "Bee Gees" },
  { id: 7, title: "Just the Way You Are", artist: "Billy Joel" },
  { id: 8, title: "Wanted Dead Or Alive", artist: "Bon Jovi" },
  { id: 9, title: "That Ain't No Way To Go", artist: "Brooks & Dunn" },
  { id: 10, title: "The Lazy Song", artist: "Bruno Mars" },
  { id: 11, title: "Before He Cheats", artist: "Carrie Underwood" },
  { id: 12, title: "Everytime We Touch", artist: "Cascada" },
  { id: 13, title: "It Was", artist: "Chely Wright" },
  { id: 14, title: "Jar of Hearts", artist: "Christina Perri" },
  { id: 15, title: "Sunglasses At Night", artist: "Corey Hart" },
  { id: 16, title: "True Colors", artist: "Cyndi Lauper" },
  { id: 17, title: "Tequila", artist: "Dan + Shay" },
  { id: 18, title: "I Can Dream About You", artist: "Dan Hartman" },
  { id: 19, title: "You Spin Me Round", artist: "Dead Or Alive" },
  { id: 20, title: "Bills, Bills, Bills", artist: "Destiny's Child" },
  { id: 21, title: "Whip It!", artist: "Devo" },
  { id: 22, title: "The Wanderer", artist: "Dion & The Belmonts" },
  { id: 23, title: "You're Welcome", artist: "Dwayne Johnson" },
  { id: 24, title: "Two Tickets To Paradise", artist: "Eddie Money" },
  { id: 25, title: "All Over The World", artist: "ELO" },
  { id: 26, title: "Bailando", artist: "Enrique Iglesias" },
  { id: 27, title: "Springsteen", artist: "Eric Church" },
  { id: 28, title: "My Immortal", artist: "Evanescence" },
  { id: 29, title: "Breathe", artist: "Faith Hill" },
  { id: 30, title: "My Songs Know What You Did In The Dark", artist: "Fall Out Boy" },
  { id: 31, title: "Dog Days Are Over", artist: "Florence & the Machine" },
  { id: 32, title: "This Is How We Roll", artist: "Florida Georgia Line" },
  { id: 33, title: "Only Happy When It Rains", artist: "Garbage" },
  { id: 34, title: "Got My Mind Set On You", artist: "George Harrison" },
  { id: 35, title: "Summer Nights", artist: "Grease" },
  { id: 36, title: "November Rain", artist: "Guns N' Roses" },
  { id: 37, title: "All I Wanna Do Is Make Love To You", artist: "Heart" },
  { id: 38, title: "Stuck With You", artist: "Huey Lewis And The News" },
  { id: 39, title: "Get Up Offa That Thing", artist: "James Brown" },
  { id: 40, title: "Tequila Makes Her Clothes Fall Off", artist: "Joe Nichols" },
  { id: 41, title: "Issues", artist: "Julia Michaels" },
  { id: 42, title: "Praying", artist: "Ke$ha" },
  { id: 43, title: "Already Gone", artist: "Kelly Clarkson" },
  { id: 44, title: "The Gambler", artist: "Kenny Rogers" },
  { id: 45, title: "Poker Face", artist: "Lady Gaga" },
  { id: 46, title: "Black Magic", artist: "Little Mix" },
  { id: 47, title: "7 Years", artist: "Lukas Graham" },
  { id: 48, title: "Ray Of Light", artist: "Madonna" },
  { id: 49, title: "Love Somebody", artist: "Maroon 5" },
  { id: 50, title: "Please Mr. Postman", artist: "Marvelettes" },
  { id: 51, title: "U Can't Touch This", artist: "MC Hammer" },
  { id: 52, title: "Who Can It Be Now", artist: "Men At Work" },
  { id: 53, title: "It's A Beautiful Day", artist: "Michael Bublé" },
  { id: 54, title: "Rock With You", artist: "Michael Jackson" },
  { id: 55, title: "I'm Gonna Miss You Girl", artist: "Michael Martin Murphey" },
  { id: 56, title: "Lady Marmalade", artist: "Mya" },
  { id: 57, title: "These Boots Are Made for Walkin'", artist: "Nancy Sinatra" },
  { id: 58, title: "America", artist: "Neil Diamond" },
  { id: 59, title: "Rockstar", artist: "Nickelback" },
  { id: 60, title: "Don't Speak", artist: "No Doubt" },
  { id: 61, title: "Wonderwall", artist: "Oasis" },
  { id: 62, title: "Hey Ya!", artist: "OutKast" },
  { id: 63, title: "High Hopes", artist: "Panic! At The Disco" },
  { id: 64, title: "We Belong", artist: "Pat Benatar" },
  { id: 65, title: "Happy", artist: "Pharrell Williams" },
  { id: 66, title: "Livin' La Vida Loca", artist: "Ricky Martin" },
  { id: 67, title: "Forever And For Always", artist: "Shania Twain" },
  { id: 68, title: "Candy Rain", artist: "Soul For Real" },
  { id: 69, title: "Every Morning", artist: "Sugar Ray" },
  { id: 70, title: "Tell It to My Heart", artist: "Taylor Dayne" },
  { id: 71, title: "Shake It Off", artist: "Taylor Swift" },
  { id: 72, title: "Home", artist: "The Magnetic Zeros" },
  { id: 73, title: "Firestarter", artist: "The Prodigy" },
  { id: 74, title: "When I Grow Up", artist: "The Pussycat Dolls" },
  { id: 75, title: "Happy Together", artist: "The Turtles" },
];

export const PLAYLIST_10 = [
  { id: 1, title: "Chattahoochee", artist: "Alan Jackson" },
  { id: 2, title: "Think", artist: "Aretha Franklin" },
  { id: 3, title: "Airplanes", artist: "B.o.B" },
  { id: 4, title: "Who Let The Dogs Out", artist: "Baha Men" },
  { id: 5, title: "Surfin USA", artist: "Beach Boys" },
  { id: 6, title: "(You Gotta) Fight For Your Right (To Party)", artist: "Beastie Boys" },
  { id: 7, title: "White Wedding", artist: "Billy Idol" },
  { id: 8, title: "All The Small Things", artist: "blink-182" },
  { id: 9, title: "Heart of Glass", artist: "Blondie" },
  { id: 10, title: "The Bad Touch", artist: "Bloodhound Gang" },
  { id: 11, title: "Total Eclipse of the Heart", artist: "Bonnie Tyler" },
  { id: 12, title: "Baby One More Time", artist: "Britney Spears" },
  { id: 13, title: "Uptown Funk", artist: "Bruno Mars" },
  { id: 14, title: "Devil Went Down to Georgia", artist: "Charlie Daniels Band" },
  { id: 15, title: "Le Freak", artist: "Chic" },
  { id: 16, title: "On The Verge", artist: "Collin Raye" },
  { id: 17, title: "Woodstock", artist: "Crosby, Stills & Nash" },
  { id: 18, title: "Instant Crush", artist: "Daft Punk" },
  { id: 19, title: "Let's Dance", artist: "David Bowie" },
  { id: 20, title: "Soul Meets Body", artist: "Death Cab for Cutie" },
  { id: 21, title: "Smoke On The Water", artist: "Deep Purple" },
  { id: 22, title: "September", artist: "Earth, Wind & Fire" },
  { id: 23, title: "Perfect", artist: "Ed Sheeran" },
  { id: 24, title: "I'll Be", artist: "Edwin McCain" },
  { id: 25, title: "My Lovin' You're Never Gonna Get It", artist: "En Vogue" },
  { id: 26, title: "Call On Me", artist: "Eric Prydz" },
  { id: 27, title: "Inside Out", artist: "Eve 6" },
  { id: 28, title: "Epic", artist: "Faith No More" },
  { id: 29, title: "Blueberry Hill", artist: "Fats Domino" },
  { id: 30, title: "Go Your Own Way", artist: "Fleetwood Mac" },
  { id: 31, title: "Take Me Out", artist: "Franz Ferdinand" },
  { id: 32, title: "The Anthem", artist: "Good Charlotte" },
  { id: 33, title: "Hollaback Girl", artist: "Gwen Stefani" },
  { id: 34, title: "Maneater", artist: "Hall & Oates" },
  { id: 35, title: "Thunder", artist: "Imagine Dragons" },
  { id: 36, title: "Want to Want Me", artist: "Jason Derulo" },
  { id: 37, title: "Bye Bye", artist: "Jo Dee Messina" },
  { id: 38, title: "Don't Stop Believin'", artist: "Journey" },
  { id: 39, title: "Asking Us To Dance", artist: "Kathy Mattea" },
  { id: 40, title: "Cop Car", artist: "Keith Urban" },
  { id: 41, title: "When You Say Nothing at All", artist: "Keith Whitley" },
  { id: 42, title: "Danger Zone", artist: "Kenny Loggins" },
  { id: 43, title: "Jungle Boogie", artist: "Kool and the Gang" },
  { id: 44, title: "Downtown", artist: "Lady Antebellum" },
  { id: 45, title: "Stay", artist: "Lisa Loeb" },
  { id: 46, title: "Sweet Home Alabama", artist: "Lynyrd Skynyrd" },
  { id: 47, title: "Dancing in the Streets", artist: "Martha & The Vandellas" },
  { id: 48, title: "Animals", artist: "Martin Garrix" },
  { id: 49, title: "2 Legit 2 Quit", artist: "MC Hammer" },
  { id: 50, title: "I'd Do Anything For Love", artist: "Meat Loaf" },
  { id: 51, title: "Nothing Else Matters", artist: "Metallica" },
  { id: 52, title: "How Am I Supposed To Live Without You", artist: "Michael Bolton" },
  { id: 53, title: "Billie Jean", artist: "Michael Jackson" },
  { id: 54, title: "In the summertime", artist: "Mungo Jerry" },
  { id: 55, title: "Lean On", artist: "MO" },
  { id: 56, title: "Torn", artist: "Natalie Imbruglia" },
  { id: 57, title: "Candy Girl", artist: "New Edition" },
  { id: 58, title: "Smells Like Teen Spirit", artist: "Nirvana" },
  { id: 59, title: "Bye Bye Bye", artist: "NSYNC" },
  { id: 60, title: "Counting Stars", artist: "One Republic" },
  { id: 61, title: "Let Her Go", artist: "Passenger" },
  { id: 62, title: "You Can Call Me Al", artist: "Paul Simon" },
  { id: 63, title: "Hit the road Jack!", artist: "Ray Charles" },
  { id: 64, title: "Waka Waka", artist: "Shakira" },
  { id: 65, title: "Next To You, Next To Me", artist: "Shenandoah" },
  { id: 66, title: "Hey Cinderella", artist: "Suzy Bogguss" },
  { id: 67, title: "Let's Get It Started", artist: "The Black Eyed Peas" },
  { id: 68, title: "Our Lips Are Sealed", artist: "The Go-Gos" },
  { id: 69, title: "I Want You Back", artist: "The Jackson 5" },
  { id: 70, title: "Ho Hey", artist: "The Lumineers" },
  { id: 71, title: "I'm a Believer", artist: "The Monkees" },
  { id: 72, title: "Elvira", artist: "The Oak Ridge Boys" },
  { id: 73, title: "I Hate This Part", artist: "The Pussycat Dolls" },
  { id: 74, title: "End Of The Line", artist: "The Traveling Wilburys" },
  { id: 75, title: "Baba O'Riley", artist: "The Who" },
];

